# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "yaml_logs_test",
    srcs = [
        "yaml_logs_test.cc",
    ],
    tags = [
        "test",
        "yaml",
    ],
    deps = [
        "//api",
        "//sdk:headers",
        "//sdk/src/configuration",
        "//sdk/src/logs",
        "//sdk/src/metrics",
        "//sdk/src/trace",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "yaml_metrics_test",
    srcs = [
        "yaml_metrics_test.cc",
    ],
    tags = [
        "test",
        "yaml",
    ],
    deps = [
        "//api",
        "//sdk:headers",
        "//sdk/src/configuration",
        "//sdk/src/logs",
        "//sdk/src/metrics",
        "//sdk/src/trace",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "yaml_propagator_test",
    srcs = [
        "yaml_propagator_test.cc",
    ],
    tags = [
        "test",
        "yaml",
    ],
    deps = [
        "//api",
        "//sdk:headers",
        "//sdk/src/configuration",
        "//sdk/src/logs",
        "//sdk/src/metrics",
        "//sdk/src/trace",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "yaml_resource_test",
    srcs = [
        "yaml_resource_test.cc",
    ],
    tags = [
        "test",
        "yaml",
    ],
    deps = [
        "//api",
        "//sdk:headers",
        "//sdk/src/configuration",
        "//sdk/src/logs",
        "//sdk/src/metrics",
        "//sdk/src/trace",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "yaml_test",
    srcs = [
        "yaml_test.cc",
    ],
    tags = [
        "test",
        "yaml",
    ],
    deps = [
        "//api",
        "//sdk:headers",
        "//sdk/src/configuration",
        "//sdk/src/logs",
        "//sdk/src/metrics",
        "//sdk/src/trace",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "yaml_trace_test",
    srcs = [
        "yaml_trace_test.cc",
    ],
    tags = [
        "test",
        "yaml",
    ],
    deps = [
        "//api",
        "//sdk:headers",
        "//sdk/src/configuration",
        "//sdk/src/logs",
        "//sdk/src/metrics",
        "//sdk/src/trace",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "yaml_distribution_test",
    srcs = [
        "yaml_distribution_test.cc",
    ],
    tags = [
        "test",
        "yaml",
    ],
    deps = [
        "//api",
        "//sdk:headers",
        "//sdk/src/configuration",
        "//sdk/src/logs",
        "//sdk/src/metrics",
        "//sdk/src/trace",
        "@com_google_googletest//:gtest_main",
    ],
)
