\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename tokudb.info
@settitle The TokuDB Embedded Database
@c %**end of header

@copying
Copyright @copyright{} 2007, Tokutek, Inc.
@end copying

@titlepage
@title TokuDB Programmmer's Manual
@subtitle for the Tokutek Embedded Database
@author Tokutek, Inc.

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage 

@contents

@ifnottex
@node Top
@top TokuDB
@menu tdb_create::

@insertcopying
@end ifnottex

@include intro.texi

@node TokuDB C API
@chapter TokuDB C API

@include tdb_create.texi

@node Index
@unnumbered Index

@printindex

@bye

