var categories = [
	
	{ tag: "Bidi-text", label: "Bidi test for Mobile widgets"},
	{ tag: "Bidi-mirroring", label: "Bidi mirroring for Mobile widgets"}
];
var tests = [
	{ url: "Bidi_Accordion.html", tags: "Bidi-text" },
	{ url: "Bidi_Button.html", tags: "Bidi-text" },
	{ url: "Bidi_ComboBox.html", tags: "Bidi-text" },
	{ url: "Bidi_Dialog.html", tags: "Bidi-text" },
	{ url: "Bidi_EdgeToEdgeCategoryList.html", tags: "Bidi-text" },
	{ url: "Bidi_EdgeToEdgeDataList.html", tags: "Bidi-text" },
	{ url: "Bidi_EdgeToEdgeList.html", tags: "Bidi-text" },
	{ url: "Bidi_EdgeToEdgeStoreList.html", tags: "Bidi-text" },
	{ url: "Bidi_Heading.html", tags: "Bidi-text" },
	{ url: "Bidi_IconContainer.html", tags: "Bidi-text" },
	{ url: "Bidi_IconMenu.html", tags: "Bidi-text" },
	{ url: "Bidi_RoundRectCategoryList.html", tags: "Bidi-text" },
	{ url: "Bidi_SearchBox.html", tags: "Bidi-text" },
	{ url: "Bidi_SpinWheel.html", tags: "Bidi-text" },
	{ url: "Bidi_StoreCarousel.html", tags: "Bidi-text" },
	{ url: "Bidi_Switch.html", tags: "Bidi-text" },
	{ url: "Bidi_TabBar.html", tags: "Bidi-text" },
	{ url: "Bidi_TextArea.html", tags: "Bidi-text" },
	{ url: "Bidi_TextBox.html", tags: "Bidi-text" },
	{ url: "Bidi_ToggleButton.html", tags: "Bidi-text" },
	{ url: "Bidi_Tooltip.html", tags: "Bidi-text" },
	{ url: "Bidi_TreeView.html", tags: "Bidi-text" },	
	{ url: "Bidi_ValuePicker.html", tags: "Bidi-text" },
	{ url: "test_Carousel_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_Carousel_rtl-compat.html", tags: "Bidi-mirroring" },
	{ url: "test_ComboBox_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_EdgeToEdgeDataList_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_EdgeToEdgeList_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_EdgeToEdgeStoreList_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_FixedSplitter-H2_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_FixedSplitter-V2H2-change_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_Heading_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_IconContainer_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_IconMenu-standalone_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_RoundRectDataList_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_RoundRectList_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_RoundRectList-check_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_RoundRectStoreList_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_SpinWheel-custom_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_SwapView_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_Switch_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_TabBar_rtl.html", tags: "Bidi-mirroring" },
	{ url: "test_ToggleButton_rtl.html", tags: "Bidi-mirroring" }

];
