define(
//begin v1.x content
{
	"field-second-relative+0": "teraz",
	"field-weekday": "deň v týždni",
	"field-wed-relative+0": "túto stredu",
	"dateFormatItem-GyMMMEd": "E, d. MMM y G",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"field-wed-relative+1": "budúcu stredu",
	"field-tue-relative+-1": "minulý utorok",
	"dateFormat-long": "d. MMMM y G",
	"field-fri-relative+-1": "minulý piatok",
	"field-wed-relative+-1": "minulú stredu",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormat-full": "EEEE, d. MMMM y G",
	"dateFormatItem-yyyyMEd": "E d. M. y G",
	"field-thu-relative+-1": "minulý štvrtok",
	"dateFormatItem-Md": "d.M.",
	"field-era": "letopočet",
	"field-year": "rok",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"field-hour": "hodina",
	"field-sat-relative+0": "túto sobotu",
	"field-sat-relative+1": "budúcu sobotu",
	"field-day-relative+0": "dnes",
	"field-day-relative+1": "zajtra",
	"field-thu-relative+0": "tento štvrtok",
	"dateFormatItem-GyMMMd": "d.M.y G",
	"field-day-relative+2": "pozajtra",
	"field-thu-relative+1": "budúci štvrtok",
	"dateFormatItem-H": "H",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-yyyyMMMEd": "E, d. MMM y G",
	"dateFormatItem-M": "L.",
	"dateFormatItem-yyyyMMM": "LLL y G",
	"dateFormatItem-yyyyMMMd": "d.M.y G",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-GyMMMMd": "d. MMMM y G",
	"field-sun-relative+0": "túto nedeľu",
	"dateFormatItem-Hm": "H:mm",
	"field-sun-relative+1": "budúcu nedeľu",
	"field-minute": "minúta",
	"field-dayperiod": "časť dňa",
	"dateFormatItem-d": "d.",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "včera",
	"dateFormatItem-h": "h a",
	"dateTimeFormat-long": "{1} {0}",
	"field-day-relative+-2": "predvčerom",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MEd": "E, d.M.",
	"dateTimeFormat-full": "{1} {0}",
	"field-fri-relative+0": "tento piatok",
	"field-fri-relative+1": "budúci piatok",
	"field-day": "deň",
	"field-zone": "časové pásmo",
	"dateFormatItem-y": "y G",
	"field-year-relative+-1": "minulý rok",
	"field-month-relative+-1": "minulý mesiac",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-yyyyMMMMd": "d. MMMM y G",
	"dateFormatItem-yyyyMd": "d.M.y G",
	"field-month": "mesiac",
	"dateFormatItem-MMM": "LLL",
	"field-tue-relative+0": "tento utorok",
	"field-tue-relative+1": "budúci utorok",
	"dateFormatItem-MMMMEd": "E, d. MMMM",
	"field-mon-relative+0": "tento pondelok",
	"field-mon-relative+1": "budúci pondelok",
	"dateFormat-short": "d.M.y GGGGG",
	"field-second": "sekunda",
	"field-sat-relative+-1": "minulú sobotu",
	"field-sun-relative+-1": "minulú nedeľu",
	"field-month-relative+0": "tento mesiac",
	"field-month-relative+1": "budúci mesiac",
	"dateFormatItem-Ed": "E d.",
	"field-week": "týždeň",
	"dateFormat-medium": "d.M.y G",
	"field-year-relative+0": "tento rok",
	"field-week-relative+-1": "minulý týždeň",
	"dateFormatItem-yyyyM": "M.y G",
	"field-year-relative+1": "budúci rok",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-GyMMM": "LLL y G",
	"field-mon-relative+-1": "minulý pondelok",
	"dateFormatItem-yyyy": "y G",
	"field-week-relative+0": "tento týždeň",
	"field-week-relative+1": "budúci týždeň"
}
//end v1.x content
);