define(
//begin v1.x content
{
	"dateFormatItem-Ehm": "E h:mm a",
	"days-standAlone-short": [
		"Ne",
		"Po",
		"Ut",
		"St",
		"Št",
		"Pi",
		"So"
	],
	"months-format-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"field-second-relative+0": "teraz",
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-weekday": "deň v týždni",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E d. M. y",
	"field-wed-relative+0": "túto stredu",
	"field-wed-relative+1": "budúcu stredu",
	"dateFormatItem-GyMMMEd": "E, d. MMMM y G",
	"dateFormatItem-MMMEd": "E, d. M.",
	"eraNarrow": [
		"pred Kr.",
		"po Kr."
	],
	"field-tue-relative+-1": "minulý utorok",
	"days-format-short": [
		"Ne",
		"Po",
		"Ut",
		"St",
		"Št",
		"Pi",
		"So"
	],
	"dateFormat-long": "d. MMMM y",
	"field-fri-relative+-1": "minulý piatok",
	"field-wed-relative+-1": "minulú stredu",
	"months-format-wide": [
		"januára",
		"februára",
		"marca",
		"apríla",
		"mája",
		"júna",
		"júla",
		"augusta",
		"septembra",
		"októbra",
		"novembra",
		"decembra"
	],
	"dateTimeFormat-medium": "{1}, {0}",
	"dateFormatItem-yMMMMd": "d. MMMM y",
	"dayPeriods-format-wide-pm": "odpoludnia",
	"dateFormat-full": "EEEE, d. MMMM y",
	"field-thu-relative+-1": "minulý štvrtok",
	"dateFormatItem-Md": "d. M.",
	"dateFormatItem-yMd": "d. M. y",
	"field-era": "letopočet",
	"dateFormatItem-yM": "M/y",
	"months-standAlone-wide": [
		"január",
		"február",
		"marec",
		"apríl",
		"máj",
		"jún",
		"júl",
		"august",
		"september",
		"október",
		"november",
		"december"
	],
	"timeFormat-short": "H:mm",
	"quarters-format-wide": [
		"1. štvrťrok",
		"2. štvrťrok",
		"3. štvrťrok",
		"4. štvrťrok"
	],
	"dateFormatItem-yQQQQ": "QQQQ y",
	"timeFormat-long": "H:mm:ss z",
	"field-year": "rok",
	"dateFormatItem-yMMM": "LLLL y",
	"field-hour": "hodina",
	"months-format-abbr": [
		"jan",
		"feb",
		"mar",
		"apr",
		"máj",
		"jún",
		"júl",
		"aug",
		"sep",
		"okt",
		"nov",
		"dec"
	],
	"field-sat-relative+0": "túto sobotu",
	"field-sat-relative+1": "budúcu sobotu",
	"timeFormat-full": "H:mm:ss zzzz",
	"field-day-relative+0": "dnes",
	"field-thu-relative+0": "tento štvrtok",
	"field-day-relative+1": "zajtra",
	"field-thu-relative+1": "budúci štvrtok",
	"dateFormatItem-GyMMMd": "d. M. y G",
	"field-day-relative+2": "pozajtra",
	"dateFormatItem-H": "H",
	"months-standAlone-abbr": [
		"jan",
		"feb",
		"mar",
		"apr",
		"máj",
		"jún",
		"júl",
		"aug",
		"sep",
		"okt",
		"nov",
		"dec"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-wide": [
		"1. štvrťrok",
		"2. štvrťrok",
		"3. štvrťrok",
		"4. štvrťrok"
	],
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-M": "L.",
	"days-standAlone-wide": [
		"nedeľa",
		"pondelok",
		"utorok",
		"streda",
		"štvrtok",
		"piatok",
		"sobota"
	],
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-GyMMMMd": "d. MMMM y G",
	"timeFormat-medium": "H:mm:ss",
	"field-sun-relative+0": "túto nedeľu",
	"dateFormatItem-Hm": "H:mm",
	"field-sun-relative+1": "budúcu nedeľu",
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"eraAbbr": [
		"pred Kr.",
		"po Kr."
	],
	"field-minute": "minúta",
	"field-dayperiod": "časť dňa",
	"days-standAlone-abbr": [
		"ne",
		"po",
		"ut",
		"st",
		"št",
		"pi",
		"so"
	],
	"dateFormatItem-d": "d.",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "včera",
	"dateFormatItem-h": "h a",
	"dateTimeFormat-long": "{1}, {0}",
	"field-day-relative+-2": "predvčerom",
	"dateFormatItem-MMMd": "d. M",
	"dateFormatItem-MEd": "E, d. M.",
	"dateTimeFormat-full": "{1}, {0}",
	"field-fri-relative+0": "tento piatok",
	"dateFormatItem-yMMMM": "LLLL y",
	"field-fri-relative+1": "budúci piatok",
	"field-day": "deň",
	"days-format-wide": [
		"nedeľa",
		"pondelok",
		"utorok",
		"streda",
		"štvrtok",
		"piatok",
		"sobota"
	],
	"field-zone": "časové pásmo",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"field-year-relative+-1": "minulý rok",
	"field-month-relative+-1": "minulý mesiac",
	"dateFormatItem-hm": "h:mm a",
	"days-format-abbr": [
		"ne",
		"po",
		"ut",
		"st",
		"št",
		"pi",
		"so"
	],
	"dateFormatItem-yMMMd": "d. M. y",
	"eraNames": [
		"pred Kristom",
		"po Kristovi"
	],
	"days-format-narrow": [
		"N",
		"P",
		"U",
		"S",
		"Š",
		"P",
		"S"
	],
	"days-standAlone-narrow": [
		"N",
		"P",
		"U",
		"S",
		"Š",
		"P",
		"S"
	],
	"dateFormatItem-MMM": "LLL",
	"field-month": "mesiac",
	"field-tue-relative+0": "tento utorok",
	"field-tue-relative+1": "budúci utorok",
	"dayPeriods-format-wide-am": "dopoludnia",
	"dateFormatItem-MMMMEd": "E, d. MMMM",
	"dateFormatItem-EHm": "E HH:mm",
	"field-mon-relative+0": "tento pondelok",
	"field-mon-relative+1": "budúci pondelok",
	"dateFormat-short": "dd.MM.yy",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"field-second": "sekunda",
	"field-sat-relative+-1": "minulú sobotu",
	"dateFormatItem-yMMMEd": "E d. M. y",
	"field-sun-relative+-1": "minulú nedeľu",
	"field-month-relative+0": "tento mesiac",
	"field-month-relative+1": "budúci mesiac",
	"dateFormatItem-Ed": "E d.",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-week": "týždeň",
	"dateFormat-medium": "d. M. y",
	"field-year-relative+0": "tento rok",
	"field-week-relative+-1": "minulý týždeň",
	"field-year-relative+1": "budúci rok",
	"dateFormatItem-mmss": "mm:ss",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-GyMMM": "LLLL y G",
	"field-mon-relative+-1": "minulý pondelok",
	"field-week-relative+0": "tento týždeň",
	"field-week-relative+1": "budúci týždeň"
}
//end v1.x content
);