include .defs.mk

TYPE := util

BIN_TARGET := sp_test
BIN_TARGET_ARCHIVES := portlib general

SOURCES := sp_test.cpp

CCFLAGS_LOC += -I$(call fixpath,$(NDB_TOP)/include/util)

include $(NDB_TOP)/Epilogue.mk
