#!/bin/sh

if [ "$BK_USER" = "Administrator" -o "$BK_USER" = "mysqldev" ]
then
 echo "Error: you cannot checkin as 'Administrator' or 'mysqldev' user."
 echo "as a workaround set BK_USER to your nickname"
 echo "e.g.: export BK_USER='bar'"
 echo ""
 echo "Checkin FAILED!"
 echo "Set BK_USER and retry."
 exit 1
fi

if [ `tail -c1 $BK_FILE` ]
then
 echo "File $BK_FILE does not end with a new-line character!"
 echo ""
 echo "Checkin FAILED!"
 echo "Fix the problem and retry."
 exit 1
fi

