.TH ARIA_FTDUMP "1" "May 2014" "aria_ftdump Ver 1.0" "User Commands"
.SH NAME
aria_ftdump \- display full\-text index information
.SH DESCRIPTION
Use: aria_ft_dump <table_name> <index_num>
.TP
\fB\-?\fR, \fB\-h\fR, \fB\-\-help\fR
Display help and exit.
.TP
\fB\-c\fR, \fB\-\-count\fR
Calculate per\-word stats (counts and global weights).
.TP
\fB\-d\fR, \fB\-\-dump\fR
Dump index (incl. data offsets and word weights).
.TP
\fB\-l\fR, \fB\-\-length\fR
Report length distribution.
.TP
\fB\-s\fR, \fB\-\-stats\fR
Report global stats.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be verbose.
.PP
.SH "SEE ALSO"
\fBmyisam_ftdump(1)\fR
.PP
For more information, please refer to the MariaDB Knowledge Base,
which is available online at http://mariadb.com/kb/
