.\"     Title: \fBmysqlbug\fR
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 03/31/2009
.\"    Manual: MySQL Database System
.\"    Source: MySQL 5.1
.\"
.TH "\fBMYSQLBUG\fR" "1" "03/31/2009" "MySQL 5.1" "MySQL Database System"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
mysqlbug \- generate bug report
.SH "SYNOPSIS"
.HP 9
\fBmysqlbug\fR
.SH "DESCRIPTION"
.PP
This program enables you to generate a bug report and send it to MySQL AB. It is a shell script and runs on Unix.
.PP
The normal way to report bugs is to visit
\fI\%http://bugs.mysql.com/\fR, which is the address for our bugs database. This database is public and can be browsed and searched by anyone. If you log in to the system, you can enter new reports. If you have no Web access, you can generate a bug report by using the
\fBmysqlbug\fR
script.
.PP
\fBmysqlbug\fR
helps you generate a report by determining much of the following information automatically, but if something important is missing, please include it with your message.
\fBmysqlbug\fR
can be found in the
\fIscripts\fR
directory (source distribution) and in the
\fIbin\fR
directory under your MySQL installation directory (binary distribution).
.PP
Invoke
\fBmysqlbug\fR
without arguments:
.sp
.RS 3n
.nf
shell> \fBmysqlbug\fR
.fi
.RE
.PP
The script will place you in an editor with a copy of the report to be sent. Edit the lines near the beginning that indicate the nature of the problem. Then write the file to save your changes, quit the editor, and
\fBmysqlbug\fR
will send the report by email. perform.
.SH "COPYRIGHT"
.PP
Copyright 2007\-2008 MySQL AB, 2009 Sun Microsystems, Inc.
.PP
This documentation is free software; you can redistribute it and/or modify it only under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110\-1301 USA or see http://www.gnu.org/licenses/.
.SH "SEE ALSO"
For more information, please refer to the MySQL Reference Manual,
which may already be installed locally and which is also available
online at http://dev.mysql.com/doc/.
.SH AUTHOR
MySQL AB (http://www.mysql.com/).
