'\" t
.\"     Title: mysqlrouter_passwd
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 09/12/2024
.\"    Manual: MySQL Router
.\"    Source: MySQL 9.0
.\"  Language: English
.\"
.TH "MYSQLROUTER_PASSWD" "1" "09/12/2024" "MySQL 9\&.0" "MySQL Router"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mysqlrouter_passwd \- MySQL Router Password Tool
.SH "SYNOPSIS"
.HP \w'\fBmysqlrouter_passwd\ [\fR\fB\fIoptions\fR\fR\fB]\fR\ 'u
\fBmysqlrouter_passwd [\fR\fB\fIoptions\fR\fR\fB]\fR
.SH "DESCRIPTION"
.PP
The
\fBmysqlrouter_passwd\fR
utility is a command line application to manage the accounts in the passwd file\&. For example usage, see
Section\ \&6.1, \(lqA Simple MySQL Router REST API Guide\(rq\&.
.PP
Usage information:
.sp
.if n \{\
.RS 4
.\}
.nf
Usage
  bin/mysqlrouter_passwd [opts] <cmd> <filename> [<username>]
  bin/mysqlrouter_passwd \-\-help
  bin/mysqlrouter_passwd \-\-version
Commands
  delete
      Delete username (if it exists) from <filename>\&.
  list
      list one or all accounts of <filename>\&.
  set
      add or overwrite account of <username> in <filename>\&.
  verify
      verify if password matches <username>\*(Aqs credentials in <filename>\&.
Options
  \-?, \-\-help
      Display this help and exit\&.
  \-\-kdf <name>
      Key Derivation Function for \*(Aqset\*(Aq\&. One of pbkdf2\-sha256, pbkdf2\-sha512,
      sha256\-crypt, sha512\-crypt\&. default: sha256\-crypt
  \-V, \-\-version
      Display version information and exit\&.
  \-\-work\-factor <num>
      Work\-factor hint for KDF if account is updated\&.
.fi
.if n \{\
.RE
.\}
.SH "COPYRIGHT"
.br
.PP
Copyright \(co 2006, 2024, Oracle and/or its affiliates.
.PP
This documentation is free software; you can redistribute it and/or modify it only under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA or see http://www.gnu.org/licenses/.
.sp
.SH AUTHOR
Oracle Corporation (http://dev.mysql.com/).
