.TH MYSQLADMIN 1 "18 December 2000"
.SH NAME
 mysqladmin [OPTIONS] command command....  \- A utility for performing administrative operations
.SH OPTION SYNOPSIS
.B mysqladmin
.RB [ \-# | \-\-debug=
.IR logfile ]
.RB [ \-f | \-\-force ]
.RB [ \-? | \-\-help ]
.BR [ --character-sets-dir=\fP\fIdirectory\fP ]
.RB [ \-C | \-\-compress ]
.RB [ \-h | \-\-host=[#] ]
.RB [ \-p[pwd] ]
.RI [ \-\-password=[pwd] ]
.RB [ \-P | \-\-port=
.IR pnum ]
.RB [ \-i | \-\-sleep=
.IR sec ]
.RB [ \-E | \-\-vertical ]
.RB [ \-s | \-\-silent ]
.RB [ \-S | \-\-socket=
.IR # ]
.RB [ \-r | \-\-relative ]
.RB [ \-t | \-\-timeout=
.IR # ]
.RB [ \-u | \-\-user=
.IR uname ]
.RB [ \-v | \-\-verbose ]
.RB [ \-V | \-\-version ]
.RB [ \-w | \-\-wait[=retries] ]
.SH OPTION DESCRIPTION
You can get a list of the options your version of 
.IR mysqladmin 
supports by executing 
.BR "mysqladmin \-\-help" 
.SH OPTIONS
.TP
.BR \-# | \-\-debug=\fP\fIlogfile\fP
Output debug log. Often this is 'd:t:o,filename`
.TP
.BR \-f | \-\-force 
Don't ask for confirmation on drop database; with
multiple commands, continue even if an error occurs
.TP
.BR  \-? | \-\-help
 Display help and exit
.TP
.BR  --character-sets-dir=\fP\fIdirectory\fP
Set the character set directory
.TP
.BR  \-C | \-\-compress
Use compression in server/client protocol
.TP
\fB\-h\fP|\fP\-\-host=\fP\fIhostname\fP
Connect to host
.TP
\fB\-p\fP|\fB\-\-password\fP[\fB=\fP\fIpwd\fP]
Password to use when connecting to server
If password is not given it's asked from the tty
.TP
\fB\-P\fR|\fB\-\-port=\fP\fIpnum\fP
Port number to use for connection
.TP  
\fB\-i\fR|\fB\-\-sleep=\fP\fIsec\fP
Execute commands again and again with a sleep between
.TP
.BR \-r | \-\-relative
Show difference between current and previous values
when used with 
.BR -i
. Currently works only with
extended-status
.TP
.BR  \-E | \-\-vertical
Print output vertically. Is similar to 
.BR --relative,
but prints output vertically.
.TP
.BR  \-s | \-\-silent
Silently exit if one can't connect to server
.TP
\fB\-S\fR|\fB\-\-socket=\fP\fIfile\fP
Socket file to use for connection
.TP
\fB\-t\fR|\fB\-\-timeout=\fP\fIsec\fP
Timeout for connection to the mysqld server
.TP
\fB\-u\fP|\fB\-\-user=\fP\fIuname\fP
User for login if not current user
.TP
.BR \-v | \-\-verbose
Write more information
.TP
.BR \-V | \-\-version
Output version information and exit
.TP
.BR \-w | \-\-wait
  Wait and retry if connection is down
.SH COMMAND SYNOPSIS  
.B MySQLADMIN
.RB [ "create \fP\fIdatabasename\fP "]
.RB [ "drop \fP\fIdatabasename\fP" ]
.RB [ extended-status ]
.RB [ flush-hosts ]
.RB [ flush-logs ]
.RB [ flush-tables ]
.RB [ flush-privileges ]
.RB [ " kill id,id,... "  ]
.RB [ "password \fP\fInew-password\fP "]
.RB [ ping ]
.RB [ processlist  ]
.RB [ reload ]
.RB [ refresh ]
.RB [ shutdown ]
.RB [ slave-start ]
.RB [ slave-stop ]
.RB [ status ]
.RB [ variables ]
.RB [ version  ]

.SH COMMANDS
Where command is a one or more of: (Commands may be shortened)
.TP
.BR "create databasename"
Create a new database
.TP
.BR "drop databasename"
Delete a database and all its tables
.TP
.BR  extended-status
Gives an extended status message from the server
.TP
.BR  flush-hosts 
Flush all cached hosts
.TP
.BR flush-logs
Flush all logs
.TP
.BR  flush-status
Clear status variables
.TP
.BR  flush-tables
Flush all tables
.TP
.BR  flush-threads
Flush the thread cache
.TP
.BR  flush-privileges
Reload grant tables (same as reload)
.TP
.BR  "kill id,id,..."
Kill mysql threads
.TP
.BR  "password \fP\fInew-password\fP" 
Change old password to new-password
.TP
.BR  ping
Check if mysqld is alive
.TP
.BR  processlist
Show list of active threads in server
.TP
.BR  reload
Reload grant tables
.TP
.BR  refresh
Flush all tables and close and open logfiles
.TP
.BR  shutdown 
Take server down
.TP
.BR  status
Gives a short status message from the server
.TP
.BR  variables
Prints variables available
.TP
.BR  version
Get version info from server  
.SH "SEE ALSO"
isamchk (1),
isamlog (1),
mysqlaccess (1),
mysqladmin (1),
mysqlbug (1),
mysqld (1),
mysqldump (1),
mysqlshow (1),
msql2mysql (1),
perror (1),
replace (1),
safe_mysqld (1),
which1 (1),
zap (1),
.SH AUTHOR
Ver 1.0, distribution 3.23.29a
Michael (Monty) Widenius (monty@tcx.se),
TCX Datakonsult AB (http://www.tcx.se).
This software comes with no warranty.
Manual page by L. (Kill-9) Pedersen 
(kill-9@kill-9.dk), Mercurmedia Data Model Architect /
system developer (http://www.mercurmedia.com)
.\" end of man page





