'\" t
.\"     Title: mysqlcheck
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 09/13/2024
.\"    Manual: MySQL Database System
.\"    Source: MySQL 9.0
.\"  Language: English
.\"
.TH "MYSQLCHECK" "1" "09/13/2024" "MySQL 9\&.0" "MySQL Database System"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mysqlcheck \- a table maintenance program
.SH "SYNOPSIS"
.HP \w'\fBmysqlcheck\ [\fR\fB\fIoptions\fR\fR\fB]\ [\fR\fB\fIdb_name\fR\fR\fB\ [\fR\fB\fItbl_name\fR\fR\fB\ \&.\&.\&.]]\fR\ 'u
\fBmysqlcheck [\fR\fB\fIoptions\fR\fR\fB] [\fR\fB\fIdb_name\fR\fR\fB [\fR\fB\fItbl_name\fR\fR\fB \&.\&.\&.]]\fR
.SH "DESCRIPTION"
.PP
The
\fBmysqlcheck\fR
client performs table maintenance: It checks, repairs, optimizes, or analyzes tables\&.
.PP
Each table is locked and therefore unavailable to other sessions while it is being processed, although for check operations, the table is locked with a
READ
lock only (see
Section\ \&15.3.6, \(lqLOCK TABLES and UNLOCK TABLES Statements\(rq, for more information about
READ
and
WRITE
locks)\&. Table maintenance operations can be time\-consuming, particularly for large tables\&. If you use the
\fB\-\-databases\fR
or
\fB\-\-all\-databases\fR
option to process all tables in one or more databases, an invocation of
\fBmysqlcheck\fR
might take a long time\&. (This is also true for the MySQL upgrade procedure if it determines that table checking is needed because it processes tables the same way\&.)
.PP
\fBmysqlcheck\fR
must be used when the
\fBmysqld\fR
server is running, which means that you do not have to stop the server to perform table maintenance\&.
.PP
\fBmysqlcheck\fR
uses the SQL statements
CHECK TABLE,
REPAIR TABLE,
ANALYZE TABLE, and
OPTIMIZE TABLE
in a convenient way for the user\&. It determines which statements to use for the operation you want to perform, and then sends the statements to the server to be executed\&. For details about which storage engines each statement works with, see the descriptions for those statements in
Section\ \&15.7.3, \(lqTable Maintenance Statements\(rq\&.
.PP
All storage engines do not necessarily support all four maintenance operations\&. In such cases, an error message is displayed\&. For example, if
test\&.t
is an
MEMORY
table, an attempt to check it produces this result:
.sp
.if n \{\
.RS 4
.\}
.nf
$> \fBmysqlcheck test t\fR
test\&.t
note     : The storage engine for the table doesn\*(Aqt support check
.fi
.if n \{\
.RE
.\}
.PP
If
\fBmysqlcheck\fR
is unable to repair a table, see
Section\ \&3.14, \(lqRebuilding or Repairing Tables or Indexes\(rq
for manual table repair strategies\&. This is the case, for example, for
InnoDB
tables, which can be checked with
CHECK TABLE, but not repaired with
REPAIR TABLE\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBCaution\fR
.ps -1
.br
.PP
It is best to make a backup of a table before performing a table repair operation; under some circumstances the operation might cause data loss\&. Possible causes include but are not limited to file system errors\&.
.sp .5v
.RE
.PP
There are three general ways to invoke
\fBmysqlcheck\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
mysqlcheck [\fIoptions\fR] \fIdb_name\fR [\fItbl_name\fR \&.\&.\&.]
mysqlcheck [\fIoptions\fR] \-\-databases \fIdb_name\fR \&.\&.\&.
mysqlcheck [\fIoptions\fR] \-\-all\-databases
.fi
.if n \{\
.RE
.\}
.PP
If you do not name any tables following
\fIdb_name\fR
or if you use the
\fB\-\-databases\fR
or
\fB\-\-all\-databases\fR
option, entire databases are checked\&.
.PP
\fBmysqlcheck\fR
has a special feature compared to other client programs\&. The default behavior of checking tables (\fB\-\-check\fR) can be changed by renaming the binary\&. If you want to have a tool that repairs tables by default, you should just make a copy of
\fBmysqlcheck\fR
named
\fBmysqlrepair\fR, or make a symbolic link to
\fBmysqlcheck\fR
named
\fBmysqlrepair\fR\&. If you invoke
\fBmysqlrepair\fR, it repairs tables\&.
.PP
The names shown in the following table can be used to change
\fBmysqlcheck\fR
default behavior\&.
.TS
allbox tab(:);
lB lB.
T{
Command
T}:T{
Meaning
T}
.T&
l l
l l
l l.
T{
\fBmysqlrepair\fR
T}:T{
The default option is \fB--repair\fR
T}
T{
\fBmysqlanalyze\fR
T}:T{
The default option is \fB--analyze\fR
T}
T{
\fBmysqloptimize\fR
T}:T{
The default option is \fB--optimize\fR
T}
.TE
.sp 1
.PP
\fBmysqlcheck\fR
supports the following options, which can be specified on the command line or in the
[mysqlcheck]
and
[client]
groups of an option file\&. For information about option files used by MySQL programs, see
Section\ \&6.2.2.2, \(lqUsing Option Files\(rq\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-help\fR,
\fB\-?\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--help
T}
.TE
.sp 1
Display a help message and exit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-all\-databases\fR,
\fB\-A\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--all-databases
T}
.TE
.sp 1
Check all tables in all databases\&. This is the same as using the
\fB\-\-databases\fR
option and naming all the databases on the command line, except that the
INFORMATION_SCHEMA
and
performance_schema
databases are not checked\&. They can be checked by explicitly naming them with the
\fB\-\-databases\fR
option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-all\-in\-1\fR,
\fB\-1\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--all-in-1
T}
.TE
.sp 1
Instead of issuing a statement for each table, execute a single statement for each database that names all the tables from that database to be processed\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-analyze\fR,
\fB\-a\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--analyze
T}
.TE
.sp 1
Analyze the tables\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-auto\-repair\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--auto-repair
T}
.TE
.sp 1
If a checked table is corrupted, automatically fix it\&. Any necessary repairs are done after all tables have been checked\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-bind\-address=\fR\fB\fIip_address\fR\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--bind-address=ip_address
T}
.TE
.sp 1
On a computer having multiple network interfaces, use this option to select which interface to use for connecting to the MySQL server\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-character\-sets\-dir=\fR\fB\fIdir_name\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--character-sets-dir=dir_name
T}
T{
Type
T}:T{
Directory name
T}
.TE
.sp 1
The directory where character sets are installed\&. See
Section\ \&12.15, \(lqCharacter Set Configuration\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-check\fR,
\fB\-c\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--check
T}
.TE
.sp 1
Check the tables for errors\&. This is the default operation\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-check\-only\-changed\fR,
\fB\-C\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--check-only-changed
T}
.TE
.sp 1
Check only tables that have changed since the last check or that have not been closed properly\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-check\-upgrade\fR,
\fB\-g\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--check-upgrade
T}
.TE
.sp 1
Invoke
CHECK TABLE
with the
FOR UPGRADE
option to check tables for incompatibilities with the current version of the server\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-compress\fR
.TS
allbox tab(:);
lB l
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--compress[={OFF|ON}]
T}
T{
Deprecated
T}:T{
Yes
T}
T{
Type
T}:T{
Boolean
T}
T{
Default Value
T}:T{
OFF
T}
.TE
.sp 1
Compress all information sent between the client and the server if possible\&. See
Section\ \&6.2.8, \(lqConnection Compression Control\(rq\&.
.sp
This option is deprecated\&. Expect it to be removed in a future version of MySQL\&. See
the section called \(lqConfiguring Legacy Connection Compression\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-compression\-algorithms=\fR\fB\fIvalue\fR\fR
.TS
allbox tab(:);
lB l
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--compression-algorithms=value
T}
T{
Type
T}:T{
Set
T}
T{
Default Value
T}:T{
uncompressed
T}
T{
Valid Values
T}:T{
.PP
zlib
.PP
zstd
.PP
uncompressed
T}
.TE
.sp 1
The permitted compression algorithms for connections to the server\&. The available algorithms are the same as for the
protocol_compression_algorithms
system variable\&. The default value is
uncompressed\&.
.sp
For more information, see
Section\ \&6.2.8, \(lqConnection Compression Control\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-databases\fR,
\fB\-B\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--databases
T}
.TE
.sp 1
Process all tables in the named databases\&. Normally,
\fBmysqlcheck\fR
treats the first name argument on the command line as a database name and any following names as table names\&. With this option, it treats all name arguments as database names\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-debug[=\fR\fB\fIdebug_options\fR\fR\fB]\fR,
\fB\-# [\fR\fB\fIdebug_options\fR\fR\fB]\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--debug[=debug_options]
T}
T{
Type
T}:T{
String
T}
T{
Default Value
T}:T{
d:t:o
T}
.TE
.sp 1
Write a debugging log\&. A typical
\fIdebug_options\fR
string is
d:t:o,\fIfile_name\fR\&. The default is
d:t:o\&.
.sp
This option is available only if MySQL was built using
\fBWITH_DEBUG\fR\&. MySQL release binaries provided by Oracle are
\fInot\fR
built using this option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-debug\-check\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--debug-check
T}
T{
Type
T}:T{
Boolean
T}
T{
Default Value
T}:T{
FALSE
T}
.TE
.sp 1
Print some debugging information when the program exits\&.
.sp
This option is available only if MySQL was built using
\fBWITH_DEBUG\fR\&. MySQL release binaries provided by Oracle are
\fInot\fR
built using this option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-debug\-info\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--debug-info
T}
T{
Type
T}:T{
Boolean
T}
T{
Default Value
T}:T{
FALSE
T}
.TE
.sp 1
Print debugging information and memory and CPU usage statistics when the program exits\&.
.sp
This option is available only if MySQL was built using
\fBWITH_DEBUG\fR\&. MySQL release binaries provided by Oracle are
\fInot\fR
built using this option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-default\-character\-set=\fR\fB\fIcharset_name\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--default-character-set=charset_name
T}
T{
Type
T}:T{
String
T}
.TE
.sp 1
Use
\fIcharset_name\fR
as the default character set\&. See
Section\ \&12.15, \(lqCharacter Set Configuration\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-defaults\-extra\-file=\fR\fB\fIfile_name\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--defaults-extra-file=file_name
T}
T{
Type
T}:T{
File name
T}
.TE
.sp 1
Read this option file after the global option file but (on Unix) before the user option file\&. If the file does not exist or is otherwise inaccessible, an error occurs\&. If
\fIfile_name\fR
is not an absolute path name, it is interpreted relative to the current directory\&.
.sp
For additional information about this and other option\-file options, see
Section\ \&6.2.2.3, \(lqCommand-Line Options that Affect Option-File Handling\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-defaults\-file=\fR\fB\fIfile_name\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--defaults-file=file_name
T}
T{
Type
T}:T{
File name
T}
.TE
.sp 1
Use only the given option file\&. If the file does not exist or is otherwise inaccessible, an error occurs\&. If
\fIfile_name\fR
is not an absolute path name, it is interpreted relative to the current directory\&.
.sp
Exception: Even with
\fB\-\-defaults\-file\fR, client programs read
\&.mylogin\&.cnf\&.
.sp
For additional information about this and other option\-file options, see
Section\ \&6.2.2.3, \(lqCommand-Line Options that Affect Option-File Handling\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-defaults\-group\-suffix=\fR\fB\fIstr\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--defaults-group-suffix=str
T}
T{
Type
T}:T{
String
T}
.TE
.sp 1
Read not only the usual option groups, but also groups with the usual names and a suffix of
\fIstr\fR\&. For example,
\fBmysqlcheck\fR
normally reads the
[client]
and
[mysqlcheck]
groups\&. If this option is given as
\fB\-\-defaults\-group\-suffix=_other\fR,
\fBmysqlcheck\fR
also reads the
[client_other]
and
[mysqlcheck_other]
groups\&.
.sp
For additional information about this and other option\-file options, see
Section\ \&6.2.2.3, \(lqCommand-Line Options that Affect Option-File Handling\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-extended\fR,
\fB\-e\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--extended
T}
.TE
.sp 1
If you are using this option to check tables, it ensures that they are 100% consistent but takes a long time\&.
.sp
If you are using this option to repair tables, it runs an extended repair that may not only take a long time to execute, but may produce a lot of garbage rows also!
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-default\-auth=\fR\fB\fIplugin\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--default-auth=plugin
T}
T{
Type
T}:T{
String
T}
.TE
.sp 1
A hint about which client\-side authentication plugin to use\&. See
Section\ \&8.2.17, \(lqPluggable Authentication\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-enable\-cleartext\-plugin\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--enable-cleartext-plugin
T}
T{
Type
T}:T{
Boolean
T}
T{
Default Value
T}:T{
FALSE
T}
.TE
.sp 1
Enable the
mysql_clear_password
cleartext authentication plugin\&. (See
Section\ \&8.4.1.3, \(lqClient-Side Cleartext Pluggable Authentication\(rq\&.)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-fast\fR,
\fB\-F\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--fast
T}
.TE
.sp 1
Check only tables that have not been closed properly\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-force\fR,
\fB\-f\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--force
T}
.TE
.sp 1
Continue even if an SQL error occurs\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-get\-server\-public\-key\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--get-server-public-key
T}
T{
Type
T}:T{
Boolean
T}
.TE
.sp 1
Request from the server the public key required for RSA key pair\-based password exchange\&. This option applies to clients that authenticate with the
caching_sha2_password
authentication plugin\&. For that plugin, the server does not send the public key unless requested\&. This option is ignored for accounts that do not authenticate with that plugin\&. It is also ignored if RSA\-based password exchange is not used, as is the case when the client connects to the server using a secure connection\&.
.sp
If
\fB\-\-server\-public\-key\-path=\fR\fB\fIfile_name\fR\fR
is given and specifies a valid public key file, it takes precedence over
\fB\-\-get\-server\-public\-key\fR\&.
.sp
For information about the
caching_sha2_password
plugin, see
Section\ \&8.4.1.1, \(lqCaching SHA-2 Pluggable Authentication\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-host=\fR\fB\fIhost_name\fR\fR,
\fB\-h \fR\fB\fIhost_name\fR\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--host=host_name
T}
T{
Type
T}:T{
String
T}
T{
Default Value
T}:T{
localhost
T}
.TE
.sp 1
Connect to the MySQL server on the given host\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-login\-path=\fR\fB\fIname\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--login-path=name
T}
T{
Type
T}:T{
String
T}
.TE
.sp 1
Read options from the named login path in the
\&.mylogin\&.cnf
login path file\&. A
\(lqlogin path\(rq
is an option group containing options that specify which MySQL server to connect to and which account to authenticate as\&. To create or modify a login path file, use the
\fBmysql_config_editor\fR
utility\&. See
mysql_config_editor(1)\&.
.sp
For additional information about this and other option\-file options, see
Section\ \&6.2.2.3, \(lqCommand-Line Options that Affect Option-File Handling\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-no\-login\-paths\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--no-login-paths
T}
.TE
.sp 1
Skips reading options from the login path file\&.
.sp
See
\fB\-\-login\-path\fR
for related information\&.
.sp
For additional information about this and other option\-file options, see
Section\ \&6.2.2.3, \(lqCommand-Line Options that Affect Option-File Handling\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-medium\-check\fR,
\fB\-m\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--medium-check
T}
.TE
.sp 1
Do a check that is faster than an
\fB\-\-extended\fR
operation\&. This finds only 99\&.99% of all errors, which should be good enough in most cases\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-no\-defaults\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--no-defaults
T}
.TE
.sp 1
Do not read any option files\&. If program startup fails due to reading unknown options from an option file,
\fB\-\-no\-defaults\fR
can be used to prevent them from being read\&.
.sp
The exception is that the
\&.mylogin\&.cnf
file is read in all cases, if it exists\&. This permits passwords to be specified in a safer way than on the command line even when
\fB\-\-no\-defaults\fR
is used\&. To create
\&.mylogin\&.cnf, use the
\fBmysql_config_editor\fR
utility\&. See
mysql_config_editor(1)\&.
.sp
For additional information about this and other option\-file options, see
Section\ \&6.2.2.3, \(lqCommand-Line Options that Affect Option-File Handling\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-optimize\fR,
\fB\-o\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--optimize
T}
.TE
.sp 1
Optimize the tables\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-password[=\fR\fB\fIpassword\fR\fR\fB]\fR,
\fB\-p[\fR\fB\fIpassword\fR\fR\fB]\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--password[=password]
T}
T{
Type
T}:T{
String
T}
.TE
.sp 1
The password of the MySQL account used for connecting to the server\&. The password value is optional\&. If not given,
\fBmysqlcheck\fR
prompts for one\&. If given, there must be
\fIno space\fR
between
\fB\-\-password=\fR
or
\fB\-p\fR
and the password following it\&. If no password option is specified, the default is to send no password\&.
.sp
Specifying a password on the command line should be considered insecure\&. To avoid giving the password on the command line, use an option file\&. See
Section\ \&8.1.2.1, \(lqEnd-User Guidelines for Password Security\(rq\&.
.sp
To explicitly specify that there is no password and that
\fBmysqlcheck\fR
should not prompt for one, use the
\fB\-\-skip\-password\fR
option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-password1[=\fR\fB\fIpass_val\fR\fR\fB]\fR
The password for multifactor authentication factor 1 of the MySQL account used for connecting to the server\&. The password value is optional\&. If not given,
\fBmysqlcheck\fR
prompts for one\&. If given, there must be
\fIno space\fR
between
\fB\-\-password1=\fR
and the password following it\&. If no password option is specified, the default is to send no password\&.
.sp
Specifying a password on the command line should be considered insecure\&. To avoid giving the password on the command line, use an option file\&. See
Section\ \&8.1.2.1, \(lqEnd-User Guidelines for Password Security\(rq\&.
.sp
To explicitly specify that there is no password and that
\fBmysqlcheck\fR
should not prompt for one, use the
\fB\-\-skip\-password1\fR
option\&.
.sp
\fB\-\-password1\fR
and
\fB\-\-password\fR
are synonymous, as are
\fB\-\-skip\-password1\fR
and
\fB\-\-skip\-password\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-password2[=\fR\fB\fIpass_val\fR\fR\fB]\fR
The password for multifactor authentication factor 2 of the MySQL account used for connecting to the server\&. The semantics of this option are similar to the semantics for
\fB\-\-password1\fR; see the description of that option for details\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-password3[=\fR\fB\fIpass_val\fR\fR\fB]\fR
The password for multifactor authentication factor 3 of the MySQL account used for connecting to the server\&. The semantics of this option are similar to the semantics for
\fB\-\-password1\fR; see the description of that option for details\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-pipe\fR,
\fB\-W\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--pipe
T}
T{
Type
T}:T{
String
T}
.TE
.sp 1
On Windows, connect to the server using a named pipe\&. This option applies only if the server was started with the
named_pipe
system variable enabled to support named\-pipe connections\&. In addition, the user making the connection must be a member of the Windows group specified by the
named_pipe_full_access_group
system variable\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-plugin\-dir=\fR\fB\fIdir_name\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--plugin-dir=dir_name
T}
T{
Type
T}:T{
Directory name
T}
.TE
.sp 1
The directory in which to look for plugins\&. Specify this option if the
\fB\-\-default\-auth\fR
option is used to specify an authentication plugin but
\fBmysqlcheck\fR
does not find it\&. See
Section\ \&8.2.17, \(lqPluggable Authentication\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-port=\fR\fB\fIport_num\fR\fR,
\fB\-P \fR\fB\fIport_num\fR\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--port=port_num
T}
T{
Type
T}:T{
Numeric
T}
T{
Default Value
T}:T{
3306
T}
.TE
.sp 1
For TCP/IP connections, the port number to use\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-print\-defaults\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--print-defaults
T}
.TE
.sp 1
Print the program name and all options that it gets from option files\&.
.sp
For additional information about this and other option\-file options, see
Section\ \&6.2.2.3, \(lqCommand-Line Options that Affect Option-File Handling\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-protocol={TCP|SOCKET|PIPE|MEMORY}\fR
.TS
allbox tab(:);
lB l
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--protocol=type
T}
T{
Type
T}:T{
String
T}
T{
Default Value
T}:T{
[see text]
T}
T{
Valid Values
T}:T{
.PP
TCP
.PP
SOCKET
.PP
PIPE
.PP
MEMORY
T}
.TE
.sp 1
The transport protocol to use for connecting to the server\&. It is useful when the other connection parameters normally result in use of a protocol other than the one you want\&. For details on the permissible values, see
Section\ \&6.2.7, \(lqConnection Transport Protocols\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-quick\fR,
\fB\-q\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--quick
T}
.TE
.sp 1
If you are using this option to check tables, it prevents the check from scanning the rows to check for incorrect links\&. This is the fastest check method\&.
.sp
If you are using this option to repair tables, it tries to repair only the index tree\&. This is the fastest repair method\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-repair\fR,
\fB\-r\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--repair
T}
.TE
.sp 1
Perform a repair that can fix almost anything except unique keys that are not unique\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-server\-public\-key\-path=\fR\fB\fIfile_name\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--server-public-key-path=file_name
T}
T{
Type
T}:T{
File name
T}
.TE
.sp 1
The path name to a file in PEM format containing a client\-side copy of the public key required by the server for RSA key pair\-based password exchange\&. This option applies to clients that authenticate with the
sha256_password
or
caching_sha2_password
authentication plugin\&. This option is ignored for accounts that do not authenticate with one of those plugins\&. It is also ignored if RSA\-based password exchange is not used, as is the case when the client connects to the server using a secure connection\&.
.sp
If
\fB\-\-server\-public\-key\-path=\fR\fB\fIfile_name\fR\fR
is given and specifies a valid public key file, it takes precedence over
\fB\-\-get\-server\-public\-key\fR\&.
.sp
For
sha256_password, this option applies only if MySQL was built using OpenSSL\&.
.sp
For information about the
sha256_password
and
caching_sha2_password
plugins, see
Section\ \&8.4.1.2, \(lqSHA-256 Pluggable Authentication\(rq, and
Section\ \&8.4.1.1, \(lqCaching SHA-2 Pluggable Authentication\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-shared\-memory\-base\-name=\fR\fB\fIname\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--shared-memory-base-name=name
T}
T{
Platform Specific
T}:T{
Windows
T}
.TE
.sp 1
On Windows, the shared\-memory name to use for connections made using shared memory to a local server\&. The default value is
MYSQL\&. The shared\-memory name is case\-sensitive\&.
.sp
This option applies only if the server was started with the
shared_memory
system variable enabled to support shared\-memory connections\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-silent\fR,
\fB\-s\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--silent
T}
.TE
.sp 1
Silent mode\&. Print only error messages\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-skip\-database=\fR\fB\fIdb_name\fR\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--skip-database=db_name
T}
.TE
.sp 1
Do not include the named database (case\-sensitive) in the operations performed by
\fBmysqlcheck\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-socket=\fR\fB\fIpath\fR\fR,
\fB\-S \fR\fB\fIpath\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--socket={file_name|pipe_name}
T}
T{
Type
T}:T{
String
T}
.TE
.sp 1
For connections to
localhost, the Unix socket file to use, or, on Windows, the name of the named pipe to use\&.
.sp
On Windows, this option applies only if the server was started with the
named_pipe
system variable enabled to support named\-pipe connections\&. In addition, the user making the connection must be a member of the Windows group specified by the
named_pipe_full_access_group
system variable\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-ssl*\fR
Options that begin with
\fB\-\-ssl\fR
specify whether to connect to the server using encryption and indicate where to find SSL keys and certificates\&. See
the section called \(lqCommand Options for Encrypted Connections\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-ssl\-fips\-mode={OFF|ON|STRICT}\fR
.TS
allbox tab(:);
lB l
lB l
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--ssl-fips-mode={OFF|ON|STRICT}
T}
T{
Deprecated
T}:T{
Yes
T}
T{
Type
T}:T{
Enumeration
T}
T{
Default Value
T}:T{
OFF
T}
T{
Valid Values
T}:T{
.PP
OFF
.PP
ON
.PP
STRICT
T}
.TE
.sp 1
Controls whether to enable FIPS mode on the client side\&. The
\fB\-\-ssl\-fips\-mode\fR
option differs from other
\fB\-\-ssl\-\fR\fB\fIxxx\fR\fR
options in that it is not used to establish encrypted connections, but rather to affect which cryptographic operations to permit\&. See
Section\ \&8.8, \(lqFIPS Support\(rq\&.
.sp
These
\fB\-\-ssl\-fips\-mode\fR
values are permitted:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
OFF: Disable FIPS mode\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ON: Enable FIPS mode\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
STRICT: Enable
\(lqstrict\(rq
FIPS mode\&.
.RE
.sp
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
If the OpenSSL FIPS Object Module is not available, the only permitted value for
\fB\-\-ssl\-fips\-mode\fR
is
OFF\&. In this case, setting
\fB\-\-ssl\-fips\-mode\fR
to
ON
or
STRICT
causes the client to produce a warning at startup and to operate in non\-FIPS mode\&.
.sp .5v
.RE
This option is deprecated\&. Expect it to be removed in a future version of MySQL\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-tables\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--tables
T}
.TE
.sp 1
Override the
\fB\-\-databases\fR
or
\fB\-B\fR
option\&. All name arguments following the option are regarded as table names\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-tls\-ciphersuites=\fR\fB\fIciphersuite_list\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--tls-ciphersuites=ciphersuite_list
T}
T{
Type
T}:T{
String
T}
.TE
.sp 1
The permissible ciphersuites for encrypted connections that use TLSv1\&.3\&. The value is a list of one or more colon\-separated ciphersuite names\&. The ciphersuites that can be named for this option depend on the SSL library used to compile MySQL\&. For details, see
Section\ \&8.3.2, \(lqEncrypted Connection TLS Protocols and Ciphers\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-tls\-sni\-servername=\fR\fB\fIserver_name\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--tls-sni-servername=server_name
T}
T{
Type
T}:T{
String
T}
.TE
.sp 1
When specified, the name is passed to the
libmysqlclient
C API library using the
MYSQL_OPT_TLS_SNI_SERVERNAME
option of
mysql_options()\&. The server name is not case\-sensitive\&. To show which server name the client specified for the current session, if any, check the
Tls_sni_server_name
status variable\&.
.sp
Server Name Indication (SNI) is an extension to the TLS protocol (OpenSSL must be compiled using TLS extensions for this option to function)\&. The MySQL implementation of SNI represents the client\-side only\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-tls\-version=\fR\fB\fIprotocol_list\fR\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--tls-version=protocol_list
T}
T{
Type
T}:T{
String
T}
T{
Default Value
T}:T{
.PP
TLSv1,TLSv1.1,TLSv1.2,TLSv1.3
(OpenSSL 1.1.1 or higher)
.PP
TLSv1,TLSv1.1,TLSv1.2
(otherwise)
T}
.TE
.sp 1
The permissible TLS protocols for encrypted connections\&. The value is a list of one or more comma\-separated protocol names\&. The protocols that can be named for this option depend on the SSL library used to compile MySQL\&. For details, see
Section\ \&8.3.2, \(lqEncrypted Connection TLS Protocols and Ciphers\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-use\-frm\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--use-frm
T}
.TE
.sp 1
For repair operations on
MyISAM
tables, get the table structure from the data dictionary so that the table can be repaired even if the
\&.MYI
header is corrupted\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-user=\fR\fB\fIuser_name\fR\fR,
\fB\-u \fR\fB\fIuser_name\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--user=user_name,
T}
T{
Type
T}:T{
String
T}
.TE
.sp 1
The user name of the MySQL account to use for connecting to the server\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-verbose\fR,
\fB\-v\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--verbose
T}
.TE
.sp 1
Verbose mode\&. Print information about the various stages of program operation\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-version\fR,
\fB\-V\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--version
T}
.TE
.sp 1
Display version information and exit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-write\-binlog\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--write-binlog
T}
.TE
.sp 1
This option is enabled by default, so that
ANALYZE TABLE,
OPTIMIZE TABLE, and
REPAIR TABLE
statements generated by
\fBmysqlcheck\fR
are written to the binary log\&. Use
\fB\-\-skip\-write\-binlog\fR
to cause
NO_WRITE_TO_BINLOG
to be added to the statements so that they are not logged\&. Use the
\fB\-\-skip\-write\-binlog\fR
when these statements should not be sent to replicas or run when using the binary logs for recovery from backup\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-zstd\-compression\-level=\fR\fB\fIlevel\fR\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--zstd-compression-level=#
T}
T{
Type
T}:T{
Integer
T}
.TE
.sp 1
The compression level to use for connections to the server that use the
zstd
compression algorithm\&. The permitted levels are from 1 to 22, with larger values indicating increasing levels of compression\&. The default
zstd
compression level is 3\&. The compression level setting has no effect on connections that do not use
zstd
compression\&.
.sp
For more information, see
Section\ \&6.2.8, \(lqConnection Compression Control\(rq\&.
.RE
.SH "COPYRIGHT"
.br
.PP
Copyright \(co 1997, 2024, Oracle and/or its affiliates.
.PP
This documentation is free software; you can redistribute it and/or modify it only under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA or see http://www.gnu.org/licenses/.
.sp
.SH "SEE ALSO"
For more information, please refer to the MySQL Reference Manual,
which may already be installed locally and which is also available
online at http://dev.mysql.com/doc/.
.SH AUTHOR
Oracle Corporation (http://dev.mysql.com/).
