'\" t
.\"     Title: ndb_index_stat
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 11/26/2022
.\"    Manual: MySQL Database System
.\"    Source: MySQL 8.0
.\"  Language: English
.\"
.TH "NDB_INDEX_STAT" "1" "11/26/2022" "MySQL 8\&.0" "MySQL Database System"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ndb_index_stat \- NDB index statistics utility
.SH "SYNOPSIS"
.HP \w'\fBndb_index_stat\ \fR\fB\fIoptions\fR\fR\ 'u
\fBndb_index_stat \fR\fB\fIoptions\fR\fR
.SH "DESCRIPTION"
.PP
\fBndb_index_stat\fR
provides per\-fragment statistical information about indexes on
NDB
tables\&. This includes cache version and age, number of index entries per partition, and memory consumption by indexes\&.
Usage
.PP
To obtain basic index statistics about a given
NDB
table, invoke
\fBndb_index_stat\fR
as shown here, with the name of the table as the first argument and the name of the database containing this table specified immediately following it, using the
\fB\-\-database\fR
(\fB\-d\fR) option:
.sp
.if n \{\
.RS 4
.\}
.nf
ndb_index_stat \fItable\fR \-d \fIdatabase\fR
.fi
.if n \{\
.RE
.\}
.PP
In this example, we use
\fBndb_index_stat\fR
to obtain such information about an
NDB
table named
mytable
in the
test
database:
.sp
.if n \{\
.RS 4
.\}
.nf
$> \fBndb_index_stat \-d test mytable\fR
table:City index:PRIMARY fragCount:2
sampleVersion:3 loadTime:1399585986 sampleCount:1994 keyBytes:7976
query cache: valid:1 sampleCount:1994 totalBytes:27916
times in ms: save: 7\&.133 sort: 1\&.974 sort per sample: 0\&.000
NDBT_ProgramExit: 0 \- OK
.fi
.if n \{\
.RE
.\}
.PP
sampleVersion
is the version number of the cache from which the statistics data is taken\&. Running
\fBndb_index_stat\fR
with the
\fB\-\-update\fR
option causes sampleVersion to be incremented\&.
.PP
loadTime
shows when the cache was last updated\&. This is expressed as seconds since the Unix Epoch\&.
.PP
sampleCount
is the number of index entries found per partition\&. You can estimate the total number of entries by multiplying this by the number of fragments (shown as
fragCount)\&.
.PP
sampleCount
can be compared with the cardinality of
SHOW INDEX
or
INFORMATION_SCHEMA\&.STATISTICS, although the latter two provide a view of the table as a whole, while
\fBndb_index_stat\fR
provides a per\-fragment average\&.
.PP
keyBytes
is the number of bytes used by the index\&. In this example, the primary key is an integer, which requires four bytes for each index, so
keyBytes
can be calculated in this case as shown here:
.sp
.if n \{\
.RS 4
.\}
.nf
    keyBytes = sampleCount * (4 bytes per index) = 1994 * 4 = 7976
.fi
.if n \{\
.RE
.\}
.PP
This information can also be obtained using the corresponding column definitions from
INFORMATION_SCHEMA\&.COLUMNS
(this requires a MySQL Server and a MySQL client application)\&.
.PP
totalBytes
is the total memory consumed by all indexes on the table, in bytes\&.
.PP
Timings shown in the preceding examples are specific to each invocation of
\fBndb_index_stat\fR\&.
.PP
The
\fB\-\-verbose\fR
option provides some additional output, as shown here:
.sp
.if n \{\
.RS 4
.\}
.nf
$> \fBndb_index_stat \-d test mytable \-\-verbose\fR
random seed 1337010518
connected
loop 1 of 1
table:mytable index:PRIMARY fragCount:4
sampleVersion:2 loadTime:1336751773 sampleCount:0 keyBytes:0
read stats
query cache created
query cache: valid:1 sampleCount:0 totalBytes:0
times in ms: save: 20\&.766 sort: 0\&.001
disconnected
NDBT_ProgramExit: 0 \- OK
$>
.fi
.if n \{\
.RE
.\}
.PP
If the only output from the program is
NDBT_ProgramExit: 0 \- OK, this may indicate that no statistics yet exist\&. To force them to be created (or updated if they already exist), invoke
\fBndb_index_stat\fR
with the
\fB\-\-update\fR
option, or execute
ANALYZE TABLE
on the table in the
\fBmysql\fR
client\&.
Options
.PP
The following table includes options that are specific to the NDB Cluster
\fBndb_index_stat\fR
utility\&. Additional descriptions are listed following the table\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&23.36.\ \&Command\-line options used with the program ndb_index_stat
.TS
allbox tab(:);
lB lB lB.
T{
Format
T}:T{
Description
T}:T{
Added, Deprecated, or Removed
T}
.T&
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l
lB l l.
T{
.PP
\fB \fR\fB--character-sets-dir=path\fR\fB \fR
T}:T{
Directory containing character sets
T}:T{
.PP
REMOVED: 8.0.31
T}
T{
.PP
\fB \fR\fB--connect-retries=#\fR\fB \fR
T}:T{
Number of times to retry connection before giving up
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--connect-retry-delay=#\fR\fB \fR
T}:T{
Number of seconds to wait between attempts to contact management server
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB--connect-string=connection_string\fR,
.PP
\fB \fR\fB-c connection_string\fR\fB \fR
T}:T{
Same as --ndb-connectstring
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--core-file\fR\fB \fR
T}:T{
Write core file on error; used in debugging
T}:T{
.PP
REMOVED: 8.0.31
T}
T{
.PP
\fB--database=name\fR,
.PP
\fB \fR\fB-d name\fR\fB \fR
T}:T{
Name of database containing table
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--defaults-extra-file=path\fR\fB \fR
T}:T{
Read given file after global files are read
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--defaults-file=path\fR\fB \fR
T}:T{
Read default options from given file only
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--defaults-group-suffix=string\fR\fB \fR
T}:T{
Also read groups with concat(group, suffix)
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--delete\fR\fB \fR
T}:T{
Delete index statistics for table, stopping any auto-update previously
              configured
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--dump\fR\fB \fR
T}:T{
Print query cache
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB--help\fR,
.PP
\fB \fR\fB-?\fR\fB \fR
T}:T{
Display help text and exit
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--login-path=path\fR\fB \fR
T}:T{
Read given path from login file
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--loops=#\fR\fB \fR
T}:T{
Set the number of times to perform given command; default is 0
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB--ndb-connectstring=connection_string\fR,
.PP
\fB \fR\fB-c connection_string\fR\fB \fR
T}:T{
Set connect string for connecting to ndb_mgmd. Syntax:
              "[nodeid=id;][host=]hostname[:port]". Overrides entries in
              NDB_CONNECTSTRING and my.cnf
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB--ndb-mgmd-host=connection_string\fR,
.PP
\fB \fR\fB-c connection_string\fR\fB \fR
T}:T{
Same as --ndb-connectstring
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--ndb-nodeid=#\fR\fB \fR
T}:T{
Set node ID for this node, overriding any ID set by --ndb-connectstring
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--ndb-optimized-node-selection\fR\fB \fR
T}:T{
Enable optimizations for selection of nodes for transactions. Enabled by
              default; use --skip-ndb-optimized-node-selection to
              disable
T}:T{
.PP
REMOVED: 8.0.31
T}
T{
.PP
\fB \fR\fB--no-defaults\fR\fB \fR
T}:T{
Do not read default options from any option file other than login file
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--print-defaults\fR\fB \fR
T}:T{
Print program argument list and exit
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--query=#\fR\fB \fR
T}:T{
Perform random range queries on first key attr (must be int unsigned)
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--sys-drop\fR\fB \fR
T}:T{
Drop any statistics tables and events in NDB kernel (all statistics are
              lost)
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--sys-create\fR\fB \fR
T}:T{
Create all statistics tables and events in NDB kernel, if none of them
              already exist
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--sys-create-if-not-exist\fR\fB \fR
T}:T{
Create any statistics tables and events in NDB kernel that do not
              already exist
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--sys-create-if-not-valid\fR\fB \fR
T}:T{
Create any statistics tables or events that do not already exist in the
              NDB kernel, after dropping any that are invalid
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--sys-check\fR\fB \fR
T}:T{
Verify that NDB system index statistics and event tables exist
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--sys-skip-tables\fR\fB \fR
T}:T{
Do not apply sys-* options to tables
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--sys-skip-events\fR\fB \fR
T}:T{
Do not apply sys-* options to events
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB \fR\fB--update\fR\fB \fR
T}:T{
Update index statistics for table, restarting any auto-update previously
              configured
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB--usage\fR,
.PP
\fB \fR\fB-?\fR\fB \fR
T}:T{
Display help text and exit; same as --help
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB--verbose\fR,
.PP
\fB \fR\fB-v\fR\fB \fR
T}:T{
Turn on verbose output
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
T{
.PP
\fB--version\fR,
.PP
\fB \fR\fB-V\fR\fB \fR
T}:T{
Display version information and exit
T}:T{
.PP
(Supported in all NDB releases based on MySQL 8.0)
T}
.TE
.sp 1
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-character\-sets\-dir\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--character-sets-dir=path
T}
T{
Removed
T}:T{
8.0.31
T}
.TE
.sp 1
Directory containing character sets\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-connect\-retries\fR
.TS
allbox tab(:);
lB l
lB l
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--connect-retries=#
T}
T{
Type
T}:T{
Integer
T}
T{
Default Value
T}:T{
12
T}
T{
Minimum Value
T}:T{
0
T}
T{
Maximum Value
T}:T{
12
T}
.TE
.sp 1
Number of times to retry connection before giving up\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-connect\-retry\-delay\fR
.TS
allbox tab(:);
lB l
lB l
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--connect-retry-delay=#
T}
T{
Type
T}:T{
Integer
T}
T{
Default Value
T}:T{
5
T}
T{
Minimum Value
T}:T{
0
T}
T{
Maximum Value
T}:T{
5
T}
.TE
.sp 1
Number of seconds to wait between attempts to contact management server\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-connect\-string\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--connect-string=connection_string
T}
T{
Type
T}:T{
String
T}
T{
Default Value
T}:T{
[none]
T}
.TE
.sp 1
Same as
\fB\-\-ndb\-connectstring\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-core\-file\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--core-file
T}
T{
Removed
T}:T{
8.0.31
T}
.TE
.sp 1
Write core file on error; used in debugging\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-database=\fR\fB\fIname\fR\fR,
\fB\-d \fR\fB\fIname\fR\fR
.TS
allbox tab(:);
lB l
lB l
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--database=name
T}
T{
Type
T}:T{
String
T}
T{
Default Value
T}:T{
[none]
T}
T{
Minimum Value
T}:T{
T}
T{
Maximum Value
T}:T{
T}
.TE
.sp 1
The name of the database that contains the table being queried\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-defaults\-extra\-file\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--defaults-extra-file=path
T}
T{
Type
T}:T{
String
T}
T{
Default Value
T}:T{
[none]
T}
.TE
.sp 1
Read given file after global files are read\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-defaults\-file\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--defaults-file=path
T}
T{
Type
T}:T{
String
T}
T{
Default Value
T}:T{
[none]
T}
.TE
.sp 1
Read default options from given file only\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-defaults\-group\-suffix\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--defaults-group-suffix=string
T}
T{
Type
T}:T{
String
T}
T{
Default Value
T}:T{
[none]
T}
.TE
.sp 1
Also read groups with concat(group, suffix)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-delete\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--delete
T}
.TE
.sp 1
Delete the index statistics for the given table, stopping any auto\-update that was previously configured\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-dump\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--dump
T}
.TE
.sp 1
Dump the contents of the query cache\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-help\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--help
T}
.TE
.sp 1
Display help text and exit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-login\-path\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--login-path=path
T}
T{
Type
T}:T{
String
T}
T{
Default Value
T}:T{
[none]
T}
.TE
.sp 1
Read given path from login file\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-loops=\fR\fB\fI#\fR\fR
.TS
allbox tab(:);
lB l
lB l
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--loops=#
T}
T{
Type
T}:T{
Numeric
T}
T{
Default Value
T}:T{
0
T}
T{
Minimum Value
T}:T{
0
T}
T{
Maximum Value
T}:T{
MAX_INT
T}
.TE
.sp 1
Repeat commands this number of times (for use in testing)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-ndb\-connectstring\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--ndb-connectstring=connection_string
T}
T{
Type
T}:T{
String
T}
T{
Default Value
T}:T{
[none]
T}
.TE
.sp 1
Set connect string for connecting to ndb_mgmd\&. Syntax: "[nodeid=id;][host=]hostname[:port]"\&. Overrides entries in NDB_CONNECTSTRING and my\&.cnf\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-ndb\-mgmd\-host\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--ndb-mgmd-host=connection_string
T}
T{
Type
T}:T{
String
T}
T{
Default Value
T}:T{
[none]
T}
.TE
.sp 1
Same as
\fB\-\-ndb\-connectstring\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-ndb\-nodeid\fR
.TS
allbox tab(:);
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--ndb-nodeid=#
T}
T{
Type
T}:T{
Integer
T}
T{
Default Value
T}:T{
[none]
T}
.TE
.sp 1
Set node ID for this node, overriding any ID set by
\fB\-\-ndb\-connectstring\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-ndb\-optimized\-node\-selection\fR
.TS
allbox tab(:);
lB l
lB l.
T{
Command-Line Format
T}:T{
--ndb-optimized-node-selection
T}
T{
Removed
T}:T{
8.0.31
T}
.TE
.sp 1
Enable optimizations for selection of nodes for transactions\&. Enabled by default; use
\fB\-\-skip\-ndb\-optimized\-node\-selection\fR
to disable\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-no\-defaults\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--no-defaults
T}
.TE
.sp 1
Do not read default options from any option file other than login file\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-print\-defaults\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--print-defaults
T}
.TE
.sp 1
Print program argument list and exit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-query=\fR\fB\fI#\fR\fR
.TS
allbox tab(:);
lB l
lB l
lB l
lB l
lB l.
T{
Command-Line Format
T}:T{
--query=#
T}
T{
Type
T}:T{
Numeric
T}
T{
Default Value
T}:T{
0
T}
T{
Minimum Value
T}:T{
0
T}
T{
Maximum Value
T}:T{
MAX_INT
T}
.TE
.sp 1
Perform random range queries on first key attribute (must be int unsigned)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-drop\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--sys-drop
T}
.TE
.sp 1
Drop all statistics tables and events in the NDB kernel\&.
\fIThis causes all statistics to be lost\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-create\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--sys-create
T}
.TE
.sp 1
Create all statistics tables and events in the NDB kernel\&. This works only if none of them exist previously\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-create\-if\-not\-exist\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--sys-create-if-not-exist
T}
.TE
.sp 1
Create any NDB system statistics tables or events (or both) that do not already exist when the program is invoked\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-create\-if\-not\-valid\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--sys-create-if-not-valid
T}
.TE
.sp 1
Create any NDB system statistics tables or events that do not already exist, after dropping any that are invalid\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-check\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--sys-check
T}
.TE
.sp 1
Verify that all required system statistics tables and events exist in the NDB kernel\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-skip\-tables\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--sys-skip-tables
T}
.TE
.sp 1
Do not apply any
\fB\-\-sys\-*\fR
options to any statistics tables\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-skip\-events\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--sys-skip-events
T}
.TE
.sp 1
Do not apply any
\fB\-\-sys\-*\fR
options to any events\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-update\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--update
T}
.TE
.sp 1
Update the index statistics for the given table, and restart any auto\-update that was previously configured\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-usage\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--usage
T}
.TE
.sp 1
Display help text and exit; same as
\fB\-\-help\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-verbose\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--verbose
T}
.TE
.sp 1
Turn on verbose output\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-version\fR
.TS
allbox tab(:);
lB l.
T{
Command-Line Format
T}:T{
--version
T}
.TE
.sp 1
Display version information and exit\&.
.RE
.PP
\fBndb_index_stat system options\fR. The following options are used to generate and update the statistics tables in the NDB kernel\&. None of these options can be mixed with statistics options (see
ndb_index_stat statistics options)\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-drop\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-create\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-create\-if\-not\-exist\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-create\-if\-not\-valid\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-check\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-skip\-tables\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-sys\-skip\-events\fR
.RE
.PP
\fBndb_index_stat statistics options\fR. The options listed here are used to generate index statistics\&. They work with a given table and database\&. They cannot be mixed with system options (see
ndb_index_stat system options)\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-database\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-delete\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-update\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-dump\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-\-query\fR
.RE
.SH "COPYRIGHT"
.br
.PP
Copyright \(co 1997, 2022, Oracle and/or its affiliates.
.PP
This documentation is free software; you can redistribute it and/or modify it only under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA or see http://www.gnu.org/licenses/.
.sp
.SH "SEE ALSO"
For more information, please refer to the MySQL Reference Manual,
which may already be installed locally and which is also available
online at http://dev.mysql.com/doc/.
.SH AUTHOR
Oracle Corporation (http://dev.mysql.com/).
