.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.\" Copyright (c) 2007 Tokutek.  All Rights Reserved.
.TH DB_ENV->err 3 "November 2007" Tokutek "TokuDB Programmer's Manual"
.SH NAME
DB_ENV->err
.SH SYNOPSIS
.LP
\fB #include <db.h>
.br
.sp
.HP 13
.BI "void DB_ENV->err(DB_ENV *" dbenv ", int " error ", const char *" fmt ", ...);"
.SH DESCRIPTION
Prints an error message.  The error comprises
.IP prefix
An optional prefix string (set with \fBDB_ENV->set_errpfx\fR), followed by a colon and a space.
.IP printf
An optional printf-style message (provided by \fIfmt\fR, or no printf message is \fIfmt\fR is \fBNULL\fR.
.IP separator
A colon and a space
.IP errstring
An error string provided by \fBdb_strerror\fR.
.SH PARAMETERS
.IP \fIerror
The error number.

.IP \fIfmt
Either \fBNULL\fR or a printf-style message.

.IP ...
The extra arguments needed by the printf.

.SH CONFORMING TO
The TokuDB embedded database provides a subset of the functionality of
the Berkeley DB.  Programs that work with TokuDB probably work with
with most versions of Berkeley DB with only recompilation or
relinking.  The database files are incompatible, however, so to
convert from one library to the other you would need to dump the
database with one library's tool and load it with the other's.
.SH AUTHOR
Tokutek, Inc.
.SH COPYRIGHT
Copyright (c) 2007 Tokutek.  All Rights Reserved.
