.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.\" Copyright (c) 2007 Tokutek.  All Rights Reserved.
.TH tokudb_load 1 "November 2007" Tokutek "TokuDB Programmer's Manual"
.SH NAME
tokudb_load
.SH SYNOPSIS
.B tokudb_load [-TV] [-c
.I name=value
.B ] [-f
.I file
.B ] [-h
.I home
.B ] [-t
.I btree
.B ]
.I db_file
.LP
.SH DESCRIPTION
The
.B tokudb_load
program reads key/data pairs from standard input and writes them into a TokuDB
database.
The format of the key/data pairs is compatible with the 
.B tokudb_dump
program and the Berkeley DB load and dump
programs.
.SH CONFORMING TO
The TokuDB embedded database provides a subset of the functionality of
the Berkeley DB.  Programs that work with TokuDB probably work with
with most versions of Berkeley DB with only recompilation or
relinking.  The database files are incompatible, however, so to
convert from one library to the other you would need to dump the
database with one library's tool and load it with the other's.
.SH UNSUPPORTED BDB OPTIONS
.IP -n
Unsupported.
.IP -P
Unsupported.
.IP "-t hash"
Unsupported.
.IP "-t recno"
Unsupported.
.IP "-t queue"
Unsupported.
.IP "-c keys=0"
Unsupported.
.IP "-c extentsize=value"
Unsupported.
.IP "-c h_ffactor=value"
Unsupported.
.IP "-c h_nelem=value"
Unsupported.
.IP "-c re_len=value"
Unsupported.
.IP "-c re_pad=value"
Unsupported.
.IP "-c renumber=value"
Unsupported.
.IP "-c recnum=value"
Unsupported.
.SH IGNORED BDB OPTIONS
These options will be accepted but not alter behavior.  They may be implemented
in the future.
.IP "-c bt_minkey=value"
Unsupported.
.IP "-c chksum=value"
Unsupported.
.IP "-c db_lorder=value"
Unsupported.
.IP "-c db_pagesize=value"
Unsupported.
.SH DIFFERENCES
Transactions are not yet supported.
The database(s) to be loaded must not be currently in use.
.SH AUTHOR
Tokutek, Inc.
.SH COPYRIGHT
Copyright (c) 2007 Tokutek.  All Rights Reserved.
