.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.\" Copyright (c) 2007 Tokutek.  All Rights Reserved.
.TH tokudb_dump 1 "November 2007" Tokutek "TokuDB Programmer's Manual"
.SH NAME
tokudb_dump
.SH SYNOPSIS
.B tokudb_dump [-pVT] [-f
.I output-file
.B ] [-h
.I home
.B ] [-s
.I database
.B ]
.I db_file
.LP
.SH DESCRIPTION
The
.B tokudb_dump
program reads a TokuDB database and writes its key/data pairs to the standard output.
The format of the key/data pairs is compatible with the 
.B tokudb_load 
program and with the Berkeley DB load and dump programs.
.SH CONFORMING TO
The TokuDB embedded database provides a subset of the functionality of
the Berkeley DB.  Programs that work with TokuDB probably work with
with most versions of Berkeley DB with only recompilation or
relinking.  The database files are incompatible, however, so to
convert from one library to the other you would need to dump the
database with one library's tool and load it with the other's.
.SH ADDITIONAL OPTIONS
.IP -T
Output in a format acceptable for
.B tokudb_load
with the
.B -T
option.
.SH UNSUPPORTED BDB OPTIONS
.IP -d
Unsupported.
.IP -k
Unsupported.
.IP -l
Unsupported.
.IP -N
Unsupported.
.IP -P
Unsupported.
.IP -R
Unsupported.
.IP -r
Unsupported.
.SH DIFFERENCES
You must use the 
.B -s
option to dump each subdatabase individually for a file with multiple databases.
Transactions are not yet supported.
The database to be dumped must not be currently in use.
.SH AUTHOR
Tokutek, Inc.
.SH COPYRIGHT
Copyright (c) 2007 Tokutek.  All Rights Reserved.
