include .defs.mk

TYPE := ndbapitest

SOURCES = mainAsyncGenerator.cpp asyncGenerator.cpp

CCFLAGS_LOC := -I../include -I../../include

BIN_TARGET := DbAsyncGenerator
BIN_TARGET_ARCHIVES := lmc_AsyncUser

include $(NDB_TOP)/Epilogue.mk

