include .defs.mk

TYPE := ndbapitest

BIN_TARGET := vw_test
BIN_TARGET_LIBS := orafunctr decode cirk inifunc
BIN_TARGET_LIBS_DIRS := /home/ndb/junk/vw/ndb/lib

SOURCES := cdrserver.C

include $(NDB_TOP)/Epilogue.mk
