define(
//begin v1.x content
{
	"field-sat-relative+0": "este sábado",
	"field-sat-relative+1": "el próximo sábado",
	"field-dayperiod": "a. m./p. m.",
	"field-sun-relative+-1": "el domingo pasado",
	"field-mon-relative+-1": "el lunes pasado",
	"field-minute": "Minuto",
	"field-day-relative+-1": "ayer",
	"field-weekday": "Día de la semana",
	"field-day-relative+-2": "anteayer",
	"field-era": "Era",
	"field-hour": "Hora",
	"field-sun-relative+0": "este domingo",
	"field-sun-relative+1": "el próximo domingo",
	"field-wed-relative+-1": "el miércoles pasado",
	"field-day-relative+0": "hoy",
	"field-day-relative+1": "mañana",
	"eraAbbr": [
		"antes de R.O.C."
	],
	"field-day-relative+2": "pasado mañana",
	"field-tue-relative+0": "este martes",
	"field-zone": "Zona horaria",
	"field-tue-relative+1": "el próximo martes",
	"field-week-relative+-1": "la semana pasada",
	"field-year-relative+0": "este año",
	"field-year-relative+1": "el próximo año",
	"field-sat-relative+-1": "el sábado pasado",
	"field-year-relative+-1": "el año pasado",
	"field-year": "Año",
	"field-fri-relative+0": "este viernes",
	"field-fri-relative+1": "el próximo viernes",
	"field-week": "Semana",
	"field-week-relative+0": "esta semana",
	"field-week-relative+1": "la próxima semana",
	"field-month-relative+0": "este mes",
	"field-month": "Mes",
	"field-month-relative+1": "el próximo mes",
	"field-fri-relative+-1": "el viernes pasado",
	"field-second": "Segundo",
	"field-tue-relative+-1": "el martes pasado",
	"field-day": "Día",
	"field-mon-relative+0": "este lunes",
	"field-mon-relative+1": "el próximo lunes",
	"field-thu-relative+0": "este jueves",
	"field-second-relative+0": "ahora",
	"field-thu-relative+1": "el próximo jueves",
	"field-wed-relative+0": "este miércoles",
	"field-wed-relative+1": "el próximo miércoles",
	"field-month-relative+-1": "el mes pasado",
	"field-thu-relative+-1": "el jueves pasado"
}
//end v1.x content
);