define({
'bold': 'Bold',
'copy': 'Kopjo',
'cut': 'Prit',
'delete': 'Fshij',
'indent': 'Kthehu',
'insertHorizontalRule': 'Rregull horizontale',
'insertOrderedList': 'Lista e numeruar',
'insertUnorderedList': 'Lista me shënja',
'italic': 'I pjerrët',
'justifyCenter': 'Qënderzo',
'justifyFull': 'Justifiko',
'justifyLeft': 'Rradhit nga e majtë',
'justifyRight': 'Rradhit nga e djathta',
'outdent': 'Outdent',
'paste': 'Ngjit',
'redo': 'Rikthe',
'removeFormat': 'Hiq formatin',
'selectAll': 'Zgjidh të gjitha',
'strikethrough': 'Përplasje',
'subscript': 'Subscript',
'superscript': 'Superscript',
'underline': 'Underline',
'undo': 'Anulo',
'unlink': 'Hiq lidhje',
'createLink': 'Krijo lidhje',
'toggleDir': 'Aktivizo / çaktivizo drejtimin',
'insertImage': 'Fut imazhin',
'insertTable': 'Fut / Ndrysho tabelën',
'toggleTableBorder': 'Aktivizo / çaktivizo kufirin e tabelës',
'deleteTable': 'Fshi tabelën',
'tableProp': 'Properties tabela',
'htmlToggle': 'Burimi HTML',
'foreColor': 'Ngjyra e përparme',
'hiliteColor': 'Ngjyra e sfondit',
'plainFormatBlock': 'Stili i paragrafit',
'formatBlock': 'Stili i paragrafit',
'fontSize': 'Madhësia e shkronjave',
'fontName': 'Emri i fontit',
'tabIndent': 'Tabelë e kthimit',
"fullScreen": "Aktivizo / çaktivizo ekranin e plotë",
"viewSource": "Shiko burimin HTML",
"print": "Shtyp",
"newPage": "Faqja e re",
/* Mesazhet e gabimeve */
"systemShortcut": "Veprimi '${0}' është i disponueshëm vetëm në shfletues përmes një çelësi. Përdorni ${1}. ",
"CtrlKey": "Ctrl+${0}",
"appleKey": "\u2318${0}" // "komanda" ose çelësi i hapur i Apple në Macintosh
});
