include .defs.mk

TYPE := 

BIN_TARGET := listtest
BIN_TARGET_ARCHIVES :=  portlib logger general

SOURCES := LogHandlerListUnitTest.cpp

CCFLAGS_LOC += -I../ -I$(NDB_TOP)/include/logger -I$(NDB_TOP)/include/portlib

include $(NDB_TOP)/Epilogue.mk


