include .defs.mk

TYPE := util

BIN_TARGET := testConfigValues
BIN_TARGET_ARCHIVES := portlib general

SOURCES := testConfigValues.cpp

CCFLAGS_LOC += -I$(call fixpath,$(NDB_TOP)/include/util)

include $(NDB_TOP)/Epilogue.mk
