#! /bin/sh

if [ ! -f configure.in ] ; then
 echo "$0 must be run from MySQL source root"
 exit 1
fi

rm -f TAGS
find -not -path \*SCCS\* -and \
 \( -name \*.cc -or -name \*.h -or -name \*.yy -or -name \*.c \) \
 -print -exec etags -o TAGS --append {} \; 
