define(
//begin v1.x content
{
	"field-second-relative+0": "jetzt",
	"field-weekday": "Wochentag",
	"field-wed-relative+0": "diesen Mittwoch",
	"field-wed-relative+1": "nächsten Mittwoch",
	"dateFormatItem-GyMMMEd": "E, d. MMM U",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"field-tue-relative+-1": "letzten Dienstag",
	"dateFormat-long": "d. MMMM U",
	"field-fri-relative+-1": "letzten Freitag",
	"field-wed-relative+-1": "letzten Mittwoch",
	"dateFormatItem-yyyyQQQ": "QQQ U",
	"dateFormat-full": "EEEE, d. MMMM U",
	"dateFormatItem-yyyyMEd": "E, d.M.y",
	"field-thu-relative+-1": "letzten Donnerstag",
	"dateFormatItem-Md": "d.M.",
	"field-era": "Epoche",
	"field-year": "Jahr",
	"dateFormatItem-yyyyMMMM": "MMMM U",
	"field-hour": "Stunde",
	"field-sat-relative+0": "diesen Samstag",
	"field-sat-relative+1": "nächsten Samstag",
	"field-day-relative+0": "heute",
	"field-thu-relative+0": "diesen Donnerstag",
	"field-day-relative+1": "morgen",
	"field-thu-relative+1": "nächsten Donnerstag",
	"dateFormatItem-GyMMMd": "d. MMM U",
	"field-day-relative+2": "übermorgen",
	"dateFormatItem-H": "HH 'Uhr'",
	"dateFormatItem-Gy": "U",
	"dateFormatItem-yyyyMMMEd": "E, d. MMM U",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMM": "MMM U",
	"dateFormatItem-yyyyMMMd": "d. MMM U",
	"field-sun-relative+0": "diesen Sonntag",
	"dateFormatItem-Hm": "HH:mm",
	"field-sun-relative+1": "nächsten Sonntag",
	"field-minute": "Minute",
	"field-dayperiod": "Tageshälfte",
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "gestern",
	"dateFormatItem-h": "h a",
	"field-day-relative+-2": "vorgestern",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MEd": "E, d.M.",
	"field-fri-relative+0": "diesen Freitag",
	"field-fri-relative+1": "nächsten Freitag",
	"field-day": "Tag",
	"field-zone": "Zeitzone",
	"dateFormatItem-y": "U",
	"field-year-relative+-1": "letztes Jahr",
	"field-month-relative+-1": "letzten Monat",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-yyyyMd": "d.M.y",
	"field-month": "Monat",
	"dateFormatItem-MMM": "LLL",
	"field-tue-relative+0": "diesen Dienstag",
	"field-tue-relative+1": "nächsten Dienstag",
	"field-mon-relative+0": "diesen Montag",
	"field-mon-relative+1": "nächsten Montag",
	"dateFormat-short": "dd.MM.yy",
	"field-second": "Sekunde",
	"field-sat-relative+-1": "letzten Samstag",
	"field-sun-relative+-1": "letzten Sonntag",
	"field-month-relative+0": "diesen Monat",
	"field-month-relative+1": "nächsten Monat",
	"dateFormatItem-Ed": "E, d.",
	"field-week": "Woche",
	"dateFormat-medium": "dd.MM U",
	"field-year-relative+0": "dieses Jahr",
	"field-week-relative+-1": "letzte Woche",
	"dateFormatItem-yyyyM": "M.y",
	"field-year-relative+1": "nächstes Jahr",
	"dateFormatItem-yyyyQQQQ": "QQQQ U",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-GyMMM": "MMM U",
	"field-mon-relative+-1": "letzten Montag",
	"dateFormatItem-yyyy": "U",
	"field-week-relative+0": "diese Woche",
	"field-week-relative+1": "nächste Woche"
}
//end v1.x content
);