define(
//begin v1.x content
{
	"field-sat-relative+0": "diesen Samstag",
	"field-sat-relative+1": "nächsten Samstag",
	"field-dayperiod": "Tageshälfte",
	"field-sun-relative+-1": "letzten Sonntag",
	"field-mon-relative+-1": "letzten Montag",
	"field-minute": "Minute",
	"field-day-relative+-1": "gestern",
	"field-weekday": "Wochentag",
	"field-day-relative+-2": "vorgestern",
	"field-era": "Epoche",
	"field-hour": "Stunde",
	"field-sun-relative+0": "diesen Sonntag",
	"field-sun-relative+1": "nächsten Sonntag",
	"field-wed-relative+-1": "letzten Mittwoch",
	"field-day-relative+0": "heute",
	"field-day-relative+1": "morgen",
	"field-day-relative+2": "übermorgen",
	"dateFormat-long": "d. MMMM y G",
	"field-tue-relative+0": "diesen Dienstag",
	"field-zone": "Zeitzone",
	"field-tue-relative+1": "nächsten Dienstag",
	"field-week-relative+-1": "letzte Woche",
	"dateFormat-medium": "dd.MM.y G",
	"field-year-relative+0": "dieses Jahr",
	"field-year-relative+1": "nächstes Jahr",
	"field-sat-relative+-1": "letzten Samstag",
	"field-year-relative+-1": "letztes Jahr",
	"field-year": "Jahr",
	"field-fri-relative+0": "diesen Freitag",
	"field-fri-relative+1": "nächsten Freitag",
	"field-week": "Woche",
	"field-week-relative+0": "diese Woche",
	"field-week-relative+1": "nächste Woche",
	"field-month-relative+0": "diesen Monat",
	"field-month": "Monat",
	"field-month-relative+1": "nächsten Monat",
	"field-fri-relative+-1": "letzten Freitag",
	"field-second": "Sekunde",
	"field-tue-relative+-1": "letzten Dienstag",
	"field-day": "Tag",
	"field-mon-relative+0": "diesen Montag",
	"field-mon-relative+1": "nächsten Montag",
	"field-thu-relative+0": "diesen Donnerstag",
	"field-second-relative+0": "jetzt",
	"dateFormat-short": "dd.MM.yy GGGGG",
	"field-thu-relative+1": "nächsten Donnerstag",
	"dateFormat-full": "EEEE, d. MMMM y G",
	"field-wed-relative+0": "diesen Mittwoch",
	"field-wed-relative+1": "nächsten Mittwoch",
	"field-month-relative+-1": "letzten Monat",
	"field-thu-relative+-1": "letzten Donnerstag"
}
//end v1.x content
);