include .defs.mk

TYPE := ndbapi

BIN_TARGET := failoverSCI
BIN_TARGET_LIBS := sisci
BIN_TARGET_ARCHIVES := portlib

CCFLAGS_LOC += -I.. 

SOURCES = failoverSCI.cpp

include $(NDB_TOP)/Epilogue.mk





