//>>built
define("dojox/drawing/plugins/_Plugin",["dojo","../util/oo"],function(_1,oo){
return oo.declare(function(_2){
this._cons=[];
_1.mixin(this,_2);
if(this.button&&this.onClick){
this.connect(this.button,"onClick",this,"onClick");
}
},{util:null,keys:null,mouse:null,drawing:null,stencils:null,anchors:null,canvas:null,node:null,button:null,type:"dojox.drawing.plugins._Plugin",connect:function(){
this._cons.push(_1.connect.apply(_1,arguments));
},disconnect:function(_3){
if(!_3){
return;
}
if(!_1.isArray(_3)){
_3=[_3];
}
_1.forEach(_3,_1.disconnect,_1);
}});
});
