#!/bin/sh -
#	$Id: testall,v 1.4 2001/09/13 14:49:37 dda Exp $
#
# Run all the Java regression tests

ecode=0
prefixarg=""
stdinarg=""
while :
do
	case "$1" in
	--prefix=* )
		prefixarg="$1"; shift;;
	--stdin )
		stdinarg="$1"; shift;;
	* )
		break
	esac
done
files="`find . -name \*.java -print`"
for file in $files; do
	name=`echo $file | sed -e 's:^\./::' -e 's/\.java$//'`
	if grep $name ignore > /dev/null; then
		echo "    **** java test $name ignored"
	else
		echo "    ==== java test $name"
		if ! sh ./testone $prefixarg $stdinarg $name; then
			ecode=1
		fi
	fi
done
exit $ecode
