def configure(conf):
  conf.env.append_unique("CPPPATH", conf.env.my_inc)
  conf.env.append_unique("LIBPATH", conf.env.my_lib)


def build(bld):
  client = bld.new_task_gen("cxx", "shlib", "node_addon")
  client.target = "mysqlclient"
  client.source = "mysqlclient_wrapper.cpp"
  client.rpath = bld.env.my_lib
  client.lib = "mysqlclient"
