include .defs.mk

TYPE =		ndbapitest

BIN_TARGET =	testSystemRestart

SOURCES =	testSystemRestart.cpp 

CFLAGS_testSystemRestart.cpp := -I$(call fixpath,$(NDB_TOP)/include/kernel)

include $(NDB_TOP)/Epilogue.mk
