include .defs.mk

TYPE :=

BIN_TARGET := filetest
BIN_TARGET_ARCHIVES := portlib general

SOURCES := FileUnitTest.cpp

CCFLAGS_LOC += -I$(NDB_TOP)/include/logger -I$(NDB_TOP)/include/portlib

include $(NDB_TOP)/Epilogue.mk


