#! /bin/sh

set -e -x

# Only use the "--with-other-libc" parameter, if another libc actually
# exists at this location
OTHER_LIBC_DIR=/usr/local/mysql-glibc
OTHER_LIBC=""
if [ -d OTHER_LIBC_DIR ] ; then
	OTHER_LIBC="--with-other-libc=$OTHER_LIBC_DIR"
fi

BUILD/compile-pentium-max $OTHER_LIBC \
  --with-comment="Official MySQL Binary"  \
  --prefix=/usr/local/mysql --with-extra-charset=complex \
  --enable-thread-safe-client --enable-local-infile \
  --with-server-suffix=-max
nm -n sql/mysqld | gzip -9 -v 2>&1 > sql/mysqld.sym.gz
scripts/make_binary_distribution
make dist
Build-tools/Do-rpm --local
BUILD/compile-pentium --with-other-libc=$OTHER_LIBC_DIR \
  --with-comment="Official MySQL Binary" \
  --prefix=/usr/local/mysql --with-extra-charset=complex \
  --enable-thread-safe-client --enable-local-infile
nm -n sql/mysqld | gzip -9 -v 2>&1 > sql/mysqld.sym.gz
scripts/make_binary_distribution 
