include .defs.mk

TYPE := ndbapi

BIN_TARGET := prioSHM
BIN_TARGET_ARCHIVES := priotransportertest transporter portlib general

CCFLAGS_LOC += -I.. 

SOURCES = prioSHM.cpp

include $(NDB_TOP)/Epilogue.mk

