include .defs.mk

TYPE := 

BIN_TARGET := loggertest
BIN_TARGET_ARCHIVES := logger portlib general

SOURCES := LoggerUnitTest.cpp

CCFLAGS_LOC += -I$(NDB_TOP)/include/logger \
               -I$(NDB_TOP)/include/util \
               -I$(NDB_TOP)/include/portlib

include $(NDB_TOP)/Epilogue.mk


