define(
//begin v1.x content
{
	"field-sat-relative+0": "sâmbăta aceasta",
	"field-sat-relative+1": "sâmbăta viitoare",
	"field-dayperiod": "a.m/p.m.",
	"field-sun-relative+-1": "duminica trecută",
	"field-mon-relative+-1": "lunea trecută",
	"field-minute": "Minut",
	"field-day-relative+-1": "ieri",
	"field-weekday": "Zi a săptămânii",
	"field-day-relative+-2": "alaltăieri",
	"field-era": "Eră",
	"field-hour": "Oră",
	"field-sun-relative+0": "duminica aceasta",
	"field-sun-relative+1": "duminica viitoare",
	"field-wed-relative+-1": "miercurea trecută",
	"field-day-relative+0": "azi",
	"field-day-relative+1": "mâine",
	"field-day-relative+2": "poimâine",
	"field-tue-relative+0": "marțea aceasta",
	"field-zone": "Fus orar",
	"field-tue-relative+1": "marțea viitoare",
	"field-week-relative+-1": "săptămâna trecută",
	"field-year-relative+0": "anul acesta",
	"field-year-relative+1": "anul viitor",
	"field-sat-relative+-1": "sâmbăta trecută",
	"field-year-relative+-1": "anul trecut",
	"field-year": "An",
	"field-fri-relative+0": "vinerea aceasta",
	"field-fri-relative+1": "vinerea viitoare",
	"field-week": "Săptămână",
	"field-week-relative+0": "săptămâna aceasta",
	"field-week-relative+1": "săptămâna viitoare",
	"field-month-relative+0": "luna aceasta",
	"field-month": "Lună",
	"field-month-relative+1": "luna viitoare",
	"field-fri-relative+-1": "vinerea trecută",
	"field-second": "Secundă",
	"field-tue-relative+-1": "marțea trecută",
	"field-day": "Zi",
	"field-mon-relative+0": "lunea aceasta",
	"field-mon-relative+1": "lunea viitoare",
	"field-thu-relative+0": "joia aceasta",
	"field-second-relative+0": "acum",
	"field-thu-relative+1": "joia viitoare",
	"field-wed-relative+0": "miercurea aceasta",
	"field-wed-relative+1": "miercurea viitoare",
	"field-month-relative+-1": "luna trecută",
	"field-thu-relative+-1": "joia trecută"
}
//end v1.x content
);