
.DELETE_ON_ERROR:
ifeq ($(TOKUDB_DIR),)
    #error
CMakeLists.txt: CMakeLists.in
	false #Need to define TOKUDB_DIR
else
CMakeLists.txt: CMakeLists.in
	sed "s?TOKUDB_DIR_REPLACE_ME?$(TOKUDB_DIR)?g" < $< > $@
endif

