include .defs.mk

TYPE := kernel ndbapitest

BIN_TARGET := testInterval
BIN_TARGET_ARCHIVES := portlib general

CCFLAGS_LOC += -I..

SOURCES = testInterval.cpp ../Interval.cpp

include $(NDB_TOP)/Epilogue.mk
