include .defs.mk

TYPE := kernel
DIRS := signaldata

PIC_ARCHIVE    := Y
ARCHIVE_TARGET := trace

SOURCES = SignalLoggerManager.cpp DebuggerNames.cpp BlockNames.cpp LogLevel.cpp EventLogger.cpp GrepError.cpp

include $(NDB_TOP)/Epilogue.mk
