include .defs.mk

DIRS := hugoCalculator hugoFill hugoLoad hugoLockRecords \
	hugoPkDelete hugoPkRead hugoPkReadRecord hugoPkUpdate \
	hugoScanRead hugoScanUpdate restart waiter

include $(NDB_TOP)/Epilogue.mk

_bins_ndbapi : _libs_src
