//>>built
define(["dijit","dojo","dojox","dojo/require!dojox/storage/Provider,dojox/storage/manager,dojox/storage/LocalStorageProvider,dojox/storage/GearsStorageProvider,dojox/storage/WhatWGStorageProvider,dojox/storage/FlashStorageProvider,dojox/storage/BehaviorStorageProvider,dojox/storage/CookieStorageProvider"],function(_1,_2,_3){
_2.provide("dojox.storage._common");
_2.require("dojox.storage.Provider");
_2.require("dojox.storage.manager");
_2.require("dojox.storage.LocalStorageProvider");
_2.require("dojox.storage.GearsStorageProvider");
_2.require("dojox.storage.WhatWGStorageProvider");
_2.require("dojox.storage.FlashStorageProvider");
_2.require("dojox.storage.BehaviorStorageProvider");
_2.require("dojox.storage.CookieStorageProvider");
_3.storage.manager.initialize();
});
