include .defs.mk

TYPE := kernel

BIN_TARGET := grep_systab_test
BIN_TARGET_ARCHIVES := portlib general

CCFLAGS_LOC += -I..

SOURCES = ../GrepSystemTable.cpp grep_systab_test.cpp

include $(NDB_TOP)/Epilogue.mk
