include .defs.mk

TYPE := kernel

ARCHIVE_TARGET := dbtup
SOURCES = \
        DbtupExecQuery.cpp \
        DbtupBuffer.cpp \
        DbtupRoutines.cpp \
        DbtupCommit.cpp \
        DbtupFixAlloc.cpp \
        DbtupTrigger.cpp \
        DbtupAbort.cpp \
        DbtupLCP.cpp \
        DbtupUndoLog.cpp \
        DbtupPageMap.cpp \
        DbtupPagMan.cpp  \
        DbtupStoredProcDef.cpp \
        DbtupMeta.cpp \
        DbtupTabDesMan.cpp \
	DbtupGen.cpp \
        DbtupSystemRestart.cpp \
	DbtupIndex.cpp \
        DbtupDebug.cpp

include $(NDB_TOP)/Epilogue.mk
