include .defs.mk

TYPE := ndbapi

BIN_TARGET := perfOSE
BIN_TARGET_ARCHIVES := perftransportertest transporter portlib

CCFLAGS_LOC += -I..

SOURCES = perfOSE.cpp

include $(NDB_TOP)/Epilogue.mk





