define(
({
	"clearFilterDialogTitle": "Изчисти филтър",
	"filterDefDialogTitle": "Филтър",
	"ruleTitleTemplate": "Правило ${0}",
	"conditionEqual": "равен",
	"conditionNotEqual": "не е равен",
	"conditionLess": "по-малък от",
	"conditionLessEqual": "по-малък от или равен",
	"conditionLarger": "по-голям от",
	"conditionLargerEqual": "по-голям от или равен",
	"conditionContains": "съдържа",
	"conditionIs": "е",
	"conditionStartsWith": "започва с",
	"conditionEndWith": "завършва с",
	"conditionNotContain": "не съдържа",
	"conditionIsNot": "не е",
	"conditionNotStartWith": "не започва с",
	"conditionNotEndWith": "не завършва с",
	"conditionBefore": "преди",
	"conditionAfter": "след",
	"conditionRange": "обхват",
	"conditionIsEmpty": "празен",
	"all": "всички",
	"any": "който и да било",
	"relationAll": "всички правила",
	"waiRelAll": "Комбинирай всички следни правила:",
	"relationAny": "които и да било правила",
	"waiRelAny": "Комбинирай които и да било от следните правила:",
	"relationMsgFront": "Комбинирай:",
	"relationMsgTail": "",
	"and": "и",
	"or": "или",
	"addRuleButton": "Добави правило",
	"waiAddRuleButton": "Добави ново правило",
	"removeRuleButton": "Премахни правило",
	"waiRemoveRuleButtonTemplate": "Премахни правило ${0}",
	"cancelButton": "Отмени",
	"waiCancelButton": "Отмени този диалог",
	"clearButton": "Изчисти",
	"waiClearButton": "Изчисти филтъра",
	"filterButton": "Филтър",
	"waiFilterButton": "Подай филтър",
	"columnSelectLabel": "Колона",
	"waiColumnSelectTemplate": "Колона за правило ${0}",
	"conditionSelectLabel": "Условие",
	"waiConditionSelectTemplate": "Условие за правило ${0}",
	"valueBoxLabel": "Стойност",
	"waiValueBoxTemplate": "Въведи стойност за филтриране на правило ${0}",
	"rangeTo": "до",
	"rangeTemplate": "от ${0} до ${1}",
	"statusTipHeaderColumn": "Колона",
	"statusTipHeaderCondition": "Правила",
	"statusTipTitle": "Лента с филтри",
	"statusTipMsg": "Щракнете върху лентата с филтри тук, за да филтрирате стойностите в ${0}.",
	"anycolumn": "която и да било колона",
	"statusTipTitleNoFilter": "Лента с филтри",
	"statusTipTitleHasFilter": "Филтър",
	"statusTipRelAny": "Комбинирай които и да било правила.",
	"statusTipRelAll": "Комбинирай всички правила.",
	"defaultItemsName": "елементи",
	"filterBarMsgHasFilterTemplate": "Показани ${0} от ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "Не е приложен филтър",
	"filterBarDefButton": "Определи филтър",
	"waiFilterBarDefButton": "Филтрирай таблицата",
	"a11yFilterBarDefButton": "Филтър...",
	"filterBarClearButton": "Изчисти филтър",
	"waiFilterBarClearButton": "Изчисти филтъра",
	"closeFilterBarBtn": "Затвори лентата с филтри",
	"clearFilterMsg": "Това ще премахне филтъра и ще покаже всички налични записи.",
	"anyColumnOption": "Която и да било колона",
	"trueLabel": "Вярно",
	"falseLabel": "Невярно"
})
);
