###
#
# Defines
SHELL       := /bin/sh


DEFINES     = -D_WIN32 -D_M_IX86=600 -D_MSC_EXTENSIONS=0 -U_cdecl -D_MT 
# 
MAKEDEPEND  = g++ -M --nostdinc --nostdinc++ -I"`cygpath -u "$(MSVCDIR)\include"`" -I"`cygpath -u "$(MSVCDIR)\PlatformSDK\include"`" $(DEFINES)
PIC         = -D_LIB
NON_PIC     = -D_LIB

RPCGENFLAGS := -M -C -N

ETAGS       := etags
CTAGS       := ctags

###
#
# Flags
# 
CCFLAGS_WARNINGS	= 
CCFLAGS_TOP		= 
CCFLAGS_LOC		= 
CCFLAGS_WIN		= -DWIN32 -D_WIN32_WINNT=0x0500 -DWINVER=0x0500 -D_MBCS -DNO_COMMAND_HANDLER
CCFLAGS_WIN		+= -W3 -EHsc
#CCFLAGS_WIN		+= -clr 

ifeq (RELEASE, $(NDB_VERSION))
CCFLAGS_WIN		+= -MT -O2 -Ob1 -DNO_DEBUG_MESSAGES
else
ifeq (RELEASE_TRACE, $(NDB_VERSION))
CCFLAGS_WIN		+= -MT -O2 -Ob1 -DNO_DEBUG_MESSAGES
else
CCFLAGS_WIN		+= -MTd -Zi -Od -GS -D_DEBUG
endif
endif

C++         = cl -nologo $(CCFLAGS_WIN)
CC          = cl -nologo $(CCFLAGS_WIN)

CCFLAGS = $(CCFLAGS_LOC) $(CCFLAGS_TOP) $(USER_FLAGS) $(VERSION_FLAGS) $(CCFLAGS_WARNINGS)
CFLAGS  = $(CCFLAGS_LOC) $(CCFLAGS_TOP) $(USER_FLAGS) $(VERSION_FLAGS) $(CCFLAGS_WARNINGS) 

LDFLAGS_TOP = 

LDFLAGS = $(LDFLAGS_LOC) $(LDFLAGS_TOP)

LDLIBS = $(LDLIBS_LOC) $(LDLIBS_TOP)

WIN_LIBS := Ws2_32.lib Advapi32.lib

ifeq (RELEASE, $(NDB_VERSION))
LINK.cc = link -INCREMENTAL:NO -NOLOGO -LARGEADDRESSAWARE $(WIN_LIBS)
else
ifeq (RELEASE_TRACE, $(NDB_VERSION))
LINK.cc = link -INCREMENTAL:NO -NOLOGO -LARGEADDRESSAWARE $(WIN_LIBS)
else
LINK.cc = link -INCREMENTAL -NOLOGO -DEBUG -LARGEADDRESSAWARE $(WIN_LIBS)
endif
endif
