#!/bin/sh

function die
{
  echo
  echo $1
  exit 1
}

echo -n "Running makeinfo..."
makeinfo --no-split -I . manual.texi

if [ $? != 0 ]; then
    die "Manual has errors - fix before you commit"
else
    echo " Looks good."
fi


echo -n "Running texi2html..."
/usr/bin/perl ./Support/texi2html -iso -number manual.texi

if [ $? != 0 ]; then
    die "Manual has errors - fix before you commit"
else
    echo " Looks good."
fi


echo -n "Running texi2dvi..."
texi2dvi --batch --quiet manual.texi

if [ $? != 0 ]; then
    die "Manual has errors - fix before you commit"
else
    echo " Looks good."
fi


[ -z $BROWSER ] && BROWSER=netscape 

echo
echo
echo "Please examine your modifications in \`manual.html'."
echo
echo "If you would like to use a different browser, set the 'BROWSER' environment"
echo "variable." 
echo

$BROWSER file://`pwd`/manual_toc.html &
