//>>built
define("dojox/mvc/_DataBindingExtension",["dojo/_base/array","dojo/aspect","dojo/_base/lang","dijit/_WidgetBase","./_DataBindingMixin"],function(_1,_2,_3,_4,_5){
_3.extend(_4,new _5());
_2.before(_4.prototype,"startup",function(){
this._dbstartup();
});
_2.before(_4.prototype,"destroy",function(){
if(this._modelWatchHandles){
_1.forEach(this._modelWatchHandles,function(h){
h.unwatch();
});
}
if(this._viewWatchHandles){
_1.forEach(this._viewWatchHandles,function(h){
h.unwatch();
});
}
});
});
