define(
//begin v1.x content
{
	"field-second-relative+0": "ora",
	"field-weekday": "Giorno della settimana",
	"field-wed-relative+0": "questo mercoledì",
	"field-wed-relative+1": "mercoledì prossimo",
	"dateFormatItem-GyMMMEd": "E d MMM y G",
	"dateFormatItem-MMMEd": "E d MMM",
	"field-tue-relative+-1": "martedì scorso",
	"dateFormat-long": "dd MMMM y G",
	"field-fri-relative+-1": "venerdì scorso",
	"field-wed-relative+-1": "mercoledì scorso",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormatItem-yyyyMEd": "E d/M/y GGGGG",
	"field-thu-relative+-1": "giovedì scorso",
	"dateFormatItem-Md": "d/M",
	"field-era": "Era",
	"field-year": "Anno",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"field-hour": "Ora",
	"field-sat-relative+0": "questo sabato",
	"field-sat-relative+1": "sabato prossimo",
	"field-day-relative+0": "oggi",
	"field-day-relative+1": "domani",
	"field-thu-relative+0": "questo giovedì",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"field-day-relative+2": "dopodomani",
	"field-thu-relative+1": "giovedì prossimo",
	"dateFormatItem-H": "HH",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-yyyyMMMEd": "E d MMM y G",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"field-sun-relative+0": "questa domenica",
	"dateFormatItem-Hm": "HH:mm",
	"field-sun-relative+1": "domenica prossima",
	"field-minute": "Minuto",
	"field-dayperiod": "AM/PM",
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "ieri",
	"dateFormatItem-h": "hh a",
	"dateTimeFormat-long": "{1} 'alle' {0}",
	"field-day-relative+-2": "l’altro ieri",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E d/M",
	"dateTimeFormat-full": "{1} 'alle' {0}",
	"field-fri-relative+0": "questo venerdì",
	"field-fri-relative+1": "venerdì prossimo",
	"field-day": "Giorno",
	"field-zone": "Fuso orario",
	"dateFormatItem-y": "y G",
	"field-year-relative+-1": "anno scorso",
	"field-month-relative+-1": "mese scorso",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormatItem-yyyyMd": "d/M/y GGGGG",
	"field-month": "Mese",
	"dateFormatItem-MMM": "LLL",
	"field-tue-relative+0": "questo martedì",
	"field-tue-relative+1": "martedì prossimo",
	"field-mon-relative+0": "questo lunedì",
	"field-mon-relative+1": "lunedì prossimo",
	"dateFormat-short": "dd/MM/yy GGGGG",
	"field-second": "Secondo",
	"field-sat-relative+-1": "sabato scorso",
	"field-sun-relative+-1": "domenica scorsa",
	"field-month-relative+0": "questo mese",
	"field-month-relative+1": "mese prossimo",
	"dateFormatItem-Ed": "E d",
	"field-week": "Settimana",
	"dateFormat-medium": "dd MMM y G",
	"field-year-relative+0": "quest’anno",
	"field-week-relative+-1": "settimana scorsa",
	"dateFormatItem-yyyyM": "M/y GGGGG",
	"field-year-relative+1": "anno prossimo",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-mon-relative+-1": "lunedì scorso",
	"dateFormatItem-yyyy": "y G",
	"field-week-relative+0": "questa settimana",
	"field-week-relative+1": "settimana prossima"
}
//end v1.x content
);