include .defs.mk

TYPE := 

BIN_TARGET := socketclient



CCFLAGS_LOC += -I../../util/ -I../../cpcd/

LIBS_LOC += -L$(NDB_TOP)/lib/ -L$(EXTERNAL_LIB_DIR)/sci

LIBS_SPEC += -lsocketclient 


SOURCES = socketClientTest.cpp


include $(NDB_TOP)/Epilogue.mk





