#--------------------------------------------------------------------------
#
# Name        Makefile
#
#
#
# List subdirectories to be travered
include .defs.mk

DIRS := \
	cmvmi           \
	dbacc		\
	dbdict		\
	dbdih		\
	dblqh		\
	dbtc		\
	dbtup		\
	ndbfs           \
	ndbcntr		\
	qmgr		\
	trix            \
        backup          \
        dbutil          \
        suma            \
        grep		\
	dbtux

include ${NDB_TOP}/Epilogue.mk
