#! /bin/sh

export MYDEV="F:/mydev"

export MWCNWx86Includes="$MYDEV/libc/include;$MYDEV/zlib-1.1.4"
export MWNWx86Libraries="$MYDEV/libc/imports;$MYDEV/mw/lib;$MYDEV/zlib-1.1.4"
export MWNWx86LibraryFiles="libcpre.o;libc.imp;netware.imp;mwcrtl.lib;mwcpp.lib;libz.a"

export WINEPATH="$MYDEV/mw/bin"

export PATH="$PATH:$HOME/mydev/mysql-4.1/netware/mw"
