#! /bin/sh

export MYDEV="F:/mysql"

export MWCNWx86Includes="$MYDEV/libc/include"
export MWNWx86Libraries="$MYDEV/libc/imports;$MYDEV/mw/lib"
export MWNWx86LibraryFiles="libcpre.o;libc.imp;netware.imp;mwcrtl.lib;mwcpp.lib"

export WINEPATH="$MYDEV/mw/bin"

export PATH="$PATH:$HOME/mysql/mysql-4.0/netware/mw"

