include .defs.mk

TYPE =			*

NONPIC_ARCHIVE =	N

PIC_ARCHIVE =		Y

ARCHIVE_TARGET =	odbchandles

SOURCES = \
			HandleBase.cpp \
			HandleRoot.cpp \
			HandleEnv.cpp \
			HandleDbc.cpp \
			HandleStmt.cpp \
			HandleDesc.cpp \
			AttrRoot.cpp \
			AttrEnv.cpp \
			AttrDbc.cpp \
			AttrStmt.cpp \
			PoolNdb.cpp \
			DescSpec.cpp \
			FuncTab.cpp \
			InfoTab.cpp

include ../Extra.mk
include $(NDB_TOP)/Epilogue.mk
