include .defs.mk

TYPE =			kernel

ARCHIVE_TARGET =	dbtux

SOURCES = \
                        DbtuxGen.cpp \
			DbtuxMeta.cpp \
			DbtuxMaint.cpp \
			DbtuxNode.cpp \
			DbtuxTree.cpp \
			DbtuxScan.cpp \
			DbtuxCmp.cpp \
			DbtuxDebug.cpp

include $(NDB_TOP)/Epilogue.mk
