include .defs.mk

TYPE =			*

NONPIC_ARCHIVE =	N

PIC_ARCHIVE =		Y

ARCHIVE_TARGET =	odbccommon

SOURCES = \
			common.cpp \
			Ctx.cpp \
			Sqlstate.cpp \
			OdbcData.cpp \
			DiagArea.cpp \
			AttrArea.cpp \
			DescArea.cpp \
			ConnArea.cpp \
			StmtInfo.cpp \
			StmtArea.cpp \
			CodeTree.cpp \
			ResultArea.cpp \
			DataType.cpp \
			DataField.cpp \
			DataRow.cpp

include ../Extra.mk
include $(NDB_TOP)/Epilogue.mk
