define(
//begin v1.x content
{
	"field-second-relative+0": "zdaj",
	"field-weekday": "Dan v tednu",
	"field-wed-relative+0": "To sredo",
	"field-wed-relative+1": "Naslednjo sredo",
	"dateFormatItem-GyMMMEd": "E, d. MMM y G",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"field-tue-relative+-1": "Prejšnji torek",
	"dateFormat-long": "dd. MMMM y G",
	"field-fri-relative+-1": "Prejšnji petek",
	"field-wed-relative+-1": "Prejšnjo sredo",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateTimeFormat-medium": "{1} {0}",
	"dateFormat-full": "EEEE, dd. MMMM y G",
	"dateFormatItem-yyyyMEd": "E, d. M. y G",
	"field-thu-relative+-1": "Prejšnji četrtek",
	"dateFormatItem-Md": "d. M.",
	"field-era": "Doba",
	"field-year": "Leto",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"field-hour": "Ura",
	"field-sat-relative+0": "To soboto",
	"field-sat-relative+1": "Naslednjo soboto",
	"field-day-relative+0": "danes",
	"field-day-relative+1": "jutri",
	"field-thu-relative+0": "Ta četrtek",
	"dateFormatItem-GyMMMd": "d. MMM y G",
	"field-day-relative+2": "pojutrišnjem",
	"field-thu-relative+1": "Naslednji četrtek",
	"dateFormatItem-H": "HH",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-yyyyMMMEd": "E, d. MMM y G",
	"dateFormatItem-M": "L",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "d. MMM y G",
	"field-sun-relative+0": "to nedeljo",
	"dateFormatItem-Hm": "HH:mm",
	"field-sun-relative+1": "naslednjo nedeljo",
	"field-minute": "Minuta",
	"field-dayperiod": "Čas dneva",
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "včeraj",
	"dateFormatItem-h": "h a",
	"dateTimeFormat-long": "{1} {0}",
	"field-day-relative+-2": "predvčerajšnjim",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MEd": "E, d. MM.",
	"dateTimeFormat-full": "{1} {0}",
	"field-fri-relative+0": "Ta petek",
	"field-fri-relative+1": "Naslednji petek",
	"field-day": "Dan",
	"field-zone": "Časovni pas",
	"dateFormatItem-y": "y",
	"field-year-relative+-1": "lani",
	"field-month-relative+-1": "prejšnji mesec",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-GyM": "M/y G",
	"dateFormatItem-yyyyMd": "d. M. y G",
	"field-month": "Mesec",
	"dateFormatItem-MMM": "LLL",
	"field-tue-relative+0": "Ta torek",
	"field-tue-relative+1": "Naslednji torek",
	"field-mon-relative+0": "ta ponedeljek",
	"field-mon-relative+1": "naslednji ponedeljek",
	"dateFormat-short": "d. MM. yy GGGGG",
	"field-second": "Sekunda",
	"field-sat-relative+-1": "Prejšnjo soboto",
	"field-sun-relative+-1": "prejšnjo nedeljo",
	"field-month-relative+0": "ta mesec",
	"field-month-relative+1": "naslednji mesec",
	"dateFormatItem-Ed": "E, d.",
	"field-week": "Teden",
	"dateFormat-medium": "d. MMM y G",
	"field-year-relative+0": "letos",
	"field-week-relative+-1": "prejšnji teden",
	"dateFormatItem-yyyyM": "M/y G",
	"field-year-relative+1": "naslednje leto",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-GyMMM": "MMM y G",
	"field-mon-relative+-1": "prejšnji ponedeljek",
	"dateFormatItem-yyyy": "y G",
	"field-week-relative+0": "ta teden",
	"field-week-relative+1": "naslednji teden"
}
//end v1.x content
);