include .defs.mk

TYPE := repserver kernel

ARCHIVE_TARGET := reprequestor

DIR :=    testRepState \
          testInterval

SOURCES = RepState.cpp \
          RepStateEvent.cpp \
          RepStateRequests.cpp \
	  \
	  Channel.cpp \
          Interval.cpp

include $(NDB_TOP)/Epilogue.mk
