INCLUDE(${MYSQL_CMAKE_SCRIPT_DIR}/cmake_parse_arguments.cmake)

# the target
MACRO(CREATE_JAR)

  CMAKE_PARSE_ARGUMENTS(ARG
    "CLASSPATH;DEPENDENCIES"
    ""
    ${ARGN}
  )

  LIST(GET ARG_DEFAULT_ARGS 0 TARGET)
  SET(JAVA_FILES ${ARG_DEFAULT_ARGS})
  LIST(REMOVE_AT JAVA_FILES 0)

  SET (CLASS_DIR "target/classes")
  SET (JAR_DIR ".")

  FILE(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/${CLASS_DIR})
  FILE(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/${JAR_DIR})

  ADD_CUSTOM_COMMAND(
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${TARGET}

    COMMAND echo "${JAVA_COMPILE} -d ${CMAKE_CURRENT_SOURCE_DIR}/${CLASS_DIR} -classpath ${ARG_CLASSPATH} ${JAVA_FILES}"

    COMMAND ${JAVA_COMPILE} ARGS -d ${CMAKE_CURRENT_SOURCE_DIR}/${CLASS_DIR} ARGS -classpath "${ARG_CLASSPATH}" ${JAVA_FILES}

    COMMAND echo "${CMAKE_COMMAND} ARGS -E chdir ${CMAKE_CURRENT_BINARY_DIR} ${JAVA_ARCHIVE} cfv ${JAR_DIR}/${TARGET} -C ${CLASS_DIR} ."

    COMMAND ${CMAKE_COMMAND} ARGS -E chdir ${CMAKE_CURRENT_BINARY_DIR} ${JAVA_ARCHIVE} cfv ${JAR_DIR}/${TARGET} -C ${CLASS_DIR} . 
  )

  ADD_CUSTOM_TARGET( ${TARGET}
    ALL DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/${TARGET})

  FOREACH(DEP ${ARG_DEPENDENCIES})
    ADD_DEPENDENCIES(${TARGET} ${DEP})
  ENDFOREACH(DEP ${ARG_DEPENDENCIES})

ENDMACRO()
