//>>built
define("dojox/calendar/_VerticalScrollBarBase",["dojo/_base/declare","dojo/_base/event","dojo/_base/lang","dojo/on","dojo/dom-style","dijit/_WidgetBase"],function(_1,_2,_3,on,_4,_5){
return _1("dojox.calendar._VerticalScrollBarBase",_5,{value:0,minimum:0,maximum:100,_scrollHandle:null,buildRendering:function(){
this.inherited(arguments);
this._scrollHandle=on(this.domNode,"scroll",_3.hitch(this,function(_6){
this.value=this._getDomScrollerValue();
this.onChange(this.value);
this.onScroll(this.value);
}));
},destroy:function(_7){
this._scrollHandle.remove();
this.inherited(arguments);
},_getDomScrollerValue:function(){
return this.domNode.scrollTop;
},_setDomScrollerValue:function(_8){
this.domNode.scrollTop=_8;
},_setValueAttr:function(_9){
_9=Math.min(this.maximum,_9);
_9=Math.max(this.minimum,_9);
if(this.value!=_9){
this.value=_9;
this.onChange(_9);
this._setDomScrollerValue(_9);
}
},onChange:function(_a){
},onScroll:function(_b){
},_setMinimumAttr:function(_c){
_c=Math.min(_c,this.maximum);
this.minimum=_c;
},_setMaximumAttr:function(_d){
_d=Math.max(_d,this.minimum);
this.maximum=_d;
_4.set(this.content,"height",_d+"px");
}});
});
