//>>built
define("dojox/calendar/DecorationRenderer",["dojo/_base/declare","dojo/dom-class","dijit/_WidgetBase","dijit/_TemplatedMixin"],function(_1,_2,_3,_4,_5){
return _1("dojox.calendar.DecorationRenderer",[_3,_4],{templateString:"<div class=\"dojoxCalendarDecoration\"></div>",_setItemAttr:function(_6){
if(_6==null){
if(this.item&&this.item.cssClass){
_2.remove(this.domNode,this.item.cssClass);
}
this.item=null;
}else{
if(this.item!=null){
if(this.item.cssClass!=_6.cssClass){
if(this.item.cssClass){
_2.remove(this.domNode,this.item.cssClass);
}
}
this.item=lang.mixin(this.item,_6);
if(_6.cssClass){
_2.add(this.domNode,_6.cssClass);
}
}else{
this.item=_6;
if(_6.cssClass){
_2.add(this.domNode,_6.cssClass);
}
}
}
},postCreate:function(){
this.inherited(arguments);
this._applyAttributes();
}});
});
