CREATE UNDO TABLESPACE `undo_init_001` ADD DATAFILE 'undo_init_001.ibu';
CREATE UNDO TABLESPACE `undo_init_002` ADD DATAFILE 'undo_init_002.ibu';
CREATE UNDO TABLESPACE `undo_init_003` ADD DATAFILE 'undo_init_003.ibu';
CREATE UNDO TABLESPACE `undo_init_004` ADD DATAFILE 'undo_init_004.ibu';
CREATE UNDO TABLESPACE `undo_init_005` ADD DATAFILE 'undo_init_005.ibu';
CREATE UNDO TABLESPACE `undo_init_006` ADD DATAFILE 'undo_init_006.ibu';
CREATE UNDO TABLESPACE `undo_init_007` ADD DATAFILE 'undo_init_007.ibu';
CREATE UNDO TABLESPACE `undo_init_008` ADD DATAFILE 'undo_init_008.ibu';
CREATE UNDO TABLESPACE `undo_init_009` ADD DATAFILE 'undo_init_009.ibu';
CREATE UNDO TABLESPACE `undo_init_010` ADD DATAFILE 'undo_init_010.ibu';

CREATE UNDO TABLESPACE `undo_init_011` ADD DATAFILE 'undo_init_011.ibu';
CREATE UNDO TABLESPACE `undo_init_012` ADD DATAFILE 'undo_init_012.ibu';
CREATE UNDO TABLESPACE `undo_init_013` ADD DATAFILE 'undo_init_013.ibu';
CREATE UNDO TABLESPACE `undo_init_014` ADD DATAFILE 'undo_init_014.ibu';
CREATE UNDO TABLESPACE `undo_init_015` ADD DATAFILE 'undo_init_015.ibu';
CREATE UNDO TABLESPACE `undo_init_016` ADD DATAFILE 'undo_init_016.ibu';
CREATE UNDO TABLESPACE `undo_init_017` ADD DATAFILE 'undo_init_017.ibu';
CREATE UNDO TABLESPACE `undo_init_018` ADD DATAFILE 'undo_init_018.ibu';
CREATE UNDO TABLESPACE `undo_init_019` ADD DATAFILE 'undo_init_019.ibu';
CREATE UNDO TABLESPACE `undo_init_020` ADD DATAFILE 'undo_init_020.ibu';

CREATE UNDO TABLESPACE `undo_init_021` ADD DATAFILE 'undo_init_021.ibu';
CREATE UNDO TABLESPACE `undo_init_022` ADD DATAFILE 'undo_init_022.ibu';
CREATE UNDO TABLESPACE `undo_init_023` ADD DATAFILE 'undo_init_023.ibu';
CREATE UNDO TABLESPACE `undo_init_024` ADD DATAFILE 'undo_init_024.ibu';
CREATE UNDO TABLESPACE `undo_init_025` ADD DATAFILE 'undo_init_025.ibu';
CREATE UNDO TABLESPACE `undo_init_026` ADD DATAFILE 'undo_init_026.ibu';
CREATE UNDO TABLESPACE `undo_init_027` ADD DATAFILE 'undo_init_027.ibu';
CREATE UNDO TABLESPACE `undo_init_028` ADD DATAFILE 'undo_init_028.ibu';
CREATE UNDO TABLESPACE `undo_init_029` ADD DATAFILE 'undo_init_029.ibu';
CREATE UNDO TABLESPACE `undo_init_030` ADD DATAFILE 'undo_init_030.ibu';

CREATE UNDO TABLESPACE `undo_init_031` ADD DATAFILE 'undo_init_031.ibu';
CREATE UNDO TABLESPACE `undo_init_032` ADD DATAFILE 'undo_init_032.ibu';
