#! /usr/bin/env python
"""Launch script for the configurator backend. Parses command line options and starts the web server."""

import sys
import platform
import os.path

def num_pyver(vn):
    if isinstance(vn, str): 
        return int(''.join(filter(str.isdigit, vn)))
    return vn

def num_py_major_minor_tuple():
    return map(num_pyver, platform.python_version_tuple()[0:2])


install_bindir = ''
if __name__ == '__main__':
    abs_install_bindir = os.path.dirname(os.path.abspath(sys.argv[0]))
    try:
        prefix = abs_install_bindir[0:abs_install_bindir.rindex(install_bindir)]
    except ValueError:
        prefix = abs_install_bindir

    abs_install_subdir = os.path.normpath(os.path.join(prefix, 
                                                       '.'))
    sys.path.append(abs_install_subdir)

    (pymajor, pyminor) = num_py_major_minor_tuple()
    assert (pymajor == 2 and pyminor >= 6), 'Unsupported Python version: '+str(platform.python_version())
    sys.path.append('/opt/csw/lib/python/site-packages')

    import request_handler
    request_handler.main(prefix, abs_install_subdir)
        
