#!/bin/sh
#
# see: The MySQL Test Framework :: 7 Creating and Executing Unit Tests
#   http://dev.mysql.com/doc/mysqltest/en/unit-test.html
# see: Test Anything Protocol (TAP)
#   http://testanything.org/wiki/index.php/Main_Page
#   http://en.wikipedia.org/wiki/Test_Anything_Protocol

# not sure which protocol version we're using
#echo "TAP version 13"

# test range
echo "1..3"

# this script gets invoked from $(top_srcdir)/unittest
cd ../storage/ndb/ndbjtie/jtie/test

# log file for output from this script
log="`pwd`/jtie_unit_tests-t.log"
rm -f "$log"
touch "$log"

# run test
( cd myapi;
    echo "running test from directory:" >> "$log" 2>&1
    echo "  `pwd`" >> "$log" 2>&1
    if ! ./test_myapi.sh >> "$log" 2>&1; then
	s="not "
    fi
    status="${s}ok 1 - test_myapi"
    echo "$status" >> "$log" 2>&1
    echo "" >> "$log" 2>&1
    echo "$status"
)

# run test
( cd myjapi;
    echo "running test from directory:" >> "$log" 2>&1
    echo "  `pwd`" >> "$log" 2>&1
    if ! ./test_myjapi.sh >> "$log" 2>&1; then
	s="not "
    fi
    status="${s}ok 2 - test_myjapi"
    echo "$status" >> "$log" 2>&1
    echo "" >> "$log" 2>&1
    echo "$status"
)

# run test
( cd unload;
    echo "running test from directory:" >> "$log" 2>&1
    echo "  `pwd`" >> "$log" 2>&1
    if ! ./test_unload.sh >> "$log" 2>&1; then
	s="not "
    fi
    status="${s}ok 3 - test_unload"
    echo "$status" >> "$log" 2>&1
    echo "" >> "$log" 2>&1
    echo "$status"
)

echo "done." >> "$log" 2>&1
