include .defs.mk

TYPE := ndbapi

BIN_TARGET := prioTCP
BIN_TARGET_ARCHIVES := priotransportertest transporter portlib general

CCFLAGS_LOC += -I.. 

SOURCES = prioTCP.cpp

include $(NDB_TOP)/Epilogue.mk

