define({ root:
//begin v1.x content
({
	"saveLabel": "Save",
	"saveSettingLabelOn": "Set Auto-Save Interval...",
	"saveSettingLabelOff": "Turn off Auto-Save",
	"saveSettingdialogTitle": "Auto-Save",
	"saveSettingdialogDescription": "Specify Auto-Save interval",
	"saveSettingdialogParamName": "Auto-Save Interval",
	"saveSettingdialogParamLabel": "min",
	"saveSettingdialogButtonOk": "Set Interval",
	"saveSettingdialogButtonCancel": "Cancel",
	"saveMessageSuccess": "Saved at ${0}",
	"saveMessageFail": "Failed to save at ${0}"
})
//end v1.x content
,
"bs": true,
"mk": true,
"sr": true,
"zh": true,
"zh-tw": true,
"uk": true,
"tr": true,
"th": true,
"sv": true,
"sl": true,
"sk": true,
"ru": true,
"ro": true,
"pt": true,
"pt-pt": true,
"pl": true,
"nl": true,
"nb": true,
"ko": true,
"kk": true,
"ja": true,
"it": true,
"id": true,
"hu": true,
"hr": true,
"he": true,
"fr": true,
"fi": true,
"es": true,
"el": true,
"eu": true,
"de": true,
"da": true,
"cs": true,
"ca": true,
"bg": true,
"ar": true
});
