define({ root:
//begin v1.x content
({
	"nodeActions": "${nodeName} Actions",
	"selectContents": "Select contents",
	"selectElement": "Select element",
	"deleteElement": "Delete element",
	"deleteContents": "Delete contents",
	"moveStart": "Move cursor to start",
	"moveEnd": "Move cursor to end"
})
//end v1.x content
,
"bs": true,
"mk": true,
"sr": true,
"zh": true,
"zh-tw": true,
"uk": true,
"tr": true,
"th": true,
"sv": true,
"sl": true,
"sk": true,
"ru": true,
"ro": true,
"pt": true,
"pt-pt": true,
"pl": true,
"nl": true,
"nb": true,
"ko": true,
"kk": true,
"ja": true,
"it": true,
"id": true,
"hu": true,
"hr": true,
"he": true,
"fr": true,
"fi": true,
"es": true,
"el": true,
"eu": true,
"de": true,
"da": true,
"cs": true,
"ca": true,
"bg": true,
"ar": true
});
