define({ root:
//begin v1.x content
({
	smiley: "Insert Emoticon",
	emoticonSmile: "smile",
	emoticonLaughing: "laughing",
	emoticonWink: "wink",
	emoticonGrin: "grin",
	emoticonCool: "cool",
	emoticonAngry: "angry",
	emoticonHalf: "half",
	emoticonEyebrow: "eyebrow",
	emoticonFrown: "frown",
	emoticonShy: "shy",
	emoticonGoofy: "goofy",
	emoticonOops: "oops",
	emoticonTongue: "tongue",
	emoticonIdea: "idea",
	emoticonYes: "yes",
	emoticonNo: "no",
	emoticonAngel: "angel",
	emoticonCrying: "crying",
	emoticonHappy: "happy"
})
//end v1.x content
,
"bs": true,
"mk": true,
"sr": true,
"zh": true,
"zh-tw": true,
"uk": true,
"tr": true,
"th": true,
"sv": true,
"sl": true,
"sk": true,
"ru": true,
"ro": true,
"pt": true,
"pt-pt": true,
"pl": true,
"nl": true,
"nb": true,
"ko": true,
"kk": true,
"ja": true,
"it": true,
"id": true,
"hu": true,
"hr": true,
"he": true,
"fr": true,
"fi": true,
"es": true,
"el": true,
"eu": true,
"de": true,
"da": true,
"cs": true,
"ca": true,
"bg": true,
"ar": true
});
