define({ root:
//begin v1.x content
({
	widgetLabel: "Batch Spell Check",
	unfound: "Not found",
	skip: "Skip",
	skipAll: "Skip All",
	toDic: "Add to dictionary",
	suggestions: "Suggestions",
	replace: "Replace",
	replaceWith: "Replace with",
	replaceAll: "Replace All",
	cancel: "Cancel",
	msg: "No misspellings found",
	iSkip: "Skip this",
	iSkipAll: "Skip all like this",
	iMsg: "No spelling suggestions"
})
//end v1.x content
,
"bs": true,
"mk": true,
"sr": true,
"zh": true,
"zh-tw": true,
"uk": true,
"tr": true,
"th": true,
"sv": true,
"sl": true,
"sk": true,
"ru": true,
"ro": true,
"pt": true,
"pt-pt": true,
"pl": true,
"nl": true,
"nb": true,
"ko": true,
"kk": true,
"ja": true,
"it": true,
"id": true,
"hu": true,
"hr": true,
"he": true,
"fr": true,
"fi": true,
"es": true,
"el": true,
"eu": true,
"de": true,
"da": true,
"cs": true,
"ca": true,
"bg": true,
"ar": true
});
