include .defs.mk

TYPE := 

BIN_TARGET := keso
BIN_TARGET_ARCHIVES := portlib general

SOURCES := testProperties.cpp

CCFLAGS_LOC += -I$(call fixpath,$(NDB_TOP)/include/util)

include $(NDB_TOP)/Epilogue.mk
