define(
//begin v1.x content
{
	"months-format-narrow": [
		"正",
		"二",
		"三",
		"四",
		"五",
		"六",
		"七",
		"八",
		"九",
		"十",
		"冬",
		"臘"
	],
	"field-second-relative+0": "現在",
	"field-weekday": "週天",
	"field-wed-relative+0": "本週三",
	"field-wed-relative+1": "下週三",
	"dateFormatItem-GyMMMEd": "rU年MMMdE",
	"dateFormatItem-MMMEd": "MMMd日E",
	"field-tue-relative+-1": "上週二",
	"dateFormat-long": "rU年MMMd",
	"field-fri-relative+-1": "上週五",
	"field-wed-relative+-1": "上週三",
	"months-format-wide": [
		"正月",
		"二月",
		"三月",
		"四月",
		"五月",
		"六月",
		"七月",
		"八月",
		"九月",
		"十月",
		"冬月",
		"臘月"
	],
	"dateFormatItem-yyyyQQQ": "rU年QQQQ",
	"dateFormat-full": "rU年MMMdEEEE",
	"dateFormatItem-yyyyMEd": "rU年MMMd，E",
	"field-thu-relative+-1": "上週四",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMd": "r年MMMd",
	"field-era": "年代",
	"months-standAlone-wide": [
		"正月",
		"二月",
		"三月",
		"四月",
		"五月",
		"六月",
		"七月",
		"八月",
		"九月",
		"十月",
		"冬月",
		"臘月"
	],
	"field-year": "年",
	"field-hour": "小時",
	"months-format-abbr": [
		"正月",
		"二月",
		"三月",
		"四月",
		"五月",
		"六月",
		"七月",
		"八月",
		"九月",
		"十月",
		"冬月",
		"臘月"
	],
	"field-sat-relative+0": "本週六",
	"field-sat-relative+1": "下週六",
	"field-day-relative+0": "今天",
	"field-thu-relative+0": "本週四",
	"field-day-relative+1": "明天",
	"field-thu-relative+1": "下週四",
	"dateFormatItem-GyMMMd": "r年MMMd",
	"field-day-relative+2": "後天",
	"months-standAlone-abbr": [
		"正月",
		"二月",
		"三月",
		"四月",
		"五月",
		"六月",
		"七月",
		"八月",
		"九月",
		"十月",
		"冬月",
		"臘月"
	],
	"dateFormatItem-Gy": "rU年",
	"dateFormatItem-yyyyMMMEd": "rU年MMMdE",
	"dateFormatItem-M": "MMM",
	"dateFormatItem-yyyyMMM": "rU年MMM",
	"dateFormatItem-yyyyMMMd": "r年MMMd",
	"field-sun-relative+0": "本週日",
	"field-sun-relative+1": "下週日",
	"field-minute": "分鐘",
	"field-dayperiod": "上午/下午",
	"dateFormatItem-d": "d日",
	"field-day-relative+-1": "昨天",
	"field-day-relative+-2": "前天",
	"dateFormatItem-MMMd": "MMMd日",
	"dateFormatItem-MEd": "M/dE",
	"field-fri-relative+0": "本週五",
	"field-fri-relative+1": "下週五",
	"field-day": "日",
	"field-zone": "時區",
	"dateFormatItem-y": "rU年",
	"months-standAlone-narrow": [
		"正",
		"二",
		"三",
		"四",
		"五",
		"六",
		"七",
		"八",
		"九",
		"十",
		"冬",
		"臘"
	],
	"field-year-relative+-1": "去年",
	"field-month-relative+-1": "上個月",
	"dateFormatItem-yyyyMd": "r年MMMd",
	"field-month": "月",
	"field-tue-relative+0": "本週二",
	"field-tue-relative+1": "下週二",
	"field-mon-relative+0": "本週一",
	"field-mon-relative+1": "下週一",
	"dateFormat-short": "r/M/d",
	"field-second": "秒",
	"field-sat-relative+-1": "上週六",
	"field-sun-relative+-1": "上週日",
	"field-month-relative+0": "本月",
	"field-month-relative+1": "下個月",
	"dateFormatItem-Ed": "d日E",
	"field-week": "週",
	"dateFormat-medium": "r年MMMd",
	"field-year-relative+0": "今年",
	"field-week-relative+-1": "上週",
	"dateFormatItem-yyyyM": "rU年MMM",
	"field-year-relative+1": "明年",
	"dateFormatItem-yyyyQQQQ": "rU年QQQQ",
	"dateFormatItem-GyMMM": "rU年MMM",
	"field-mon-relative+-1": "上週一",
	"dateFormatItem-yyyy": "rU年",
	"field-week-relative+0": "本週",
	"field-week-relative+1": "下週"
}
//end v1.x content
);