.\" Copyright (c) 2018 Yubico AB. All rights reserved.
.\" Use of this source code is governed by a BSD-style
.\" license that can be found in the LICENSE file.
.\"
.Dd $Mdocdate: May 25 2018 $
.Dt FIDO_INIT 3
.Os
.Sh NAME
.Nm fido_init
.Nd initialise the FIDO 2 library
.Sh SYNOPSIS
.In fido.h
.Ft void
.Fn fido_init "int flags"
.Sh DESCRIPTION
The
.Fn fido_init
function initialises the
.Em libfido2
library.
Its invocation must precede that of any other
.Em libfido2
function in the context of the executing thread.
.Pp
If
.Dv FIDO_DEBUG
is set in
.Fa flags ,
then
debug output will be emitted by
.Em libfido2
on
.Em stderr .
Alternatively, the
.Ev FIDO_DEBUG
environment variable may be set.
.Pp
If
.Dv FIDO_DISABLE_U2F_FALLBACK
is set in
.Fa flags ,
then
.Em libfido2
will not fallback to U2F in
.Xr fido_dev_open 3
if a device claims to be FIDO2 but fails to respond to a
FIDO2 command.
.Sh SEE ALSO
.Xr fido_assert_new 3 ,
.Xr fido_cred_new 3 ,
.Xr fido_dev_info_manifest 3 ,
.Xr fido_dev_open 3
