include .defs.mk

TYPE := ndbapi
BIN_TARGET := prioSCI
BIN_TARGET_LIBS := sisci
BIN_TARGET_ARCHIVES := priotransportertest transporter portlib general

CCFLAGS_LOC += -I.. 

SOURCES = prioSCI.cpp

include $(NDB_TOP)/Epilogue.mk





