//>>built
define("dojox/mobile/SearchBox",["dojo/_base/declare","dojo/_base/lang","dijit/form/_SearchMixin","dojox/mobile/TextBox","dojo/dom-class","dojo/keys","./sniff"],function(_1,_2,_3,_4,_5,_6,_7){
return _1("dojox.mobile.SearchBox",[_4,_3],{baseClass:"mblTextBox mblSearchBox",type:"search",placeHolder:"",incremental:true,_setIncrementalAttr:function(_8){
this.incremental=_8;
},_onInput:function(e){
if(e.charOrCode==_6.ENTER){
e.charOrCode=229;
}else{
if(!this.incremental){
e.charOrCode=0;
}
}
this.inherited(arguments);
},postCreate:function(){
this.inherited(arguments);
this.textbox.removeAttribute("incremental");
if(!this.textbox.hasAttribute("results")){
this.textbox.setAttribute("results","0");
}
if(_7("iphone")<5){
_5.add(this.domNode,"iphone4");
this.connect(this.textbox,"onfocus",function(){
if(this.textbox.value!==""){
setTimeout(_2.hitch(this,function(){
if(this.textbox.value===""){
this._onInput({charOrCode:_6.ENTER});
}
}),0);
}
});
}
this.connect(this.textbox,"onsearch",function(){
this._onInput({charOrCode:_6.ENTER});
});
}});
});
