//>>built
define("dojox/mobile/SpinWheel",["dojo/_base/declare","dojo/_base/array","dojo/dom-construct","./_PickerBase","./SpinWheelSlot"],function(_1,_2,_3,_4){
return _1("dojox.mobile.SpinWheel",_4,{baseClass:"mblSpinWheel",buildRendering:function(){
this.inherited(arguments);
_3.create("div",{className:"mblSpinWheelBar"},this.domNode);
},startup:function(){
if(this._started){
return;
}
this.centerPos=Math.round(this.domNode.offsetHeight/2);
this.inherited(arguments);
},resize:function(){
this.centerPos=Math.round(this.domNode.offsetHeight/2);
_2.forEach(this.getChildren(),function(_5){
_5.resize&&_5.resize();
});
},addChild:function(_6,_7){
this.inherited(arguments);
if(this._started){
_6.setInitialValue();
}
}});
});
