include .defs.mk	

TYPE := kernel

BIN_TARGET := testSimplePropertiesSection
BIN_TARGET_ARCHIVES := general portlib 

SOURCES = test.cpp ../SimplePropertiesSection.cpp

include $(NDB_TOP)/Epilogue.mk
