--echo #
--echo # WL#16525: Dynamic Datamasking Support in MySQL
--echo #

--echo # Test cases for CREATE/DROP/SHOW MASKING POLICY.

--error ER_MASKING_POLICY_COMPONENT_ERROR
CREATE MASKING POLICY mak_pol(i)
  CASE WHEN CURRENT_ROLE_IN('admin') THEN sha2('abc', 224) ELSE i END;
--error ER_MASKING_POLICY_COMPONENT_ERROR
CREATE MASKING POLICY IF NOT EXISTS pol_if_not_exists(i)
  CASE WHEN CURRENT_ROLE_IN('admin') THEN sha2('abc', 224) ELSE i END;
--error ER_MASKING_POLICY_COMPONENT_ERROR
CREATE MASKING POLICY p1(i)
  CASE WHEN CURRENT_USER_IN ('admin, app') THEN sha2('abc', i) ELSE i END;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SHOW CREATE MASKING POLICY p1;
--error ER_MASKING_POLICY_COMPONENT_ERROR
CREATE MASKING POLICY p1_1(i)
  CASE WHEN CURRENT_USER_IN('admin, app') THEN sha2('abc', 224) ELSE i END;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SHOW CREATE MASKING POLICY p1_1;
--error ER_MASKING_POLICY_COMPONENT_ERROR
CREATE MASKING POLICY p2(i)
  CASE WHEN CURRENT_USER_IN('admin, app') THEN i ELSE sha2('abc', i) END;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SHOW CREATE MASKING POLICY p2;
--error ER_MASKING_POLICY_COMPONENT_ERROR
CREATE MASKING POLICY p2_2(i)
  CASE WHEN CURRENT_USER_IN('admin, app') THEN i ELSE sha2('abc', 224) END;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SHOW CREATE MASKING POLICY p2_2;
--error ER_MASKING_POLICY_COMPONENT_ERROR
DROP MASKING POLICY pol_does_not_exist;
--error ER_MASKING_POLICY_COMPONENT_ERROR
DROP MASKING POLICY IF EXISTS pol_does_not_exist;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SHOW CREATE MASKING POLICY pol_does_not_exist;

--echo # Test cases for assigning/unassigning masking policies on columns
--echo # with CREATE TABLE and ALTER TABLE.

CREATE TABLE t1(i VARCHAR(256) MASKING POLICY p1);
SHOW CREATE TABLE t1;
DROP TABLE t1;

CREATE TABLE t2(i VARCHAR(256));
ALTER TABLE t2 ALTER COLUMN i DROP MASKING POLICY;
SHOW CREATE TABLE t2;

ALTER TABLE t2 ALTER COLUMN i SET MASKING POLICY p2;
SHOW CREATE TABLE t2;
DROP TABLE t2;

CREATE TABLE t1(i VARCHAR(256));
ALTER TABLE t1 ADD COLUMN j VARCHAR(256) MASKING POLICY p1;
SHOW CREATE TABLE t1;
DROP TABLE t1;

CREATE TABLE t1(i VARCHAR(256) MASKING POLICY p1);
SHOW CREATE TABLE t1;
DROP TABLE t1;

CREATE TABLE t2(i VARCHAR(256) MASKING POLICY p3);
SHOW CREATE TABLE t2;

ALTER TABLE t2 ALTER COLUMN i DROP MASKING POLICY;
SHOW CREATE TABLE t2;

ALTER TABLE t2 ALTER COLUMN i SET MASKING POLICY p2;
SHOW CREATE TABLE t2;
DROP TABLE t2;

CREATE TABLE t1(i VARCHAR(256) MASKING POLICY p1);
ALTER TABLE t1 ADD COLUMN j VARCHAR(256) MASKING POLICY p1;
SHOW CREATE TABLE t1;
ALTER TABLE t1 DROP COLUMN j;
DROP TABLE t1;

CREATE TABLE t3(i INT);
ALTER TABLE t3 MODIFY COLUMN i INT MASKING POLICY p1;
SHOW CREATE TABLE t3;
ALTER TABLE t3 MODIFY COLUMN i INT MASKING POLICY p2;
SHOW CREATE TABLE t3;
ALTER TABLE t3 MODIFY COLUMN i INT;
SHOW CREATE TABLE t3;
DROP TABLE t3;

--echo # Tests for I_S.COLUMNS.EXTRA marker on masked columns.

CREATE TABLE t4(i INT MASKING POLICY p1, j INT);
CREATE TABLE t5(k INT);

SELECT column_name, extra
FROM information_schema.columns
WHERE table_schema = database() AND table_name = 't4'
ORDER BY column_name;

SELECT DISTINCT table_name
FROM information_schema.columns
WHERE table_schema = database()
  AND table_name IN ('t4', 't5')
  AND extra LIKE '%MASKING POLICY%'
ORDER BY table_name;

ALTER TABLE t4 ALTER COLUMN i DROP MASKING POLICY;
SELECT column_name, extra
FROM information_schema.columns
WHERE table_schema = database() AND table_name = 't4'
ORDER BY column_name;

SELECT DISTINCT table_name
FROM information_schema.columns
WHERE table_schema = database()
  AND table_name IN ('t4', 't5')
  AND extra LIKE '%MASKING POLICY%'
ORDER BY table_name;

ALTER TABLE t4 ALTER COLUMN i SET MASKING POLICY p1;
ALTER TABLE t4 MODIFY COLUMN i INT MASKING POLICY p1 INVISIBLE;
SELECT column_name, extra
FROM information_schema.columns
WHERE table_schema = database() AND table_name = 't4'
ORDER BY column_name;

DROP TABLE t4, t5;

# Masking policy names cannot be empty or end in a space. And they
# cannot exceed 64 characters.
--error ER_SP_WRONG_NAME
CREATE TABLE t(col INT MASKING POLICY ``);
--error ER_SP_WRONG_NAME
CREATE TABLE t(col INT MASKING POLICY ` `);
--error ER_SP_WRONG_NAME
CREATE TABLE t(col INT MASKING POLICY `x `);
--error ER_TOO_LONG_IDENT
CREATE TABLE t(col INT
MASKING POLICY aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
);

# The same invalid names should also be rejected by ALTER TABLE variants.
CREATE TABLE t(i INT);
--error ER_SP_WRONG_NAME
ALTER TABLE t ALTER COLUMN i SET MASKING POLICY ``;
--error ER_SP_WRONG_NAME
ALTER TABLE t ALTER COLUMN i SET MASKING POLICY ` `;
--error ER_SP_WRONG_NAME
ALTER TABLE t ALTER COLUMN i SET MASKING POLICY `x `;
--error ER_TOO_LONG_IDENT
ALTER TABLE t ALTER COLUMN i SET MASKING POLICY
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa;

--error ER_SP_WRONG_NAME
ALTER TABLE t MODIFY COLUMN i INT MASKING POLICY ``;
--error ER_SP_WRONG_NAME
ALTER TABLE t MODIFY COLUMN i INT MASKING POLICY ` `;
--error ER_SP_WRONG_NAME
ALTER TABLE t MODIFY COLUMN i INT MASKING POLICY `x `;
--error ER_TOO_LONG_IDENT
ALTER TABLE t MODIFY COLUMN i INT MASKING POLICY
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa;

--error ER_SP_WRONG_NAME
ALTER TABLE t ADD COLUMN j INT MASKING POLICY ``;
--error ER_SP_WRONG_NAME
ALTER TABLE t ADD COLUMN k INT MASKING POLICY ` `;
--error ER_SP_WRONG_NAME
ALTER TABLE t ADD COLUMN l INT MASKING POLICY `x `;
--error ER_TOO_LONG_IDENT
ALTER TABLE t ADD COLUMN l INT MASKING POLICY
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa;

DROP TABLE t;

--echo # Tests for DML statements on a table with a masked column. Since the
--echo # needed component is not installed, attempts to read the masked
--echo # column should fail. Statements that don't attempt to read the masked
--echo # column should succeed, even those that write to the masked columns.

CREATE TABLE t1 (i INT MASKING POLICY p1, j INT);

# Should pass. Does not access any column with a masking policy.
SELECT j FROM t1;

# The rest should fail because they access a column with a masking
# policy that does not exist.
--error ER_MASKING_POLICY_COMPONENT_ERROR
SELECT * FROM t1;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SELECT i FROM t1;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SELECT j FROM t1 WHERE i < 10;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SELECT j FROM t1 ORDER BY i;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SELECT SUM(i) FROM t1;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SELECT SUM(j) FROM t1 GROUP BY i;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SELECT FIRST_VALUE(i) OVER () FROM t1;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SELECT ROW_NUMBER() OVER (PARTITION BY i) FROM t1;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SELECT ROW_NUMBER() OVER (ORDER BY i) FROM t1;
--error ER_MASKING_POLICY_COMPONENT_ERROR
SELECT 1 FROM t1 JOIN t1 AS t2 USING (i);
--error ER_MASKING_POLICY_COMPONENT_ERROR
SELECT 1 FROM t1 NATURAL JOIN t1 AS t2;

# INSERT, UPDATE, DELETE on tables with unavailable masking policies
# is allowed, as long as they don't need to read a masked column.
INSERT INTO t1 VALUES (), ();
INSERT INTO t1 VALUES (1, 2), (2, 3);
INSERT INTO t1(i) VALUES (3);
INSERT INTO t1(j) VALUES (4);
--error ER_MASKING_POLICY_COMPONENT_ERROR
INSERT INTO t1 SELECT * FROM t1;
--error ER_MASKING_POLICY_COMPONENT_ERROR
INSERT INTO t1(j) SELECT j FROM t1 WHERE i <> 0;
INSERT INTO t1 SELECT j, j FROM t1 WHERE j <> 0;

# Verify that the INSERT statements succeeded.
ALTER TABLE t1 ALTER COLUMN i DROP MASKING POLICY;
--sorted_result
SELECT * FROM t1;
ALTER TABLE t1 ALTER COLUMN i SET MASKING POLICY p1;

--error ER_MASKING_POLICY_COMPONENT_ERROR
UPDATE t1 SET j = i;
--error ER_MASKING_POLICY_COMPONENT_ERROR
UPDATE t1, t1 AS t2 SET t1.j = t2.i;
--error ER_MASKING_POLICY_COMPONENT_ERROR
UPDATE t1 SET i = i + 1;
--error ER_MASKING_POLICY_COMPONENT_ERROR
UPDATE t1, t1 AS t2 SET t1.i = t2.i + 1;
--error ER_MASKING_POLICY_COMPONENT_ERROR
UPDATE t1 SET j = i + 1;
--error ER_MASKING_POLICY_COMPONENT_ERROR
UPDATE t1 SET j = i + 2;
--error ER_MASKING_POLICY_COMPONENT_ERROR
UPDATE t1 SET j = j + 1 WHERE i < 10;

UPDATE t1 SET i = j + 1;

# Verify that the single-table UPDATE statement succeeded.
ALTER TABLE t1 ALTER COLUMN i DROP MASKING POLICY;
--sorted_result
SELECT * FROM t1;
ALTER TABLE t1 ALTER COLUMN i SET MASKING POLICY p1;

UPDATE t1, t1 AS t2 SET t1.i = t2.j + 2 WHERE t1.j = t2.j;

# Verify that the multi-table UPDATE statement succeeded.
ALTER TABLE t1 ALTER COLUMN i DROP MASKING POLICY;
--sorted_result
SELECT * FROM t1;
ALTER TABLE t1 ALTER COLUMN i SET MASKING POLICY p1;

--error ER_MASKING_POLICY_COMPONENT_ERROR
DELETE FROM t1 WHERE i < j;
--error ER_MASKING_POLICY_COMPONENT_ERROR
DELETE t1 FROM t1, t1 AS t2 WHERE t1.i < t2.j;
--error ER_MASKING_POLICY_COMPONENT_ERROR
DELETE t2 FROM t1, t1 AS t2 WHERE t1.i < t2.j;

DELETE FROM t1 WHERE t1.j > 3;
DELETE t1 FROM t1, t1 AS t2 WHERE t1.j = t2.j AND t2.j < 3;

# Verify that the DELETE statements succeeded.
ALTER TABLE t1 ALTER COLUMN i DROP MASKING POLICY;
--sorted_result
SELECT * FROM t1;
ALTER TABLE t1 ALTER COLUMN i SET MASKING POLICY p1;

DROP TABLE t1;

CREATE TABLE t2(id INT PRIMARY KEY, a INT MASKING POLICY p1, b INT);
INSERT INTO t2 VALUES (1, 1, 1), (2, 2, 2), (3, 3, 3);
--error ER_MASKING_POLICY_COMPONENT_ERROR
INSERT INTO t2 (id) VALUES (1) ON DUPLICATE KEY UPDATE b = a + 1;
INSERT INTO t2 (id) VALUES (2) ON DUPLICATE KEY UPDATE a = b + 1;
ALTER TABLE t2 ALTER COLUMN a DROP MASKING POLICY;
SELECT * FROM t2 ORDER BY id;
DROP TABLE t2;
