--source include/have_mac_os.inc

--error ER_FEATURE_UNSUPPORTED
CREATE RESOURCE GROUP test TYPE=USER VCPU=1-3 THREAD_PRIORITY=5;

--error ER_FEATURE_UNSUPPORTED
ALTER RESOURCE GROUP test VCPU=0;

--error ER_FEATURE_UNSUPPORTED
DROP RESOURCE GROUP test;

--error ER_FEATURE_UNSUPPORTED
SET RESOURCE GROUP test FOR 4;

--error ER_FEATURE_UNSUPPORTED
SET RESOURCE GROUP test FOR 4,5;

--error ER_FEATURE_UNSUPPORTED
SET RESOURCE GROUP test;

# INFORMATION_SCHEMA.RESOURCE_GROUPS shall return empty set.
SELECT * FROM INFORMATION_SCHEMA.RESOURCE_GROUPS;
