--echo #
--echo # MyISAM does not support undo tablespaces commands
--echo #

--source include/have_innodb_default_undo_tablespaces.inc

--echo #
--echo # InnoDB supports these undo tablespaces commands
--echo #

CREATE UNDO TABLESPACE undo_003 ADD DATAFILE 'undo_003.ibu' ENGINE InnoDB;

SELECT NAME, SPACE_TYPE, STATE FROM INFORMATION_SCHEMA.INNODB_TABLESPACES
       WHERE SPACE_TYPE = 'Undo' ORDER BY NAME;
SELECT TABLESPACE_NAME, FILE_NAME, FILE_TYPE FROM INFORMATION_SCHEMA.FILES
       WHERE FILE_NAME LIKE '%undo%' ORDER BY TABLESPACE_NAME;

ALTER UNDO TABLESPACE undo_003 SET ACTIVE ENGINE InnoDB;

ALTER UNDO TABLESPACE undo_003 SET INACTIVE ENGINE InnoDB;

let $inactive_undo_space = undo_003;
source include/wait_until_undo_space_is_empty.inc;

DROP UNDO TABLESPACE undo_003 ENGINE InnoDB;

SELECT NAME, SPACE_TYPE, STATE FROM INFORMATION_SCHEMA.INNODB_TABLESPACES
       WHERE SPACE_TYPE = 'Undo' ORDER BY NAME;
SELECT TABLESPACE_NAME, FILE_NAME, FILE_TYPE FROM INFORMATION_SCHEMA.FILES
       WHERE FILE_NAME LIKE '%undo%' ORDER BY TABLESPACE_NAME;

