include .defs.mk

TYPE := repserver

ARCHIVE_TARGET := repstorage

SOURCES = GCIContainer.cpp \
          GCIContainerPS.cpp \
          GCIBuffer.cpp \
          GCIPage.cpp \
          NodeGroupInfo.cpp \
          NodeGroup.cpp 

include $(NDB_TOP)/Epilogue.mk
