//>>built
define("dojox/mobile/bidi/TextBox",["dojo/_base/declare","dijit/_BidiSupport"],function(_1){
return _1(null,{_setTextDirAttr:function(_2){
if(!this._created||this.textDir!=_2){
this._set("textDir",_2);
if(this.value){
this.applyTextDir(this.focusNode||this.textbox);
}else{
this.applyTextDir(this.focusNode||this.textbox,this.textbox.getAttribute("placeholder"));
}
}
},_setDirAttr:function(_3){
if(!(this.textDir&&this.textbox)){
this.dir=_3;
}
},_onBlur:function(e){
this.inherited(arguments);
if(!this.textbox.value){
this.applyTextDir(this.textbox,this.textbox.getAttribute("placeholder"));
}
},_onInput:function(e){
this.inherited(arguments);
if(!this.textbox.value){
this.applyTextDir(this.textbox,this.textbox.getAttribute("placeholder"));
}
}});
});
