include .defs.mk
TYPE := ndbapi

PIC_ARCHIVE := Y
ARCHIVE_TARGET := socketclient

# Source files of non-templated classes (.cpp files)
SOURCES =  ClientInterface.cpp SocketService.cpp SocketClient.cpp

include $(NDB_TOP)/Epilogue.mk
