define({      
//begin v1.x content
	/* These are already handled in the default RTE
		amp:"ampersand",lt:"less-than sign",
		gt:"greater-than sign",
		nbsp:"no-break space\nnon-breaking space",
		quot:"quote",
	*/
	iexcl:"obrnuti uzvičnik",
	cent:"znak centa",
	pound:"znak funte",
	curren:"znak valute",
	yen:"znak jena\nyznak jena",
	brvbar:"isprekidana linija\nisprekidana vertikalna linija",
	sect:"znak sekcije",
	uml:"dijareza\nprored sijareze",
	copy:"znak autorskog prava",
	ordf:"indikator rednog broja ženskog roda",
	laquo:"lijevo usmjereni ugaoni navodnik\nlijevo usmjereni guillemet",
	not:"znak ne",
	shy:"meka crtica\ndiskrecijska crtica",
	reg:"registrovani znakn\nznak za registrovani zaštitni znak",
	macr:"makron\nsprored makrona\ncrta iznad\nAPL traka iznad",
	deg:"znak stepena",
	plusmn:"plus-minus znak\nplus-ili-minus znak",
	sup2:"superskript dva\nsuperskript sa cifrom dva\nkvadrat",
	sup3:"superskript tri\nsuperskript sa cifrom tri\nkub",
	acute:"akcenat akuta\nsprored akuta",
	micro:"znak mikro",
	para:"znak paragrafa\nznak paragrafa",
	middot:"srednja tačka\ngregorijanski zarez\ngrčka srednja tačka",
	cedil:"sedilja\nprored sedilje",
	sup1:"superskript jedan\nsuperskript sa cifrom jedan",
	ordm:"indikator rednog broja muškog roda",
	raquo:"desno usmjereni dupli ugaoni navodnik\ndesno usmjereni guillemet",
	frac14:"prost razlomak jedna četvrtina\nrazlomak jedna četvrtina",
	frac12:"prost razlomak jedna polovina\nrazlomak jedna polovina",
	frac34:"prost razlomak tri četvrtine\nrazlomak tri četvrtine",
	iquest:"obrnuti upitnik\nokrenuti upitnik",
	Agrave:"Latinsko veliko slovo A s grave akcentom\nLatinsko veliko slovo A s grave akcentom",
	Aacute:"Latinsko veliko slovo A s akcentom acute",
	Acirc:"Latinsko veliko slovo A s akcentom cirkumfleks",
	Atilde:"Latinsko veliko slovo A s akcentom tilde",
	Auml:"Latinsko veliko slovo A s akcentom diaeresis",
	Aring:"Latinsko veliko slovo A s krugom iznad\nLatinsko veliko slovo s krugom",
	AElig:"Latinsko veliko slovo AE\nLatinsko veliko spojeno slovo AE",
	Ccedil:"Latinsko veliko slovo C s akcentom cedilla",
	Egrave:"Latinsko veliko slovo E s akcentom grave",
	Eacute:"Latinsko veliko slovo E s akcentom acute",
	Ecirc:"Latinsko veliko slovo E s akcentom cirkumfleks",
	Euml:"Latinsko veliko slovo E s akcentom diaeresis",
	Igrave:"Latinsko veliko slovo I s akcentom grave",
	Iacute:"Latinsko veliko slovo I s akcentom acute",
	Icirc:"Latinsko veliko slovo I s akcentom cirkumfleks",
	Iuml:"Latinsko veliko slovo I s akcentom diaeresis",
	ETH:"Latinsko veliko slovo ETH",
	Ntilde:"Latinsko veliko slovo N s akcentom tilde",
	Ograve:"Latinsko veliko slovo O s akcentom grave",
	Oacute:"Latinsko veliko slovo O s akcentom acute",
	Ocirc:"Latinsko veliko slovo O s akcentom cirkumfleks",
	Otilde:"Latinsko veliko slovo O s akcentom tilde",
	Ouml:"Latinsko veliko slovo O s akcentom diaeresis",
	times:"znak množenja",
	Oslash:"Latinsko veliko slovo O sa crtom\nLatinsko veliko slovo O s kosom linijom",
	Ugrave:"Latinsko veliko slovo U s akcentom grave",
	Uacute:"Latinsko veliko slovo U s akcentom acute",
	Ucirc:"Latinsko veliko slovo U s akcentom cirkumfleks",
	Uuml:"Latinsko veliko slovo U s akcentom diaeresis",
	Yacute:"Latinsko veliko slovo Y s akcentom acute",
	THORN:"Latinsko veliko slovo THORN",
	szlig:"Latinsko malo slovo oštro s\ness-zed",
	agrave:"Latinsko malo slovo a s grave akcentom\nLatinsko malo slovo a s grave akcentom",
	aacute:"Latinsko malo slovo a s akcentom acute",
	acirc:"Latinsko malo slovo a s akcentom circumflex",
	atilde:"Latinsko malo slovo a s akcentom tilde",
	auml:"Latinsko malo slovo a s akcentom diaeresis",
	aring:"Latinsko malo slovo a s krugom iznad\nLatinsko malo slovo s krugom",
	aelig:"Latinsko malo slovo ae\nLatinsko malo spojeno slovo ae",
	ccedil:"Latinsko malo slovo c s akcentom cedilla",
	egrave:"Latinsko malo slovo e s akcentom grave",
	eacute:"Latinsko malo slovo e s akcentom acute",
	ecirc:"Latinsko malo slovo e s akcentom cirkumfleks",
	euml:"Latinsko malo slovo e s akcentom diaeresis",
	igrave:"Latinsko malo slovo i s akcentom grave",
	iacute:"Latinsko malo slovo i s akcentom acute",
	icirc:"Latinsko malo slovo i s akcentom cirkumfleks",
	iuml:"Latinsko malo slovo i s akcentom diaeresis",
	eth:"Latinsko malo slovo eth",
	ntilde:"Latinsko malo slovo n s akcentom tilde",
	ograve:"Latinsko malo slovo o s akcentom grave",
	oacute:"Latinsko malo slovo o s akcentom acute",
	ocirc:"Latinsko malo slovo o s akcentom cirkumfleks",
	otilde:"Latinsko malo slovo o s akcentom tilde",
	ouml:"Latinsko malo slovo o s akcentom diaeresis",
	divide:"znak dijeljenja",
	oslash:"Latinsko malo slovo o sa crtom\nLatinsko malo slovo o s kosom crtom",
	ugrave:"Latinsko malo slovo u s akcentom grave",
	uacute:"Latinsko malo slovo u s akcentom acute",
	ucirc:"Latinsko malo slovo u s akcentom cirkumfleks",
	uuml:"Latinsko malo slovo u s akcentom diaeresis",
	yacute:"Latinsko malo slovo y s akcentom acute",
	thorn:"Latinsko malo slovo thorn",
	yuml:"Latinsko malo slovo y s akcentom diaeresis",

// Greek Characters and Symbols
	fnof:"Latinsko malo slovo s kvačicom\nfinkcija\nflorin",
	Alpha:"Grčko veliko slovo alfa",
	Beta:"Grčko veliko slovo beta",
	Gamma:"Grčko veliko slovo gamma",
	Delta:"Grčko veliko slovo delta",
	Epsilon:"Grčko veliko slovo epsilon",
	Zeta:"Grčko veliko slovo zeta",
	Eta:"Grčko veliko slovo eta",
	Theta:"Grčko veliko slovo theta",
	Iota:"Grčko veliko slovo iota",
	Kappa:"Grčko veliko slovo kappa",
	Lambda:"Grčko veliko slovo lambda",
	Mu:"Grčko veliko slovo mu",
	Nu:"Grčko veliko slovo nu",
	Xi:"Grčko veliko slovo xi",
	Omicron:"Grčko veliko slovo omicron",
	Pi:"Grčko veliko slovo pi",
	Rho:"Grčko veliko slovo rho",
	Sigma:"Grčko veliko slovo sigma",
	Tau:"Grčko veliko slovo tau",
	Upsilon:"Grčko veliko slovo upsilon",
	Phi:"Grčko veliko slovo phi",
	Chi:"Grčko veliko slovo chi",
	Psi:"Grčko veliko slovo psi",
	Omega:"Grčko veliko slovo omega",
	alpha:"Grčko malo slovo alpha",
	beta:"Grčko malo slovo beta",
	gamma:"Grčko malo slovo gamma",
	delta:"Grčko malo slovo delta",
	epsilon:"Grčko malo slovo epsilon",
	zeta:"Grčko malo slovo zeta",
	eta:"Grčko malo slovo eta",
	theta:"Grčko malo slovo theta",
	iota:"Grčko malo slovo iota",
	kappa:"Grčko malo slovo kappa",
	lambda:"Grčko malo slovo lambda",
	mu:"Grčko malo slovo mu",
	nu:"Grčko malo slovo nu",
	xi:"Grčko malo slovo xi",
	omicron:"Grčko malo slovo omicron",
	pi:"Grčko malo slovo pi",
	rho:"Grčko malo slovo rho",
	sigmaf:"Grčko malo slovo zadnje sigma",
	sigma:"Grčko malo slovo sigma",
	tau:"Grčko malo slovo tau",
	upsilon:"Grčko malo slovo upsilon",
	phi:"Grčko malo slovo phi",
	chi:"Grčko malo slovo chi",
	psi:"Grčko malo slovo psi",
	omega:"Grčko malo slovo omega",
	thetasym:"Grčko malo slovo simbol theta",
	upsih:"Grčki upsilon sa simbolom kvačice",
	piv:"Grčki simbol pi",
	bull:"grafička oznaka\nmali crni krug",
	hellip:"horizontalne tri tačke\ntri tačke na kraju",
	prime:"prime\nminute\nstope",
	Prime:"dupli \nsekunde\ninči",
	oline:"crta iznad\sprored crte iznad",
	frasl:"kosa crta razlomka",
	weierp:"skriptno veliko P\nnadskup\nWeierstrass p",
	image:"veliko I gotičkog pisma\nimaginarni dio",
	real:"veliko R gotičkog pisma\nisimbol realnog dijela",
	trade:"znak zaštitnog znaka",
	alefsym:"simbol alef\nprvi transifiran kardinalni broj",
	larr:"strelica ulijevo",
	uarr:"strelica prema gore",
	rarr:"strelica udesno",
	darr:"strelica prema dole",
	harr:"strelica lijevo desno",
	crarr:"strelica prema dole koja zavija lijevo\noznaka kraja reda",
	lArr:"dupla strelica ulijevo",
	uArr:"dupla strelica prema gore",
	rArr:"dupla strelica udesno",
	dArr:"dupla strelica prema dole",
	hArr:"dupla strelica lijevo desno",
	forall:"za sve",
	part:"parcijalni diferencijal",
	exist:"tamo postoji",
	empty:"prazan skup\nnull skup\npromjer",
	nabla:"nabla\npovratna razlika",
	isin:"element od",
	notin:"nije element od",
	ni:"sadrži kao člana",
	prod:"n-arni proizvod\nznak proizvoda",
	sum:"n-arni zbroj",
	minus:"minus predznak",
	lowast:"operator zvjezdica",
	radic:"kvadratni korijen\noznaka korijena",
	prop:"proporcionalan sa",
	infin:"beskonačno",
	ang:"ugao",
	and:"logičko i\nwedge",
	or:"logičko ili\nvee",
	cap:"presjek\ncap",
	cup:"unija\ncup","int":"integral",
	there4:"prema tome",
	sim:"operator tilde\nvarira s\nslično",
	cong:"približno jednako",
	asymp:"približno jednako\nasimptotski",
	ne:"nije jednak",
	equiv:"identično",
	le:"manje ili jednako",
	ge:"veće ili jednako",
	sub:"podskup od",
	sup:"nadskup od",
	nsub:"nije podskup od",
	sube:"podskup ili jednak",
	supe:"nadskup ili jednak",
	oplus:"zaokruženi plus\nizravna suma",
	otimes:"zaokruženo puta\nvektorski produkt",
	perp:"čavlić prema gore\nortogonalno na\nvertikalno",
	sdot:"operator tačka",
	lceil:"lijevi plafonski\nAPL lijevi plafonski",
	rceil:"desni plafonski",
	lfloor:"lijevi podni\nAPL lijevi podni",
	rfloor:"desni podni",
	lang:"uglata zagrada ulijevo",
	rang:"uglata zagrada udesno",
	loz:"dijamant",
	spades:"boja crni pik",
	clubs:"boja crni tref\ndjetelina",
	hearts:"boja crno srce\nvalentine",
	diams:"boja crni karo",
	OElig:"Latinsko veliko spojeno slovo OE",
	oelig:"Latinsko malo spojeno slovo oe",
	Scaron:"Latinsko veliko slovo S s invertiranim cirkumfleksom",
	scaron:"Latinsko malo slovo s s invertiranim cirkumfleksom",
	Yuml:"Latinsko veliko slovo Y s akcentom diaeresis",
	circ:"cirkumfleks akcent slova modifikatora",
	tilde:"malena tilda",
	ensp:"en prostor",
	emsp:"em prostor",
	thinsp:"tanak prostor",
	zwnj:"ne-sastavljač nulte širine",
	zwj:"sastavljač nulte širine",
	lrm:"oznaka lijevo-desno",
	rlm:"oznaka desno-lijevo",
	ndash:"en crtica",
	mdash:"em crtica",
	lsquo:"lijevi jednostruki navodnik",
	rsquo:"desni jednostruki navodnik",
	sbquo:"jednostruki navodnik oblika male devetke",
	ldquo:"lijevi dupli navodnik",
	rdquo:"desni dupli navodnik",
	bdquo:"dupli navodnik oblika male devetke",
	dagger:"kama",
	Dagger:"dvostruka kama",
	permil:"znak mile",
	lsaquo:"jednostruki ugaoni navodnik ulijevo",
	rsaquo:"jednostruki ugaoni navodnik udesno",
	euro:"znak eura"
//end v1.x content
});

