#!/bin/bash

# Copyright (c) 2016, Oracle and/or its affiliates. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

# Process input file sql/mysqld.cc,
# to replace
# - ${DOXYGEN_GENERATION_DATE}
# - ${DOXYGEN_GENERATION_BRANCH}
# - ${DOXYGEN_GENERATION_REVISION}
# with actual values, respectively:
# - the current build date
# - the PB2 branch name ${BRANCH_NAME} if any, or the current git branch
# - the PB2 revision ${PUSH_REVISION} if any, or the current git revision

CMD1="s/\\\${DOXYGEN_GENERATION_DATE}/"`date -I`"/g"
CMD2="s/\\\${DOXYGEN_GENERATION_BRANCH}/"${BRANCH_NAME:="$(git rev-parse --abbrev-ref HEAD)"}"/g"
CMD3="s/\\\${DOXYGEN_GENERATION_REVISION}/"${PUSH_REVISION:="$(git log -1 --format=%H)"}"/g"

sed -e ${CMD1} -e ${CMD2} -e ${CMD3} $1

