def configure(conf):
  pass

def build(bld):
  mapr = bld.new_task_gen('cxx', 'shlib', 'node_addon')
  mapr.target = 'mapper'
  mapr.source = 'c-api.cc api-mapper.cc'
  
  outermapper = bld.new_task_gen('cxx', 'shlib', 'node_addon')
  outermapper.target = 'outermapper'
  outermapper.source = 'outer-mapper.cc'

  dlopen = bld.new_task_gen('cxx', 'shlib', 'node_addon')
  dlopen.target = 'debug_dlopen'
  dlopen.source = 'debug_dlopen.cpp'

  jscons = bld.new_task_gen('cxx', 'shlib', 'node_addon')
  jscons.target = 'jscons'
  jscons.source = 'js-constructor.cpp'


