include .defs.mk

TYPE := ndbapitest

BIN_TARGET := DbCreate
BIN_TARGET_ARCHIVES := lmc_User

CCFLAGS_LOC:= -I../include -I../../include

SOURCES := \
   mainPopulate.c\
   dbPopulate.c

include $(NDB_TOP)/Epilogue.mk

