def build(ctx):
  obj = ctx.new_task_gen("cxx", "shlib", "node_addon")
  obj.target = "ndbapi"
  obj.uselib_local = "libimpl_common"
  obj.rpath = ctx.env.rpath
  
  obj.source = "tie/node_module.cpp " + \
  "tie/Ndb_init_wrapper.cpp " + \
  "tie/Ndb_cluster_connection_wrapper.cpp "


