include .defs.mk

TYPE =			*

NONPIC_ARCHIVE =	N

PIC_ARCHIVE =		Y

ARCHIVE_TARGET =	odbcdictionary

SOURCES = \
			DictCatalog.cpp \
			DictSchema.cpp \
			DictTable.cpp \
			DictColumn.cpp \
			DictIndex.cpp \
			DictSys.cpp

include ../Extra.mk
include $(NDB_TOP)/Epilogue.mk
