def configure(conf):
  pass

# 
# The common_library module must be loaded before any others,
# to avoid linker errors.
# 
  
def build(bld):
  libcommon = bld.new_task_gen("cxx", "shlib", "node_addon")
  libcommon.target = "common_library"  
  libcommon.source = "src/async_common.cpp " + \
  "src/unified_debug.cpp " + \
  "src/debug_dlopen.cpp " + \
  "src/unified_debug_v8.cpp " + \
  "src/common_library.cpp"

