# Copyright (c) 2010, 2024, Oracle and/or its affiliates.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2.0,
# as published by the Free Software Foundation.
#
# This program is designed to work with certain software (including
# but not limited to OpenSSL) that is licensed under separate terms,
# as designated in a particular file or component or in included license
# documentation.  The authors of MySQL hereby grant you an additional
# permission to link the program and your derivative works with the
# separately licensed software that they have either included with
# the program or referenced in the documentation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License, version 2.0, for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA

#------------------------------------------------------------------------------

  SRC	= ./src/cpp

.PHONY:	all help dep dbg opt prf clean mostlclean clobber distclean \
	run.ndbapi run.crund
all:	dbg

help:
	@echo "dep		-- build dependencies"
	@echo "all		-- build all targets with default flags"
	@echo "dbg		-- build all targets with debug flags"
	@echo "opt		-- build all targets with optimizing flags"
	@echo "prf		-- build all targets with profiling flags"
	@echo "clean		-- delete temporary files"
	@echo "mostlyclean	-- also delete all generated files"
	@echo "distclean	-- delete also database and server log files"
	@echo ""
	@echo "benchmark execution targets:"
	@echo "run.crund (generic driver, uses property 'loads')"
	@echo "run.ndbapi"

dep dbg opt prf clean mostlyclean clobber:
	ant $@
	@cd $(SRC) && $(MAKE) $(MFLAGS) $@

distclean:
	rm -rf scripts/ndblog
	rm -f *~
	ant $@
	rm -f ./.ant-targets-build.xml
	@cd $(SRC) && $(MAKE) $(MFLAGS) $@

#------------------------------------------------------------------------------

# read the generic settings
include	env.properties

run.ndbapi run.crund:	$(SRC)/crund
	$(SRC)/crund \
	-p crundRun.properties -p crundNdb.properties

#------------------------------------------------------------------------------
