/*
   Copyright (c) 2020, Oracle and/or its affiliates.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License, version 2.0,
   as published by the Free Software Foundation.

   This program is also distributed with certain software (including
   but not limited to OpenSSL) that is licensed under separate terms,
   as designated in a particular file or component or in included license
   documentation.  The authors of MySQL hereby grant you an additional
   permission to link the program and your derivative works with the
   separately licensed software that they have included with MySQL.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License, version 2.0, for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA
*/

/*
 * Generated by dheadgen(1).
 */

#ifndef	_PROBES_MYSQL_D
#define	_PROBES_MYSQL_D

#ifdef	__cplusplus
extern "C" {
#endif

#define	MYSQL_CONNECTION_START(arg0, arg1, arg2)
#define	MYSQL_CONNECTION_START_ENABLED() (0)
#define	MYSQL_CONNECTION_DONE(arg0, arg1)
#define	MYSQL_CONNECTION_DONE_ENABLED() (0)
#define	MYSQL_COMMAND_START(arg0, arg1, arg2, arg3)
#define	MYSQL_COMMAND_START_ENABLED() (0)
#define	MYSQL_COMMAND_DONE(arg0)
#define	MYSQL_COMMAND_DONE_ENABLED() (0)
#define	MYSQL_QUERY_START(arg0, arg1, arg2, arg3, arg4)
#define	MYSQL_QUERY_START_ENABLED() (0)
#define	MYSQL_QUERY_DONE(arg0)
#define	MYSQL_QUERY_DONE_ENABLED() (0)
#define	MYSQL_QUERY_PARSE_START(arg0)
#define	MYSQL_QUERY_PARSE_START_ENABLED() (0)
#define	MYSQL_QUERY_PARSE_DONE(arg0)
#define	MYSQL_QUERY_PARSE_DONE_ENABLED() (0)
#define	MYSQL_QUERY_CACHE_HIT(arg0, arg1)
#define	MYSQL_QUERY_CACHE_HIT_ENABLED() (0)
#define	MYSQL_QUERY_CACHE_MISS(arg0)
#define	MYSQL_QUERY_CACHE_MISS_ENABLED() (0)
#define	MYSQL_QUERY_EXEC_START(arg0, arg1, arg2, arg3, arg4, arg5)
#define	MYSQL_QUERY_EXEC_START_ENABLED() (0)
#define	MYSQL_QUERY_EXEC_DONE(arg0)
#define	MYSQL_QUERY_EXEC_DONE_ENABLED() (0)
#define	MYSQL_INSERT_ROW_START(arg0, arg1)
#define	MYSQL_INSERT_ROW_START_ENABLED() (0)
#define	MYSQL_INSERT_ROW_DONE(arg0)
#define	MYSQL_INSERT_ROW_DONE_ENABLED() (0)
#define	MYSQL_UPDATE_ROW_START(arg0, arg1)
#define	MYSQL_UPDATE_ROW_START_ENABLED() (0)
#define	MYSQL_UPDATE_ROW_DONE(arg0)
#define	MYSQL_UPDATE_ROW_DONE_ENABLED() (0)
#define	MYSQL_DELETE_ROW_START(arg0, arg1)
#define	MYSQL_DELETE_ROW_START_ENABLED() (0)
#define	MYSQL_DELETE_ROW_DONE(arg0)
#define	MYSQL_DELETE_ROW_DONE_ENABLED() (0)
#define	MYSQL_READ_ROW_START(arg0, arg1, arg2)
#define	MYSQL_READ_ROW_START_ENABLED() (0)
#define	MYSQL_READ_ROW_DONE(arg0)
#define	MYSQL_READ_ROW_DONE_ENABLED() (0)
#define	MYSQL_INDEX_READ_ROW_START(arg0, arg1)
#define	MYSQL_INDEX_READ_ROW_START_ENABLED() (0)
#define	MYSQL_INDEX_READ_ROW_DONE(arg0)
#define	MYSQL_INDEX_READ_ROW_DONE_ENABLED() (0)
#define	MYSQL_HANDLER_RDLOCK_START(arg0, arg1)
#define	MYSQL_HANDLER_RDLOCK_START_ENABLED() (0)
#define	MYSQL_HANDLER_WRLOCK_START(arg0, arg1)
#define	MYSQL_HANDLER_WRLOCK_START_ENABLED() (0)
#define	MYSQL_HANDLER_UNLOCK_START(arg0, arg1)
#define	MYSQL_HANDLER_UNLOCK_START_ENABLED() (0)
#define	MYSQL_HANDLER_RDLOCK_DONE(arg0)
#define	MYSQL_HANDLER_RDLOCK_DONE_ENABLED() (0)
#define	MYSQL_HANDLER_WRLOCK_DONE(arg0)
#define	MYSQL_HANDLER_WRLOCK_DONE_ENABLED() (0)
#define	MYSQL_HANDLER_UNLOCK_DONE(arg0)
#define	MYSQL_HANDLER_UNLOCK_DONE_ENABLED() (0)
#define	MYSQL_FILESORT_START(arg0, arg1)
#define	MYSQL_FILESORT_START_ENABLED() (0)
#define	MYSQL_FILESORT_DONE(arg0, arg1)
#define	MYSQL_FILESORT_DONE_ENABLED() (0)
#define	MYSQL_SELECT_START(arg0)
#define	MYSQL_SELECT_START_ENABLED() (0)
#define	MYSQL_SELECT_DONE(arg0, arg1)
#define	MYSQL_SELECT_DONE_ENABLED() (0)
#define	MYSQL_INSERT_START(arg0)
#define	MYSQL_INSERT_START_ENABLED() (0)
#define	MYSQL_INSERT_DONE(arg0, arg1)
#define	MYSQL_INSERT_DONE_ENABLED() (0)
#define	MYSQL_INSERT_SELECT_START(arg0)
#define	MYSQL_INSERT_SELECT_START_ENABLED() (0)
#define	MYSQL_INSERT_SELECT_DONE(arg0, arg1)
#define	MYSQL_INSERT_SELECT_DONE_ENABLED() (0)
#define	MYSQL_UPDATE_START(arg0)
#define	MYSQL_UPDATE_START_ENABLED() (0)
#define	MYSQL_UPDATE_DONE(arg0, arg1, arg2)
#define	MYSQL_UPDATE_DONE_ENABLED() (0)
#define	MYSQL_MULTI_UPDATE_START(arg0)
#define	MYSQL_MULTI_UPDATE_START_ENABLED() (0)
#define	MYSQL_MULTI_UPDATE_DONE(arg0, arg1, arg2)
#define	MYSQL_MULTI_UPDATE_DONE_ENABLED() (0)
#define	MYSQL_DELETE_START(arg0)
#define	MYSQL_DELETE_START_ENABLED() (0)
#define	MYSQL_DELETE_DONE(arg0, arg1)
#define	MYSQL_DELETE_DONE_ENABLED() (0)
#define	MYSQL_MULTI_DELETE_START(arg0)
#define	MYSQL_MULTI_DELETE_START_ENABLED() (0)
#define	MYSQL_MULTI_DELETE_DONE(arg0, arg1)
#define	MYSQL_MULTI_DELETE_DONE_ENABLED() (0)
#define	MYSQL_NET_READ_START()
#define	MYSQL_NET_READ_START_ENABLED() (0)
#define	MYSQL_NET_READ_DONE(arg0, arg1)
#define	MYSQL_NET_READ_DONE_ENABLED() (0)
#define	MYSQL_NET_WRITE_START(arg0)
#define	MYSQL_NET_WRITE_START_ENABLED() (0)
#define	MYSQL_NET_WRITE_DONE(arg0)
#define	MYSQL_NET_WRITE_DONE_ENABLED() (0)
#define	MYSQL_KEYCACHE_READ_START(arg0, arg1, arg2, arg3)
#define	MYSQL_KEYCACHE_READ_START_ENABLED() (0)
#define	MYSQL_KEYCACHE_READ_BLOCK(arg0)
#define	MYSQL_KEYCACHE_READ_BLOCK_ENABLED() (0)
#define	MYSQL_KEYCACHE_READ_HIT()
#define	MYSQL_KEYCACHE_READ_HIT_ENABLED() (0)
#define	MYSQL_KEYCACHE_READ_MISS()
#define	MYSQL_KEYCACHE_READ_MISS_ENABLED() (0)
#define	MYSQL_KEYCACHE_READ_DONE(arg0, arg1)
#define	MYSQL_KEYCACHE_READ_DONE_ENABLED() (0)
#define	MYSQL_KEYCACHE_WRITE_START(arg0, arg1, arg2, arg3)
#define	MYSQL_KEYCACHE_WRITE_START_ENABLED() (0)
#define	MYSQL_KEYCACHE_WRITE_BLOCK(arg0)
#define	MYSQL_KEYCACHE_WRITE_BLOCK_ENABLED() (0)
#define	MYSQL_KEYCACHE_WRITE_DONE(arg0, arg1)
#define	MYSQL_KEYCACHE_WRITE_DONE_ENABLED() (0)

#ifdef  __cplusplus
}
#endif

#endif  /* _PROBES_MYSQL_D */
