cscript win\configure.js ^
 WITH_EXAMPLE_STORAGE_ENGINE ^
 WITH_FEDERATEDX_STORAGE_ENGINE ^
 WITH_MERGE_STORAGE_ENGINE ^
 WITH_PARTITION_STORAGE_ENGINE ^
 WITH_MARIA_STORAGE_ENGINE ^
 WITH_PBXT_STORAGE_ENGINE ^
 WITH_XTRADB_STORAGE_ENGINE
