define({      
//begin v1.x content
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color (e.g. gray / grey).
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "alisina plava",
antiquewhite: "antičko bela",
aqua: "akva",
aquamarine: "akvamarin",
azure: "azurna",
beige: "bež",
bisque: "biske",
black: "crna",
blanchedalmond: "blanširani badem",
blue: "plava",
blueviolet: "tamnoljubičasta",
brown: "braon",
burlywood: "peščano braon",
cadetblue: "kadet plava",
chartreuse: "šartruz",
chocolate: "čokoladna",
coral: "koral",
cornflowerblue: "različkova plava",
cornsilk: "kukuruzna svila",
crimson: "krmezna",
cyan: "cijan",
darkblue: "tamnoplava",
darkcyan: "tamnocijan",
darkgoldenrod: "tamnozlatna",
darkgray: "tamnosiva",
darkgreen: "tamnozelena",
darkgrey: "tamnosiva", // same as darkgray
darkkhaki: "tamna kaki",
darkmagenta: "tamna ciklama",
darkolivegreen: "tamna maslinastozelena",
darkorange: "tamno narandžasta",
darkorchid: "tamna orhideja",
darkred: "tamnocrvena",
darksalmon: "tamnolososova",
darkseagreen: "tamna morskozelena",
darkslateblue: "tamna škriljastoplava",
darkslategray: "tamna škriljastosiva",
darkslategrey: "tamna škriljastosiva", // same as darkslategray
darkturquoise: "tamna tirkizna",
darkviolet: "tamnoljubičasta",
deeppink: "tamnoružičasta",
deepskyblue: "tamna nebeskoplava",
dimgray: "dimnosiva",
dimgrey: "dimnosiva", // same as dimgray
dodgerblue: "šeret-plava",
firebrick: "pečena cigla",
floralwhite: "cvetno bela",
forestgreen: "šumski zelena",
fuchsia: "fuksija",
gainsboro: "gejnzboro",
ghostwhite: "duhovno bela",
gold: "zlatna",
goldenrod: "zlatica",
gray: "siva",
green: "zelena",
greenyellow: "žutozelena",
grey: "siva", // same as gray
honeydew: "mednica",
hotpink: "vrela ružičasta",
indianred: "indijansko crvena",
indigo: "indigo",
ivory: "slonovača",
khaki: "kaki",
lavender: "lavanda",
lavenderblush: "rumena lavanda",
lawngreen: "travnjak zelena",
lemonchiffon: "limunasto šifon",
lightblue: "svetlo plava",
lightcoral: "svetlo koral",
lightcyan: "svetlo cijan",
lightgoldenrodyellow: "svetlo zlatičasto žuta",
lightgray: "svetlo siva",
lightgreen: "svetlo zelena",
lightgrey: "svetlo siva", // same as lightgray
lightpink: "svetlo ružičasta",
lightsalmon: "svetlo lososova",
lightseagreen: "svetlo morskozelena",
lightskyblue: "svetlo nebeskoplava",
lightslategray: "svetlo škriljastosiva",
lightslategrey: "svetlo škriljastosiva", // same as lightslategray
lightsteelblue: "svetlo čelik plava",
lightyellow: "svetložuta",
lime: "limeta",
limegreen: "limeta zelena",
linen: "lanena",
magenta: "ciklama crvena",
maroon: "kestenjastomrka",
mediumaquamarine: "srednje akvamarin",
mediumblue: "srednje plava",
mediumorchid: "srednje orhideja",
mediumpurple: "srednje ljubičasta",
mediumseagreen: "srednje morskozelena",
mediumslateblue: "srednje škriljastoplava",
mediumspringgreen: "srednje prolećnozelena",
mediumturquoise: "srednje tirkizna",
mediumvioletred: "srednje ljubičastocrvena",
midnightblue: "ponoćno plava",
mintcream: "krem od mente",
mistyrose: "bledoružičasta",
moccasin: "mokasin",
navajowhite: "navaho bela",
navy: "tamnoplava",
oldlace: "stara čipka",
olive: "maslinasta",
olivedrab: "pastelnomaslinasta",
orange: "narandžasta",
orangered: "crvenonarandžasta",
orchid: "orhideja",
palegoldenrod: "bleda zlatica",
palegreen: "bledozelena",
paleturquoise: "bledotirkizna",
palevioletred: "bleda ljubičastocrvena",
papayawhip: "papaja sa šlagom",
peachpuff: "kolačići sa breskvom",
peru: "peru",
pink: "roze",
plum: "šljiva",
powderblue: "puder plava",
purple: "ljubičasta",
red: "crvena",
rosybrown: "ružičastobraon",
royalblue: "kraljevskoplava",
saddlebrown: "sedlo braon",
salmon: "losos",
sandybrown: "peščano braon",
seagreen: "morskozelena",
seashell: "školjka",
sienna: "sijena",
silver: "srebrna",
skyblue: "nebeskoplava",
slateblue: "škriljastoplava",
slategray: "škriljastosiva",
slategrey: "škriljastosiva", // same as slategray
snow: "sneg",
springgreen: "prolećnozelena",
steelblue: "čeličnoplava",
tan: "boja štavljene kože",
teal: "plavozelena",
thistle: "boja korova",
tomato: "paradajz crvena",
transparent: "providna",
turquoise: "tirkizna",
violet: "ljubičasta",
wheat: "pšenica",
white: "bela",
whitesmoke: "beli dim",
yellow: "žuta",
yellowgreen: "žutozelena"
//end v1.x content
});

