define({      
//begin v1.x content
	"clearFilterDialogTitle": "Исчисти филтер",
	"filterDefDialogTitle": "Филтер",
	"ruleTitleTemplate": "Правило ${0}",
	"conditionEqual": "еднакво",
	"conditionNotEqual": "не е еднакво",
	"conditionLess": "е помало од",
	"conditionLessEqual": "помало од или еднакво",
	"conditionLarger": "е поголемо од",
	"conditionLargerEqual": "поголемо од или еднакво на",
	"conditionContains": "содржи",
	"conditionIs": "е",
	"conditionStartsWith": "почнува со",
	"conditionEndWith": "завршува со",
	"conditionNotContain": "не содржи",
	"conditionIsNot": "не е",
	"conditionNotStartWith": "не почнува со",
	"conditionNotEndWith": "не завршува со",
	"conditionBefore": "пред",
	"conditionAfter": "после",
	"conditionRange": "опсег",
	"conditionIsEmpty": "е празно",
	"all": "сите",
	"any": "кои било",
	"relationAll": "сите правила",
	"waiRelAll": "Се совпаѓа со сите следни правила:",
	"relationAny": "кои било правила",
	"waiRelAny": "Се совпаѓа со кое било од следниве правила:",
	"relationMsgFront": "Се совпаѓа:",
	"relationMsgTail": "",
	"and": "и",
	"or": "или",
	"addRuleButton": "Додај правило",
	"waiAddRuleButton": "Додај ново правило",
	"removeRuleButton": "Отстрани правило",
	"waiRemoveRuleButtonTemplate": "Отстрани го правилото ${0}",
	"cancelButton": "Откажи",
	"waiCancelButton": "Откажи го овој дијалог",
	"clearButton": "Исчисти",
	"waiClearButton": "Исчисти го филтерот",
	"filterButton": "Филтрирај",
	"waiFilterButton": "Поднеси го филтерот",
	"columnSelectLabel": "Колона",
	"waiColumnSelectTemplate": "Колона за правилото ${0}",
	"conditionSelectLabel": "Услов",
	"waiConditionSelectTemplate": "Услов за правилото ${0}",
	"valueBoxLabel": "Вредност",
	"waiValueBoxTemplate": "Внесете вредност за филтер на правилото ${0}",
	"rangeTo": "до",
	"rangeTemplate": "од ${0} до ${1}",
	"statusTipHeaderColumn": "Колона",
	"statusTipHeaderCondition": "Правила",
	"statusTipTitle": "Лента за филтер",
	"statusTipMsg": "Кликнете на лентата за филтер тука за да филтрирате вредности во ${0}.",
	"anycolumn": "која било колона",
	"statusTipTitleNoFilter": "Лента за филтер",
	"statusTipTitleHasFilter": "Филтер",
	"statusTipRelAny": "Совпаѓање на кои било правила.",
	"statusTipRelAll": "Совпаѓање на сите правила.",
	"defaultItemsName": "ставки",
	"filterBarMsgHasFilterTemplate": "Се прикажува ${0} од ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "Нема применето филтер",
	"filterBarDefButton": "Дефинирај филтер",
	"waiFilterBarDefButton": "Филтрирај табела",
	"a11yFilterBarDefButton": "Филтер...",
	"filterBarClearButton": "Исчисти филтер",
	"waiFilterBarClearButton": "Исчисти го филтерот",
	"closeFilterBarBtn": "Затвори лента за филтер",
	"clearFilterMsg": "Со ова филтерот се отстранува и се прикажуваат сите достапни записи.",
	"anyColumnOption": "Која било колона",
	"trueLabel": "Точно",
	"falseLabel": "Неточно"
//end v1.x content
});

