#!/bin/sh -eux

${CC} --version

# Build and install libfido2.
mkdir build
(cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..)
make -C build
sudo make -C build install

# Check udev/fidodevs.
sudo update-alternatives --set awk "$(which original-awk)"
udev/check.sh udev/fidodevs
