/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sleepycat_db_Dbt */

#ifndef _Included_com_sleepycat_db_Dbt
#define _Included_com_sleepycat_db_Dbt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sleepycat_db_Dbt
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sleepycat_db_Dbt_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_sleepycat_db_Dbt
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sleepycat_db_Dbt_init
  (JNIEnv *, jobject);

/*
 * Class:     com_sleepycat_db_Dbt
 * Method:    create_data
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sleepycat_db_Dbt_create_1data
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
