\input texinfo  @c -*-texinfo-*-
@c
@c *********************************************************
@c
@c This is a dummy placeholder file for internals.texi in the
@c MySQL source trees.
@c
@c Note, that the internals documentation has been moved into a separate
@c BitKeeper source tree named "mysqldoc" - do not attempt to edit this
@c file! All changes to internals.texi should be done in the mysqldoc tree.
@c
@c See http://www.mysql.com/doc/en/Installing_source_tree.html
@c for information about how to work with BitKeeper source trees.
@c
@c This dummy file is being replaced with the actual file from the
@c mysqldoc tree when building the official source distribution.
@c
@c Please e-mail docs@mysql.com for more information or if
@c you are interested in doing a translation.
@c
@c *********************************************************
@c
@c %**start of header

@setfilename internals.info

@c We want the types in the same index
@syncodeindex tp fn

@ifclear tex-debug
@c This removes the black squares in the right margin
@finalout
@end ifclear

@c Set background for HTML
@set _body_tags BGCOLOR=silver TEXT=#000000 LINK=#101090 VLINK=#7030B0
@c Set some style elements for the manual in HTML form. 'suggested'
@c natural language colors: aqua, black, blue, fuchsia, gray, green,
@c lime, maroon, navy, olive, purple, red, silver, teal, white, and
@c yellow. From Steeve Buehler <ahr@YogElements.com>
@set _extra_head <style> code {color:purple} tt {color:green} samp {color:navy} pre {color:maroon} </style>

@settitle Dummy MySQL internals documentation for version @value{mysql_version}.

@c We want single-sided heading format, with chapters on new pages. To
@c get double-sided format change 'on' below to 'odd'
@setchapternewpage on

@paragraphindent 0

@c %**end of header

@ifinfo
@format
START-INFO-DIR-ENTRY
* mysql: (mysql).               MySQL documentation.
END-INFO-DIR-ENTRY
@end format
@end ifinfo

@titlepage
@sp 10
@center @titlefont{Empty placeholder for the MySQL Internals Documentation}
@sp 10
@center Copyright @copyright{} 1995-2003 MySQL AB
@c blank page after title page makes page 1 be a page front.
@c also makes the back of the title page blank.
@page
@end titlepage

@c This should be added. The HTML conversion also needs a MySQL version
@c number somewhere.

@iftex
@c change this to double if you want formatting for double-sided
@c printing
@headings single

@oddheading @thischapter @| @| @thispage
@evenheading @thispage @| @| MySQL Internal Reference for Version @value{mysql_version}

@end iftex

@node Top, (dir), (dir), (dir)

@ifinfo
This is an empty placeholder file for the MySQL internals documentation.

The real version of this file is now maintained in a separate BitKeeper
source tree!  Please see
@url{http://www.mysql.com/doc/en/Installing_source_tree.html} for more info
on how to work with BitKeeper.

Please do not attempt to edit this file directly - use the one in the
@code{mysqldoc} BK tree instead.

This file will be replaced with the current @code{internals.texi} when
building the official source distribution.
@end ifinfo

@bye
