@c FIX AGL 20011108 Extracted from manual.texi.
@c Should only be on website with new submits by webform.


@node MySQL Testimonials, Contrib, Users, Top
@appendix MySQL Testimonials

@cindex MySQL Testimonials

The section 'MySQL Users' contains a lot of different links to
MySQL users but doesn't provide that much information about how
they are using MySQL.  @xref{Users}. This section gives you an idea
of how other MySQL users are using MySQL to solve their problems.

Please note that all new stories are added on the MySQL website,
@uref{http://www.mysql.com/}.
Do let us know about @emph{your} success story too!

@itemize @bullet
@item 
@strong{Peter Zaitsev of Spylog.ru} writes:
I think you might be interested in my database size.  The whole database
is currently on 15 servers and I think it's about 60.000 of tables
containing about 5.000.000.000 of rows.  My mostly loaded server
currently holds about 10.000 of tables with 1.000.000.000 of rows in it.
Hugest tables have about 50.000.000 of rows, and this value will raise
as soon as I'll move to 2.4 kernel with large files. Currently I have to
delete much of logs for large sites to hold table sizes in 2Gb.

@item

