@c FIX AGL 20011108 Extracted from manual.texi.
@c Should only be on website.


@node Users, Contrib, Problems, Top
@appendix MySQL Users

@cindex users, of MySQL
@cindex news sites

This appendix lists users of MySQL that have given us permission
to list them in our documentation.  It is by far not a complete list, but
should give you a general idea of who uses MySQL and what it can
be used for.

@appendixsec General News Sites

@itemize @bullet

@item @uref{http://www.yahoo.com/} (Yahoo!)

@item @uref{http://slashdot.org/} (Slashdot: A pro-Linux/tech news and comment/discussion site)

@item @uref{http://www.linux.com/} (All about Linux)

@item @uref{http://www.linuxtoday.com/} (Linuxtoday)

@item @uref{http://www.32bitsonline.com/} (32Bits Online: because there's
more than one way to compute)

@item @uref{http://www.freshmeat.net/} (Freshmeat: News about new versions of computer-related stuff)

@end itemize

@cindex search engines, web
@cindex web search engines
@appendixsec Web Search Engines

@itemize @bullet

@item @uref{http://www.aaa.com.au/} (AAA Matilda Web Search)
@item @uref{http://www.whatsnu.com/} (What's New)
@item @uref{http://www.aladin.de/} (Aladin)
@item @uref{http://www.columbus-finder.de/} (Columbus Finder)
@item @uref{http://www.spider.de/} (Spider)
@item @uref{http://www.blitzsuche.de/} (Blitzsuche)
@item @uref{http://www.indoseek.co.id/} (Indoseek Indonesia)
@item @uref{http://www.yaboo.dk/} (Yaboo - Yet Another BOOkmarker)
@item @uref{http://www.ozsearch.com.au/} (OzSearch Internet Guide)
@item @uref{http://www.splatsearch.com/} (Splat! Search)
@item @uref{http://osdls.library.arizona.edu/} (The Open Source Digital Library System Project)
@end itemize

@appendixsec Information Search Engines Specialising in a Particular Area

@itemize @bullet

@item @uref{http://www.spylog.ru/} (SpyLOG ;  A very popular Web counter site)

@item @uref{http://www.tucows.com/} (TuCows Network; Free Software archive)

@item @uref{http://www.jobvertise.com/} (Jobvertise: Post and search for jobs)

@item @uref{http://www.musicdatabase.com/} (The Music Database)

@item @uref{http://www.soccersearch.com/} (Football -Soccer- search page)

@item @uref{http://www.headrush.net/takedown} (TAKEDOWN - wrestling)

@item @uref{http://www.lyrics.net/} (The International Lyrics Network)

@item @uref{http://TheMatrix.com/~matrix/band_search.phtml} (Musicians looking for other musicians; free service)

@item @uref{http://www.addall.com/AddBooks/Stores.html} (AddALL books searching and price comparison)

@item @uref{http://www.herbaria.harvard.edu/Data/Gray/gray.html} (Harvard's Gray Herbarium Index of Plant Names)

@item @uref{http://www.game-developer.com/} (The Game Development Search Engine)

@item @uref{http://www.theinnkeeper.com/} (The Innkeeper Vacation Guides)

@item @uref{http://www.macgamedatabase.com/} (The Mac Game Database uses PHP and MySQL)
@c From: Marc Antony Vose <suzerain@suzerain.com>

@item @uref{http://www.csse.monash.edu.au/publications/} (Research
Publications at Monash University in Australia)

@item @uref{http://www.ipielle.emr.it/bts/}
(Occupational Health & Safety Website database; a project for the ECC)
@c c.presutti@ipielle.emr.it

@item @uref{http://data.mch.mcgill.ca/} (Bioinformatics databases at the
Montreal Children's Hospital using MySQL)
@c saeed@www.debelle.mcgill.ca
@end itemize

@cindex online magazines
@cindex magazines, online
@appendixsec Online Magazines

@itemize @bullet
@item @uref{http://www.spoiler.com/} (Spoiler Webzine)
An online magazine featuring music, literature, arts, and design content.
@item @uref{http://www.linux-magazin.de/newsflash/} (Daily news about Linux in German language)
@item @uref{http://www.betazine.com/} (Betazine - The Ultimate Online Beta Tester's Magazine)
@item @uref{http://www.currents.net/ccinfo/aboutcc.html} (Computer Currents Magazine)
@end itemize

@cindex websites
@appendixsec Websites that Use MySQL as a Backend

@itemize @bullet

@item @uref{http://liftoff.msfc.nasa.gov/} (NASA)
@item @uref{http://kids.msfc.nasa.gov/} (NASA KIDS)
@item @uref{http://science.nasa.gov/} (Sience@@NASA)

@item @uref{http://www.handy.de/} (handy.de)

@item @uref{http://lindev.jmc.tju.edu/qwor/} (Qt Widget and Object Repository)

@item @uref{http://www.samba-choro.com.br/} (Brazilian samba site; in Portuguese)

@item @uref{http://pgss.iss.uw.edu.pl/en_index.ISS} (Polish General Social Survey)

@item @uref{http://www.expo2000.com/} Expo2000 - world-wide distribution of
tickets for this event is implemented using MySQL and Tcl/Tk. More than
5000 travel agencies all over the world have access to it.

@item @uref{http://www.freevote.com/} FreeVote.com is a free voting
service with millions of users.

@item @uref{http://f1.tauzero.se/} (Forza Motorsport)

@item @uref{http://www.dreamhost.com/} (DreamHost Web Hosting)

@end itemize

@cindex services
@appendixsec Domain/Internet/Web and Related Services

@itemize @bullet

@item @uref{http://www.wix.com/mysql-hosting/} (Registry of Web providers that
support MySQL)

@item @uref{http://www.yi.org/} (Dynamic DNS Services)

@item @uref{http://www.dynodns.net/} (Dynamic domain name service)

@item @uref{http://www.ods.org/} (Open DNS Project; free dynamic DNS service)

@c @item @uref{http://dynodns.net/} (Free dynamic DNS implementation)
@c EMAIL: A Moore <amoore@mooresystems.com>

@item @uref{http://www.hn.org/} (Hammernode; Public DNS Servers)

@item @uref{http://www.fdns.net/} (Free 3rd level domains)

@item @uref{http://worldcommunity.com/} (Online Database)

@item @uref{http://www.bigbiz.com/} (BigBiz Internet Services)

@item @uref{http://virt.circle.net/} (The Virt Gazette)

@item @uref{http://www.california.com/} (Global InfoNet Inc)

@item @uref{http://www.webhosters.com/} (WebHosters - A Guide to WWW Providers)

@item @uref{http://online.dn.ru/} (Internet information server)

@item @uref{http://www.worldnetla.net/} (WorldNet Communications - An Internet Services Provider)

@item @uref{http://www.netizen.com.au/} (Netizen: Australian-based Web consultancy)

@item @uref{http://www.trainingpages.co.uk/} (Search site for training courses in the UK)

@item @uref{http://chat.nitco.com/} (Gannon Chat; GPL. Written in Perl and Javascript)

@item @uref{http://www.addurls.com/} (A general links directory)

@item @uref{http://www.bookmarktracker.com/} (A Web-based bookmark management service)

@item @uref{http://www.cdrom.com/} (Walnut Creek CDROM)

@item @uref{http://www.wwwthreads.org/} (WWWThreads; Interactive discussion Forums)

@item @uref{http://pvmon.portici.enea.it/Meteo/} (In Italian; Storage data from meteo station)

@item @uref{http://www.buysell.net/} (Online "Person To Person" Auction)

@item @uref{http://tips.pair.com/} (Tips on Web development)

@item @uref{http://www.mailfriends.com/} (Mailfriends.com is a FREE service for
everybody who wants to find friends over the internet)

@item @uref{http://www.uninova.com/cgi-bin/wctelnets?list} (Web Page Telnet BBS List)

@item @uref{http://www.uninova.com/cnc.html} (UniNova Digital Postcards)

@c @item @uref{http://cabinboy.powersurfr.com/} (An Internet RFC search engine)

@item @uref{http://www.dslreports.com/} (DSL-provider search with reviews)
Made with MySQL and Modperl, all pages are generated dynamically out of
the MySQL database
@end itemize

@cindex PHP, websites
@appendixsec Websites that Use @code{PHP} and MySQL

@itemize @bullet
@c @item @uref{http://www.wh200th.com/} (White House 200th Anniversary site)

@item @uref{http://support.jgaa.com/} (Jgaa's Internet - Official Support Site)

@item @uref{http://io.incluso.com/} (Ionline - online publication) MySQL,
PHP, Java, Web programming, DB development

@item @uref{http://www.baboo.com/} (BaBoo - Browse and Bookmark. Free Web-based bookmark manager and Calendar)

@item @uref{http://www.courses.pjc.cc.fl.us/Schedule/}
(Course Schedule System at Pensacola Junior College)

@item @uref{http://www.fccj.org/} (Florida Community College at Jacksonville)

@item @uref{http://www.32bit.com/} (32bit.com; An extensive shareware / freeware archive)

@item @uref{http://www.jokes2000.com/} (Jokes 2000)
@c Added 990604; EMAIL: ah@dybdahl.dk

@item @uref{http://www.burken.nu/}
Burken is a webhotel that provides scripts, among other things,
for remote users, like counters, guestbooks etc.
@c Added 990608; EMAIL: spacedmp@SpaceDump.Burken.NU (Anders Olausson)

@item @uref{http://tips.pair.com/}
Contains tips on html, javascript, 2d/3d graphics, and PHP3/MySQL.
All pages are generated from a database.
@c Added 990614; EMAIL: downey@image.dk (Rune Madsen)

@item @uref{http://www.softwarezrus.com/}
Ecommerce site that is selling computers.
@end itemize

@cindex consultants, list of
@appendixsec MySQL Consultants

@itemize @bullet

@item @uref{http://www.ayni.com/} (Ayni AG)

@item @uref{http://worldcommunity.com/} (Online Database)

@item @uref{http://www2.dataguard.no/} (DataGuard; Uses MySQL and PHP)

@item @uref{http://wwits.net/programs/mysql.phtml} (WWITS; uses MySQL and PHP)

@item @uref{http://www.worldcommunity.com/} (WCN - The World Community Network)

@item @uref{http://www.chipcastle.com/} (Chip Castle Dot Com Inc)
@c Added 990603 EMAIL: chip@chipcastle.com (Chip Castle)

@item @uref{http://www.cyber.com.au/} (Cybersource Pty. Ltd)

@item @uref{http://www.spring.de/} (Spring infotainment gmbh & co. kg)
@c added 990905 "Oliver Pischke" <opischke@spring.de>

@item @uref{http://www.wamdesign.com/} (Wam Design develops websites using MySQL)
@c Added 990905; max@wamdesign.com

@item @uref{http://www.berkeleyconsultants.com/} (Berkeley Consultants Group)

@item @uref{http://www.jammconsulting.com/} (JAMM Consulting Inc)

@end itemize

@c Commented out by Arjen 011018, section is empty!
@c appendixsec Programming

@cindex web pages, miscellaneous
@appendixsec Uncategorised Pages

@itemize @bullet

@item @uref{http://www.feature-showcase.com/htmls/demo_mysql.sql} (AZC.COM's Feature Showcase)

@item @uref{http://www.teach.org.uk/subjects/trainingcourse/g.html} (Course Search)

@item @uref{http://www.northerbys.com/} (Northerbys Online Auctions)

@item @uref{http://www.schiphol.nl/flights/home.htm} (Amsterdam Airport Schiphol)

@item @uref{http://TheMatrix.com/seventhsin/query.phtml} (CD database)

@item @uref{http://TheMatrix.com/~flmm/GEAR.html} (Used Audio Gear Database)

@item @uref{http://www.kiss.de/musik-mueller/} (Musical note-sheets)

@item @uref{http://www.bagism.com/} (Bagism; A John Lennon fan page)

@item @uref{http://www.selftaught.com/} (US Folk art broker)

@item @uref{http://organizer.net/} (Mail reading on the Web)

@item @uref{http://www.mypage.org/} (Free home pages on www.somecoolname.mypage.org)

@item @uref{http://www.schulweb.de/} (Der Server f@"ur Schulen im Web - in German)

@item @uref{http://www.ald.net/} (Auldhaefen Online Services)

@item @uref{http://www.cary.net/} (CaryNET Information Center)

@item @uref{http://www.dataden.com/} (Dataden Computer Systems)

@item @uref{http://andree.grm.se/} (Andr@'emuseet; in Swedish)

@item @uref{http://www.him.net/} (HOMESITE Internet Marketing)

@item @uref{http://www.jade-v.com/techinfo.html} (Jade-V Network Services)

@item @uref{http://ww2010.atmos.uiuc.edu/(Gl)/abt/aknw/tech.rxml}
Weather World 2010 Technical Credits

@item @uref{http://gimp.foebud.org/registry/doc/}
About The Gimp plugin registry

@item @uref{http://www.fast-inc.com/Products/Archiver/database.html}
Java tool; archiver technical detail (Slightly optimistic about MySQL
ANSI-92 compliance)

@item @uref{http://www.gamesdomain.com/cheats/usrcheat.phtml} (Games Domain Cheats Database)

@item @uref{http://www.kcilink.com/poweredby/} (The "Powered By" Page; Kcilink)

@item @uref{http://www.netcasting.net/index.whtml} (Netcasting)

@item @uref{http://homepages.tig.com.au/~mjj/nbltips} (NBL: Australian National Basketball League; tipping)

@item @uref{http://www.cgishop.com/} (CGI shop)

@item @uref{http://www.whirlycott.com/} (Whirlycott: Website Design)

@item @uref{http://www.mtp.dk/} (Museum Tusculanum Press)

@item @uref{http://csdgi.historie.ku.dk/biblio/} (Centro Siciliano di Documentazione)

@item @uref{http://caribou.dyn.ml.org:8000/} (Quake statistics database)

@item @uref{http://www.astroforum.ch/} (Astroforum: Astrologie and related things; in German)

@item @uref{http://www.opendebate.com/} (OpenDebate - Interactive Polls & Open Discussion)

@item @uref{http://vermeer.organik.uni-erlangen.de/dissertationen/} (Online chemical dissertation server)

@item @uref{http://www.freschinfo.com/} (FreSch! The Free Scholarship Search Service)

@item @uref{http://www.nada.kth.se/~staffanu/pinball/} (Stockholm Pinball Locator)

@item @uref{http://www.hek.com/} (HEK - a construction company)

@item @uref{http://www.ebi.nl/} (Elsevier Business Information)

@item @uref{http://vaccination.medicallink.se/} (Medical Links; using ColdFusion and MySQL)

@item @uref{http://www.joblink-usa.com/} (Search for jobs & people at JobLink-USA)

@item @uref{http://www.skydive.net/competfs/} (Competition Formation Skydiving)

@item @uref{http://www.galaxy-net.net/} (Galaxy-NET Telecommunications; E-commerce and internal accounting)

@item @uref{http://www.borsen.dk/} (Denmark's leading business daily newspaper B@o{}rsen)

@item @uref{http://tmmm.simplenet.com/indb/} (The Internet NES Database)

@item @uref{http://www.russia.cz/} (Travel agency in Prague in 3 languages)

@item @uref{http://www.linkstation.de/} (Linkstation)

@item @uref{http://www.peoplestaff.com/} (Searchable online database at Peoplestaff)

@item @uref{http://www.dreamhorse.com/} (A searchable database system for horse classified ads)

@item @uref{http://pootpoot.com/} (The Poot site)

@item @uref{http://grateful.net/hw_html/} ("Playin' in the LAN"; a network monitoring suite)

@c Update from  Christopher Milton <cmilton@bwn.net> 1999-12-21
@item @uref{http://www.usapa.army.mil/} (U.S. Army Publishing Agency)

@item @uref{http://www.nekretnine.co.yu/} (Realestate handling in Yugoslavia)

@item @uref{http://demo.cpsoft.com/pims/devFAQ.html} (PIMS; a Patient Information Management System)

@item @uref{http://cpsoft.com/} (Pilkington Software Inc)

@item @uref{http://www.no-quarter.org/} (A Vietnam Veteran's Memorial - The Wall - database)

@item @uref{http://www.gamers-union.com/} (Gamer's Union specializes in auctions of used & out-of-print gaming material)

@item @uref{http://www.montereyhigh.com/office/dbul.php3} (A daily bulletin at Monterey High school)

@item @uref{http://www.myEastside.com/} (Community-owned site serving Lake
Washington's Eastside residents and businesses)

@item @uref{http://bowling-france.net/} (French bowling site)
@end itemize

Send any additions to this list to @email{webmaster@@mysql.com}.

@page




