#! /bin/sh
CMD="\
   AR='mwldnlm' \
   AR_FLAGS='-type library -o' \
   AS='mwasmnlm' \
   CC='mwccnlm -gccincludes' \
   CFLAGS='-dialect c -proc 686 -bool on -relax_pointers -DUSE_OLD_FUNCTIONS' \
   CXX='mwccnlm -gccincludes' \
   CXXFLAGS='-dialect c++ -proc 686 -bool on -relax_pointers' \
   LD='mwldnlm' \
   LDFLAGS='-entry _LibCPrelude -exit _LibCPostlude -flags pseudopreemption' \
   RANLIB=: \
   STRIP=: \
   ./configure --host=i686-pc-netware $* \
   --without-docs \
   --enable-local-infile \
   --with-extra-charsets=all \
   --prefix=N:/mysql \
   "
#rm -f config.cache config.log config.status
echo $CMD
eval $CMD

