define({      
//begin v1.x content
	"clearFilterDialogTitle": "Obriši filter",
	"filterDefDialogTitle": "Filter",
	"ruleTitleTemplate": "Pravilo ${0}",
	"conditionEqual": "jednako",
	"conditionNotEqual": "nije jednako",
	"conditionLess": "je manje od",
	"conditionLessEqual": "manje ili jednako",
	"conditionLarger": "je veće od",
	"conditionLargerEqual": "veće ili jednako",
	"conditionContains": "sadrži",
	"conditionIs": "je",
	"conditionStartsWith": "počinje sa",
	"conditionEndWith": "završava se sa",
	"conditionNotContain": "ne sadrži",
	"conditionIsNot": "nije",
	"conditionNotStartWith": "ne počinje sa",
	"conditionNotEndWith": "ne završava se sa",
	"conditionBefore": "pre",
	"conditionAfter": "posle",
	"conditionRange": "opseg",
	"conditionIsEmpty": "je prazno",
	"all": "sve",
	"any": "bilo koje",
	"relationAll": "sva pravila",
	"waiRelAll": "Podudaranje sa svim sledećim pravilima:",
	"relationAny": "bilo koje pravilo",
	"waiRelAny": "Podudaranje sa bilo kojim od sledećih pravila:",
	"relationMsgFront": "Podudaranje:",
	"relationMsgTail": "",
	"and": "i",
	"or": "ili",
	"addRuleButton": "Dodaj pravilo",
	"waiAddRuleButton": "Dodaj novo pravilo",
	"removeRuleButton": "Ukloni pravilo",
	"waiRemoveRuleButtonTemplate": "Ukloni pravilo ${0}",
	"cancelButton": "Otkaži",
	"waiCancelButton": "Otkaži ovaj dijalog",
	"clearButton": "Obriši",
	"waiClearButton": "Obriši filter",
	"filterButton": "Filter",
	"waiFilterButton": "Pošalji filter",
	"columnSelectLabel": "Kolona",
	"waiColumnSelectTemplate": "Kolona za pravilo ${0}",
	"conditionSelectLabel": "Uslov",
	"waiConditionSelectTemplate": "Uslov za pravilo ${0}",
	"valueBoxLabel": "Vrednost",
	"waiValueBoxTemplate": "Unesite vrednost koju treba filtrirati za pravilo ${0}",
	"rangeTo": "do",
	"rangeTemplate": "Od ${0} do ${1}",
	"statusTipHeaderColumn": "Kolona",
	"statusTipHeaderCondition": "Pravila",
	"statusTipTitle": "Traka sa filterima",
	"statusTipMsg": "Kliknite na traku sa filterima ovde da biste filtrirali vrednosti u ${0}.",
	"anycolumn": "bilo kojoj koloni",
	"statusTipTitleNoFilter": "Traka sa filterima",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelAny": "Podudaranje sa bilo kojim pravilom.",
	"statusTipRelAll": "Podudaranje sa svim pravilima.",
	"defaultItemsName": "stavke",
	"filterBarMsgHasFilterTemplate": "Prikazano je ${0} od ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "Filter nije primenjen",
	"filterBarDefButton": "Definiši filter",
	"waiFilterBarDefButton": "Filtriraj tabelu",
	"a11yFilterBarDefButton": "Filtriraj...",
	"filterBarClearButton": "Obriši filter",
	"waiFilterBarClearButton": "Obriši filter",
	"closeFilterBarBtn": "Zatvori traku sa filterima",
	"clearFilterMsg": "Ovo će ukloniti filter i prikazati sve dostupne zapise.",
	"anyColumnOption": "Bilo koja kolona",
	"trueLabel": "Tačno",
	"falseLabel": "Netačno"
//end v1.x content
});

