include .defs.mk

TYPE := util
BIN_TARGET := ndb_cpcd

# Source files of non-templated classes (.cpp files)
SOURCES = main.cpp CPCD.cpp Process.cpp APIService.cpp Monitor.cpp common.cpp

BIN_TARGET_LIBS += logger

include $(NDB_TOP)/Epilogue.mk
