#!/bin/sh
# Copyright (c) 2000, 2014, Oracle and/or its affiliates. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA

if test $# -ne 1
then
  echo "Copies # error messages from share/english/errmsg.txt to other message files"
  echo "Usage: $0 number_of_messages_to_copy"
  exit 1;
fi

FILE=/tmp/add.$$
tail -$1 share/english/errmsg-utf8.txt > $FILE
for i in `ls share/*/errmsg-utf8.txt | grep -v english`
do
  cat $FILE >> $i
done
rm $FILE

