#!/bin/sh
#
# see: The MySQL Test Framework :: 7 Creating and Executing Unit Tests
#   http://dev.mysql.com/doc/mysqltest/en/unit-test.html
# see: Test Anything Protocol (TAP)
#   http://testanything.org/wiki/index.php/Main_Page
#   http://en.wikipedia.org/wiki/Test_Anything_Protocol

# not sure which protocol version we're using
#echo "TAP version 13"

# test range
echo "1..6"

# this script gets invoked from $(top_srcdir)/unittest
cd ../storage/ndb/ndbjtie/test

# log file for output from this script
log="`pwd`/ndbjtie_unit_tests-t.log"
rm -f "$log"
touch "$log"

# run test
( cd .
    echo "running test from directory:" >> "$log" 2>&1
    echo "  `pwd`" >> "$log" 2>&1
    if ! ./test_mutils_decimal.sh >> "$log" 2>&1; then
	s="not "
    fi
    status="${s}ok 1 - test_mutils_decimal"
    echo "$status" >> "$log" 2>&1
    echo "" >> "$log" 2>&1
    echo "$status"
)

# run test
( cd .
    echo "running test from directory:" >> "$log" 2>&1
    echo "  `pwd`" >> "$log" 2>&1
    if ! ./test_mutils_charsetmap.sh >> "$log" 2>&1; then
	s="not "
    fi
    status="${s}ok 2 - test_mutils_charsetmap"
    echo "$status" >> "$log" 2>&1
    echo "" >> "$log" 2>&1
    echo "$status"
)

# run test
( cd .
    echo "running test from directory:" >> "$log" 2>&1
    echo "  `pwd`" >> "$log" 2>&1
    if ! ./test_ndbjtie_library.sh >> "$log" 2>&1; then
	s="not "
    fi
    status="${s}ok 3 - test_ndbjtie_library"
    echo "$status" >> "$log" 2>&1
    echo "" >> "$log" 2>&1
    echo "$status"
)

# run test
( cd .
    echo "running test from directory:" >> "$log" 2>&1
    echo "  `pwd`" >> "$log" 2>&1
    if ! ./test_unload_mutils_decimal.sh >> "$log" 2>&1; then
	s="not "
    fi
    status="${s}ok 4 - test_unload_mutils_decimal"
    echo "$status" >> "$log" 2>&1
    echo "" >> "$log" 2>&1
    echo "$status"
)

# run test
( cd .
    echo "running test from directory:" >> "$log" 2>&1
    echo "  `pwd`" >> "$log" 2>&1
    if ! ./test_unload_mutils_charsetmap.sh >> "$log" 2>&1; then
	s="not "
    fi
    status="${s}ok 5 - test_unload_mutils_charsetmap"
    echo "$status" >> "$log" 2>&1
    echo "" >> "$log" 2>&1
    echo "$status"
)

# run test
( cd .
    echo "running test from directory:" >> "$log" 2>&1
    echo "  `pwd`" >> "$log" 2>&1
    if ! ./test_unload_ndbjtie_library.sh >> "$log" 2>&1; then
	s="not "
    fi
    status="${s}ok 6 - test_unload_ndbjtie_library"
    echo "$status" >> "$log" 2>&1
    echo "" >> "$log" 2>&1
    echo "$status"
)

echo "done." >> "$log" 2>&1
