# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

load("@rules_cc//cc:cc_test.bzl", "cc_test")

# cc_test(
#     name = "dynamic_load_test",
#     srcs = [
#         "dynamic_load_test.cc",
#     ],
#     linkopts = [
#         "-ldl",
#     ],
#     tags = [
#         "api",
#         "test",
#     ],
#     deps = [
#         "//api",
#         "@com_google_googletest//:gtest_main",
#     ],
# )
